### ISSUE TITLE
clean up query hits when many buttons

### ISSUE THREAD

**Issue by cgalvarino** [glos/myglos#1]
@kknee What do you think of doing something like this?

http://manos.malihu.gr/tuts/jquery_thumbnail_scroller_horizontal_full.html
http://manos.malihu.gr/tuts/jquery_thumbnail_scroller_vertical_full.html

**Comment by kknee** [comment]
you mean to show all the variables in the search result record?  I think I'd rather not show any of the variables and have the user add the station to the map and be able to see the values in a pop-up or something.

If a user is interested in a particular station - adding all those variables, 1 at a time, will be a pain

**Comment by cgalvarino** [comment]
@kknee I have thrown away all the variable buttons and stuck in an Add to map button.

![image](https://cloud.githubusercontent.com/assets/180985/4775466/2cde6a9a-5bb8-11e4-939d-98270f480048.png)

This is what happens when you click on Levis Creek.  A dot is added, a popup appears, and the obs start coming in one by one.

![image](https://cloud.githubusercontent.com/assets/180985/4775492/69fd4130-5bb8-11e4-9c3a-7a1a4d242ec1.png)

I added the red arrow to show you that I am drawing that name on the map.  We might want it to stand out more, and we might want a special icon instead of a circle for these.

@bnfish Could you stylize the table a bit?  It all falls under an id=popup umbrella, and I already have a couple of things in style.css.

Finally, if you click on one of the var names, it fires a full GetObs request to populate the graph below.  Ben, I think it would be nice if the popup table had row hovers or something in place of the simple <a>'s I have here.  If that's too vague, let me know.

![image](https://cloud.githubusercontent.com/assets/180985/4775521/b9126fa2-5bb8-11e4-963f-c6aee8a104e5.png)

**Comment by kknee** [comment]
hallelujah!

**Comment by cgalvarino** [comment]
Looks good to me, @bnfish .  Thanks.

![image](https://cloud.githubusercontent.com/assets/180985/4798137/3c529c34-5e11-11e4-9be8-95a058547b83.png)

The comment I made about the horizontal scrollbar had zilch to w/ you.  It was just luck of the draw:  some of the obs sites have var names 1000000000 chars long.  It is what it is.
