### ISSUE TITLE
Datetime format changed in THREDDS?

### ISSUE THREAD

**Issue by tslawecki** [glos/myglos#101]
Jessica Lucido at USGS noted that the USGS ENDDAT tool is having problems with the datetime format in THREDDS retrievals of GLCFS model data. She says:

_The service used to provided dates with this format (e.g. "2016-01-01T00:00:00Z") and now uses this format (e.g. "2016-01-01 00:00:00.000 UTC"). Would it be possible to change the format back?_

Can we change the default format back (to ISO 8601?), or is there an option so specify the format in the TDS retrieval?

**Comment by kknee** [comment]
The sample link that Jessica provided seemed outdated - sent her a follow up email to check the current best time series link.  Waiting to hear back.

**Comment by lukecampbell** [comment]
>Here is an example request. I believe that we are hitting the THREDDS service.
> http://tds.glos.us/thredds/dodsC/glos/glcfs/archive2016/michigan/ncfmrc-2d/Lake_Michigan_-_Nowcast_-_2D_-_2016_best.ncd.ddx

for book keeping, it helps to keep this in the issue thread

**Comment by kknee** [comment]
This issue can be closed.

Temporary 4.3 instance was added for USGS to use while they updated their scripts to handle the 4.6 format.  Scripts were eventually updated and 4.3 instance shut down.
