### ISSUE TITLE
GLEAM - missing one child record

### ISSUE THREAD

**Issue by kkoch** [glos/myglos#103]
The Phosphorus Loading child record to the GLEAM collection does not appear mapable in portal (doesn't show on the pop-up).

Here is the GN metadata record in case that helps >
http://data.glos.us/metadata/srv/eng/main.home?uuid=5e49955f-5401-4ba8-88ae-9fe358b0c082

**Comment by lukecampbell** [comment]
JIRA Bug: MGLS-166

**Comment by kkoch** [comment]
May not be "our" issue.  From client > "The deal with phosphorus is that I don’t have it CDF-transformed correctly – I think I didn’t send the data to you at all because of it.  So that’s why there are 33 instead of 34 stressors."

I will close this for now until we hear more.
