### ISSUE TITLE
Guidance on ncsos access to HABs portal stations

### ISSUE THREAD

**Issue by tslawecki** [glos/myglos#106]
Need guidance on accessing data from ncSOS for Greg Cutrell and Reid Sawtell to read for asset landing page.

Also timeline for moving buoy data to ncSOS?

**Comment by kknee** [comment]
@gcutrell NDBC has great documentation on how to use ncSOS. @cheryldmorse will provide some links.

timeline for buoy data is 4/30 as outlined in our SOW.

**Comment by cheryldmorse** [comment]
@gcutrell Check out the  [NDBC SOS site](http://sdf.ndbc.noaa.gov/sos/) 
That site shows the required parameters and also has many examples.

**Comment by tslawecki** [comment]
So NDBC is running ncsos ... or are NDBC SOS and ncsos identical from the API side?



The theory here is that we can use the HABs ncsos endpoints to build test queries ahead of the 4/30 rollout of "everything as ncsos". Is there any separate documentation for the ncsos API ... or is it simply SOS-compliant so my question doesn't really make sense?



________________________________

**Comment by cheryldmorse** [comment]
@tslawecki, no NDBC is not running ncSOS. That site just shows you the required parameters and how to format a getObservation request. To make a getObservation request you would need to parse the getCapabilities response to determine what offerings/response formats/ observedProperties/etc.. exist for each dataset

**Comment by gcutrell** [comment]
@cheryldmorse is there an endpoint for ncSOS to get the getCapabilites?

**Comment by cheryldmorse** [comment]
@gcutrell There would be a getCapabilities for each netCDF file. Are you just looking for an example endpoint? ncSOS hasn't been setup yet for GLOS.

**Comment by tslawecki** [comment]
@cheryldmorse I thought the HABs portal was ncSOS-driven - if I'm wrong we need to consider a little short-term scrambling at this end.



________________________________

**Comment by kknee** [comment]
ncSOS is setup for HABS, all the endpoints are available from the TDS.  ncSOS is simply listed as another access option, e.g. 

![image](https://cloud.githubusercontent.com/assets/196868/25179693/f3c6a0b4-24d8-11e7-9210-120c17642aea.png)

**Comment by tslawecki** [comment]
@gcutrell I was a little narrow in my thinking, the server-side harvest can use whatever method to grab the data ... doesn't have to be SOS.



________________________________
