### ISSUE TITLE
Asset Landing Page - figure out semantics

### ISSUE THREAD

**Issue by tslawecki** [glos/myglos#107]
What do we call individual pages and the map? What URLs?

  greatlakesbuoys.org/whatever?ID=45176 (previous URL)
  data.glos.us/greatlakesbuoys/45176
  glb.glos.us/45176

Asset Landing Page? Asset Page? Buoy Page? ????

**Comment by everhamme** [comment]
I vote for  “station pages”

I’d love it if we could not break the old url for folks… or at least provide a way that the old url maps/forwards to the new one.. but recognize there might be a transition period

http://greatlakesbuoys.org/station_page.php?station=45169

**Comment by beckypearson** [comment]
Kristin and I can get behind naming the pages, station pages.  That is what NDBC calls them.

**Comment by kkoch** [comment]
Links from GN & Catalog called Station Page

![image](https://user-images.githubusercontent.com/6392982/27397717-4365667c-5685-11e7-9e50-72a7c76ed096.png)
