### ISSUE TITLE
Asset Landing Page - Access from portal.glos.us and glos.us

### ISSUE THREAD

**Issue by tslawecki** [glos/myglos#108]
Discuss at next DMAC call (4/6) how to integrate access to asset landing page into existing glos.us pages.

**Comment by kkoch** [comment]
Will need GN metadata record.  Can create one 'now' for greatlakesbuoys.org which can be used for testing placement and which can then be modified for nuance changes with the final asset page.

**Comment by tslawecki** [comment]
We have a show-and-tell scheduled with GLOS on Thursday 4/20. I'd like to have a link from the dev version of the data portal map view to the associated station page that "works" in the sense that there is a hyperlink in buoy popups that take the user to a station page. Can be crude, just needs to give a sense.

Also need to have links to the portal - not sure if this means map, catalog, or both - and maybe to the GeoNetwork record as well from the ALP.  Also links to associated data services, at a minimum for the TDS feed?

Adding @gcutrell, @kknee and @lukecampbell to assignees.

**Comment by kknee** [comment]
@tslawecki that doesn't give us much time.  Can you get us the links asap?  Were you thinking that the links are from the buoy titles?

![image](https://cloud.githubusercontent.com/assets/196868/25044877/2ffcbcb6-20f7-11e7-8a44-79f944572346.png)

**Comment by tslawecki** [comment]
For demo purposes we can just link all buoys to the same page, the important thing is to have that link available. We can populate later, probably based on buoy number/name in the format http://glos.us/glbuoys/buoyid (not yet available). We would want to have this fully working before IAGLR.



________________________________

**Comment by kknee** [comment]
@tslawecki ok, its there a link to a dev page that we should use for all?  Or should we use: http://glos.us/glbuoys/buoyid?

**Comment by tslawecki** [comment]
Let's get @gcutrell to tell us what to use for now.



________________________________

**Comment by gcutrell** [comment]
@kknee I'm planning on moving the current dev page location to Amazon's AWS Monday. If I provide the new link by then would that give you enough time to complete the task?

**Comment by gcutrell** [comment]
@kkoch The homepage is located at http://52.42.141.198/. Currently right now the only way to go to a specific buoy is through the home page.

**Comment by kknee** [comment]
@gcutrell received, we will try to get it linked to the portal in time.

I do not see anyway to get to an individual buoy, however: 

![image](https://cloud.githubusercontent.com/assets/196868/25100991/6e9b7184-2380-11e7-92e0-6b7e05888832.png)

**Comment by gcutrell** [comment]
@kknee I'm having to change location references in the code. Should be working in a bit. I just spoke with Tad and for Thursday I will just create two buoy.html sites for show that we can directly access from the portal. I'll get you those links shortly.

**Comment by gcutrell** [comment]
At a minimum we will have two stations we can reference. [http://52.42.141.198/45029](http://52.42.141.198/45029) and [http://52.42.141.198/45169](http://52.42.141.198/45169). I'll be working on these pages today and tomorrow.

**Comment by kknee** [comment]
@gcutrell @tslawecki - can you clarify exactly what we should link in the portal?  Last week @tslawecki said to link all buoys to the same homepage, but now it sounds like we should be linking two buoys to their individual pages.  Please confirm which route we should take and we'll get this implemented.  

@kkoch are you planning on entering these links into GN records for each station?

**Comment by tslawecki** [comment]
For this week any link should go to a station page, which can be the same one for all buoys with links.


-------- Original message --------

**Comment by kknee** [comment]
@tslawecki ok, so link everything to  http://52.42.141.198/ or http://52.42.141.198/45029?

**Comment by tslawecki** [comment]
Yes. We are just showing the concept.


-------- Original message --------

**Comment by kkoch** [comment]
All buoys that are currently in GLBuoys site are linked to 45029 [http://52.42.141.198/45029] in order to test.

Entered in GeoNetwork  with the Tag of "Station Page".  Will update these to actual links (and/or remove the incorrect link shortly).

With the exception of GLRCMET, 45002 and 45007 [these buoys do not appear in the portal]. I also added to all the HABs stations making the assumption that we will have asset pages for them as well.

**Comment by kkoch** [comment]
All GN records point to actual landing page

**Comment by kknee** [comment]
@kkoch I believe this can be closed as we have links to station pages from the Portal Catalog and a separate issue for linking to popups, #138
