### ISSUE TITLE
45172 (NMU Grand Marais) - No Data

### ISSUE THREAD

**Issue by kknee** [glos/myglos#11]
NMU Grand Marais buoy now redeployed/online.
Status page shows that we are receiving data and there is current data on NDBC and GLBuoys

There is no data in the obs cache - http://data.glos.us/portal/getObsByPlatform.php?provider=glos&platform=45172+-+Grand+Marais+Buoy

**Comment by kkoch** [comment]
@gwang still same issue as above. Need status.

**Comment by kkoch** [comment]
Seems to be fixed.
