### ISSUE TITLE
Address missing files in GLCFS forecast from new year

### ISSUE THREAD

**Issue by tslawecki** [glos/myglos#111]
We've identified a problem with GLCFS forecast timestamp being off by 24 hours, likely attributable to missing 1/1/2017 and/or 1/2/2017 files. Suggest @gcutrell talk with Guan further about whether it's feasible to address through catalog fix, code change (not sure what code), or creation of blank netcdfs.

**Comment by tslawecki** [comment]
Figuring out the right way to test for this condition (maybe count of files in Forecast directory) would be good.

**Comment by tslawecki** [comment]
Hold on -- Greg Lang just advised that he has a restore request on and should know shortly if the files are available.

**Comment by gcutrell** [comment]
Added missing model runs Greg L. provided for DOY 001 and 002 for all lakes and restarted thredds. Using the large wave event around 4/7 both Lake Erie and Michigan forecast look good now. Guan has a script to check the GLCFS but I'll see what is being done in the script and make sure any alert emails are not being sent to Guan.

**Comment by kknee** [comment]
@gcutrell sounds like we're all set here, so closing.  Please re-open if I'm incorrect.
