### ISSUE TITLE
External links display in map view

### ISSUE THREAD

**Issue by kkoch** [glos/myglos#114]
When you click on External Links in Catalog you see any/all links created in GN

![image](https://cloud.githubusercontent.com/assets/6392982/25142814/463c371c-2436-11e7-884c-2814b8e94ff0.png)

When you click on the "i" icon in Map view, you only see metadata link.  

![image](https://cloud.githubusercontent.com/assets/6392982/25142937/a678a476-2436-11e7-83fa-e2445ae1789c.png)

[Didn't we used to see them all there before too?  Regardless - would think it makes sense to see everything on map as well, so am adding this as an enhancement in case it's not a bug.]

**Comment by kknee** [comment]
@kkoch we can do whatever makes the most sense.  But per this issue that we just closed this morning: https://github.com/glos/myglos/issues/14.  I thought we had decided to change the map view to metadata only.

**Comment by kkoch** [comment]
Ah that’s where it got confused.  Glad I wasn’t dreaming that it used to be there.

No - #14 was to correct the wording of “data source” to metadata.  Never had anything to do with removing the other links.

**Comment by kkoch** [comment]
Not quite sure what to call this.  Isn't really an enhancement and not really a bug since it was something purposefullly (albeit accidently) removed.  But would be a very good thing if easy to bring back for the asset landing page project since we should show Station Page link if someone clicks on the "i" as well.

How easy/quick is it to put that back in place?

**Comment by tslawecki** [comment]
Confirming we would like to have it back, but noting that we can live without it for tomorrow.



________________________________

**Comment by kkoch** [comment]
BTW Very strange that I see multiple links for some things and not others.  Although it is also strange that on this I see the phrase "data source" instead of "metadata record" for the GN link so am guessing there is code that was changed for buoys but not for other non-mappable items.

![image](https://cloud.githubusercontent.com/assets/6392982/25441404/278eda6e-2a70-11e7-91df-d8783ec5e049.png)

So to clarify:
a) definitely want to see multiple links consistently for any and all items that we pull from GN. Should appear both in the Catalog view for external links as well as when the user clicks on the "i" icon in the Map view or if it is a non-mappable link (like above)
b) I want to see the phrase 'metadata record' (not 'data source') anytime it is the link the users would use to go to the GeoNetwork record.

**Comment by kkoch** [comment]
@Bobfrat I assigned you since this is something I think you can take care of pretty quickly (?) and it's been hanging around awhile.  If it really belongs to someone else, feel free to re-asign.

**Comment by Bobfrat** [comment]
This is on dev site now for testing http://dev.oceansmap.com/myglos/#. There are a bunch of updates on Dev and I will push these updates to production once we're happy.

**Comment by kkoch** [comment]
Close but not quite >  Top one is when I click on the "i" in the catalog nav. Has the right links but not liking the double spacing there.  Bottom one is when I click on the title and it shows on the map - still seeing 'data source' there. 

![image](https://user-images.githubusercontent.com/6392982/28224924-da2d5af8-689e-11e7-9159-0d7f98b24bb9.png)

**Comment by Bobfrat** [comment]
@kkoch you can see the updates on http://dev.oceansmap.com/myglos/# now.

Some other updates on dev include station page links in the popup, the Custom Portals category, and adding Organization field (and date created) to user profiles and the feedback form. Please let me know what you think. I can push to production if you give it your blessing.

**Comment by kkoch** [comment]
Woo hoo.  Everything looks great @bobfrat.  Feel free to find a good time to push to production.

**Comment by Bobfrat** [comment]
Ok all set 👍
