### ISSUE TITLE
Redirect data.glos.us/glatos to glatos.glos.us

### ISSUE THREAD

**Issue by IWN-Currents** [glos/myglos#115]
@lukecampbell - This feels like you, LMK if not. The GLATOS folk are done with data.glos.us/glatos and would like to have all traffic there redirected to glatos.glos.us. Is this best done at the site level> Might we need to add a 404? Copying @kknee FYI, scheduling is important. 

Apparently Cam sent me an email requesting this several weeks ago but I never received it, so client is antsy ...

**Comment by tslawecki** [comment]
BTW, IWN-Currents is a clone of me ...

**Comment by lukecampbell** [comment]
On data.glos.us, change `/etc/httpd/conf/httpd.conf` **Lines 1073** from 

```
RailsBaseURI /glatos
<Directory /var/www/html/data.glos/glatos>
  Allow from all
  Options -MultiViews -Indexes
</Directory>
```

To 

```
Redirect permanent /glatos http://glatos.glos.us
```

After that, restart apache with

```
sudo service httpd restart
```

You can do this whenever you want, let me know if you have any trouble.

**Comment by tslawecki** [comment]
Thanks @lukecampbell - changed httpd.cong and restarted apache per directions, and checked that data.glos.us/glatos is redirected to glatos.glos.us per client request.
