### ISSUE TITLE
Portal need to extend the disk volume

### ISSUE THREAD

**Issue by kkoch** [glos/myglos#118]
404 not found for portal.glos.us

**Comment by kknee** [comment]
it was working after the updates to production yesterday - I tested late last night

**Comment by tslawecki** [comment]
Here's a current traceroute ...



Tracing route to portal.glos.us [64.9.208.40]
over a maximum of 30 hops:

  1    47 ms     2 ms     1 ms  10.89.254.253
  2     3 ms     5 ms     4 ms  173-167-227-78-ip-static.hfc.comcastbusiness.net [173.167.227.78]
  3    10 ms    18 ms    26 ms  96.120.41.109
  4    14 ms    15 ms    36 ms  te-3-8-ur02.ypwest.mi.michigan.comcast.net [68.85.48.5]
  5    48 ms    41 ms    23 ms  te-0-8-0-3-ar02.pontiac.mi.michigan.comcast.net [162.151.103.69]
  6    26 ms    18 ms    28 ms  69.139.254.70
  7    20 ms    19 ms    21 ms  50-205-139-226-static.hfc.comcastbusiness.net [50.205.139.226]
  8    25 ms    30 ms     *     gross225.pinemountainsite.com [64.9.222.225]
  9    63 ms    28 ms    15 ms  avs-fw-vdom01.onlinetech.com [64.9.192.41]
 10    16 ms    33 ms    23 ms  mail3.onlinetech.net [64.9.208.40]

Trace complete.

________________________________

**Comment by kkoch** [comment]
threads:
The portal.glos.us VM that runs the portal ran out of space. It only has 20 GiB on it.
It's a local GLOS VM.
Space recommendation? 100 GiB would be safer. We don't use a whole lot of space. The docker images take up the most room which are a few gigs but I can clean them up after deployments to keep the space down. ElasticSearch which is the search engine does take up quite a bit of room and as we add records it goes up. If 100 GiB is unreasonable then 50 GiB is ok.
Tad has also brought Elliott (LTI) in for possible assistance.
Also Luke asks: Also, if I reboot the VM, will it come back on the same IP? Because everything is stuck and I can't terminate docker.

**Comment by tslawecki** [comment]
We are restoring the Wed 10 PM snapshot, should be back up around 11:30 AM.

Two follow-up items we may want to turn into separate issues:

1) Monitoring up/down for portal.glos.us --- we should have been notified rather than serendipitously discovering problem. Was this already being monitored by RPS, or do we need to add. 

1a) Add monitoring of CPU/disk/RAM for portal.glos.us for munin.

2) Restore from Veeam is taking longer than desirable. How do we speed it up.

**Comment by kkoch** [comment]
Looks like it's back?

**Comment by lukecampbell** [comment]
It's back but we still need to extend the disk volume which will require a reboot at some point in the future.

**Comment by tslawecki** [comment]
This is completed.
