### ISSUE TITLE
Documentation update

### ISSUE THREAD

**Issue by kkoch** [glos/myglos#119]
Recent issues with GN and the Portal bring to my attention that we urgently need to update the following document in the Wiki:

https://drive.google.com/file/d/0B7pJZVmOuWvzU0FUZERyUGZhcjg/edit?usp=sharing

I've attached owners as I know them.  Please within the next couple of weeks make sure 
a) the information is correct and 
b) include a list of the VM's, their IP, their 'common name' (e.g., GN25 for 64.9.208.34), plus any other pertinent information.  

Do NOT include passwords.

**Comment by kknee** [comment]
I will check with Ben Adams on location of documentation updates that were done in Nov/Dec 2016

**Comment by kknee** [comment]
updated documentation posted to Google Drive (https://drive.google.com/drive/folders/0B7pJZVmOuWvzZU9EUXZLazkzalU)

See Annotated GLOS Master Documentation
