### ISSUE TITLE
45027 Missing Air Temp

### ISSUE THREAD

**Issue by kknee** [glos/myglos#120]
Data appears in the obs cache, but not in the portal pop-up

obs cache: http://data.glos.us/portal/getObsByPlatform.php?provider=glos&platform=UMD+Coastal+Buoy

**Comment by kkoch** [comment]
We need to remember that if the PI changes a parameter name (e.g., was "Air Temperature" and now they present it as "AirTemperature" (had a space and now doesn't), I need to make that fix in GeoNetwork.  

For UMD this was the case so I've made the correction in GN.  It is something I check each week (or more often during the season) but before we think it is a huge problem, check with me and I'll make sure we don't have a disconnect between GN and Obs.
