### ISSUE TITLE
Increase frequency of thredds/buoy files

### ISSUE THREAD

**Issue by gcutrell** [glos/myglos#121]
Do we have the capacity to increase the frequency at which the buoy netcdf's are updated on thredds? The current greatlakesbuoys is generally only 10-20 minutes behind actual time and we really need to try and match it for the new website. We are currently pulling data from Thredds every 10 minutes. 

@kknee @cheryldmorse

**Comment by kknee** [comment]
@gcutrell  - we currently harvest once an hour.  @cheryldmorse will update to every 10 minutes tomorrow morning and keep an eye on it throughout the day to make sure that each harvester process finishes before the next one starts and that we're not impacting TDS performance.

**Comment by gcutrell** [comment]
@kknee Great! Thanks! I think we could get away with once every 15 minutes without people complaining but every ten minutes would be optimal since most buoys report at that frequency.

**Comment by cheryldmorse** [comment]
@gcutrell The data is being harvested every 10 minutes now.
