### ISSUE TITLE
NDBC buoys not available in Data Portal!

### ISSUE THREAD

**Issue by tslawecki** [glos/myglos#125]
I was cross-checking between Boater's Tool and Data Portal this morning, and noticed that I could not get 45006 or 45008 in Data Portal - 45005 seems to be the only buoy in the NDBC collection.

**Comment by kkoch** [comment]
I also briefly noticed this the other day when I was working on GLBuoys that I wasn’t seeing expected NDBC buoys in Portal but was immersed and figured I’d done something odd on my end and then didn’t remember to revisit.  

When we search for NDBC and partner stations and add to map all I’m seeing are NWS stations (e.g., 
Station bsbm4 - Big Sable Point, MI ) not the buoys (e.g. 45006 etc.).  The buoys you see in the image below are our GN cataloged ones >
![image](https://cloud.githubusercontent.com/assets/6392982/26497288/003b9eca-41f9-11e7-9b96-2d040dfa47ff.png)


If I look at legacy portal they are there, so something is disconnected for production.  Here is a snapshot from the legacy >
![image](https://cloud.githubusercontent.com/assets/6392982/26497170/6eb60418-41f8-11e7-9c3b-7e1e67c4ea70.png)

**Comment by kknee** [comment]
This is updated on dev (dev.oceansmap.com/myglos) and needs to be pushed to production

**Comment by kknee** [comment]
deployed on production
