### ISSUE TITLE
Missing *_20170608.nc files?

### ISSUE THREAD

**Issue by tslawecki** [glos/myglos#129]
As noted to dmac@glos.us, the Buoy Portal is showing many out-of-date stations. Checking, I saw that (e.g.) there is no 45023_20170608.nc file for today's observations, though the Data Portal shows 8 AM observations. I did do a quick check - there is still disk space on the thredds server and the NAS.  @kknee , I'm thinking this is for @cheryldmorse to check into?

**Comment by cheryldmorse** [comment]
This was an issue with storage.glos.us not accepting incoming connections. A reboot solved the issue.

**Comment by everhamme** [comment]
Any idea if this might be a recurring issue?  Do we have any checks in place to actively notify us of issues other than waiting for a user to notify?

**Comment by kknee** [comment]
We can set up a daily report on the latest files and highlight those that are more than xx hours old.  Probably a couple of days of effort to setup.  Let me know if we should proceed.

**Comment by everhamme** [comment]
Greg has a similar automated  email report setup for the old gl buoys.    I'm sure he could adapt with very little effort.


Greg can respond?



Ed Verhamme
Project Engineer
LimnoTech www.limno.com
Ph: (734) 332-1200<tel:(734)%20332-1200>
Direct/Cell:  (734) 681-0577<tel:(734)%20681-0577>
everhamme@limno.com<mailto:everhamme@limno.com>


-------- Original message --------

**Comment by tslawecki** [comment]
I think that this is a different type of fault ... what we need is an alert that the ssh is not working.

________________________________

**Comment by everhamme** [comment]
A check on the glbuoys.glos.us timestamps per buoy would catch a host of problems.



Ed Verhamme
Project Engineer
LimnoTech www.limno.com
Ph: (734) 332-1200<tel:(734)%20332-1200>
Direct/Cell:  (734) 681-0577<tel:(734)%20681-0577>
everhamme@limno.com<mailto:everhamme@limno.com>


-------- Original message --------

**Comment by kknee** [comment]
Agree – first step is to be alerted that they are not current, then we can work out why.

**Comment by tslawecki** [comment]
Btw something's  off again in case anyone is anle to check.
-------- Original message --------

**Comment by everhamme** [comment]
Many many stations aren't current as of now



Ed Verhamme
Project Engineer
LimnoTech www.limno.com
Ph: (734) 332-1200<tel:(734)%20332-1200>
Direct/Cell:  (734) 681-0577<tel:(734)%20681-0577>
everhamme@limno.com<mailto:everhamme@limno.com>


-------- Original message --------

**Comment by kknee** [comment]
@everhamme aren't current where?  Spot checked portal and TDS and am seeing 6/13/17 data in both places.

**Comment by tslawecki** [comment]
http://glbuoys.glos.us ...

________________________________

**Comment by tslawecki** [comment]
Two examples:



  45028 is > 6 hours old, but that's consistent with data.glos.us/status, which suggests UMnD is having some sort of problem, so *maybe* this is all right.



  45001 is also outdated, but it's more problematic: I can't get to 45001 (NDBC) in portal.glos.us at all. NBDC link shows it as current, so two problems here:



  - glbuoys harvest



  - display/access in main data portal

________________________________

**Comment by kknee** [comment]
taking 45176 as an example- same deal, data is more than 6 hours old but that is consistent in the portal and TDS.  

For 45001 we may need to update the NDBC buoy collection layer

**Comment by tslawecki** [comment]
NDBC is an existing issue - I'm surprised it's still open ... https://github.com/glos/myglos/issues/125



Is this a Kathy or RPS issue?



________________________________

**Comment by kknee** [comment]
This was an issue with the NDBC collection, which we updated and deployed to dev to keep an eye on: http://dev.oceansmap.com/myglos/#

I think we're probably good to push to production

**Comment by everhamme** [comment]
About 30 were red this morning on glbuoys.glos.us



Ed Verhamme
Project Engineer
LimnoTech www.limno.com
Ph: (734) 332-1200<tel:(734)%20332-1200>
Direct/Cell:  (734) 681-0577<tel:(734)%20681-0577>
everhamme@limno.com<mailto:everhamme@limno.com>


-------- Original message --------

**Comment by gcutrell** [comment]
Strangely we are getting an error reading in some NDBC buoys but not others. Usually it is all or nothing. Not 100% sure why the error is occurring so I asked Reid if he knows what is going on. 

I have also adopted a previous program where I scrap Limnotech's stations last update and check for a time difference greater than two hours and if this occurs an email is sent out. This program has been very useful for us to catch and fix station errors. The program also checks if the website is available to access. By checking LimnoTech's stations we would also pick up errors with thredds no updating correcting. I can also add a few NDBC stations to verify the script to retrieve NDBC data is working correctly. 

Not sure if we want to check all the stations down the road and play the role of NDBC alerting buoy owners of an issue. 75% of the stations are on NDBC so that may be overkill.
