### ISSUE TITLE
45014 not pushing data to system

### ISSUE THREAD

**Issue by kkoch** [glos/myglos#130]
According to PI, Buoy 45014 (Green Bay - UWM) was released May 31, but portal indicates that it is out of the water. 

I (Kathy) have responded to Becky's email to UWM that they should check and see if they are submitting data to ftp.glos.us.  If we could also check on our side and make sure there isn't something in error on our side.  I also am removing the out of water statement from GN but we need to resolve the "no results" part.

**Comment by kknee** [comment]
there's no data in the obs cache: http://data.glos.us/portal/getObsByPlatform.php?provider=glos&platform=GB17 so seems to be a data flow issue

**Comment by kkoch** [comment]
From PI 

Hi Kathy, sorry for the slow response.  We are having communication issues with 45014 and are sending a crew up on Thursday, weather permitting, to install a new antenna - which hopefully will correct the problem.  

Jeff will keep you posted on the status.

thanks Val



J. Val Klump, JD, PhD 
Senior Director and Dean 
School of Freshwater Sciences
Great Lakes WATER Institute
University of Wisconsin-Milwaukee
414-382-1700

**Comment by kknee** [comment]
@kkoch please close if you see successful data flow

**Comment by kkoch** [comment]
I am closing this for now since even though we are not getting data, it does not appear to be a problem on our end.  Will re-open if they let us know they are sending data and we still can't access it.

**Comment by kkoch** [comment]
All is good. Data flowing to GLOS
