### ISSUE TITLE
Boaters Tool transition

### ISSUE THREAD

**Issue by kkoch** [glos/myglos#132]
Boater's Tool Oceansmap has been created > http://dev.oceansmap.com/boaters/

Changes done to be completed before beta release:
- [x] reorganization of TOC categories per @kkoch comments [RPS]
- [x] rename categories per @kkoch comments [RPS]
- [x] add hamburger button [RPS]
- [x] add feedback form (to hamburger menu) [RPS]
- [x] finalize users guide and quick start guide [LT-kk]  [add marinas document/pdf] 
- [x] create about text [LT] 
- [x] add user guide to hamburger menu [RPS]
- [x] add about text to hamburger menu [RPS] @Bobfrat see below
- [x] add marinas document to hamburger menu [RPS]  Link > https://drive.google.com/open?id=0B7pJZVmOuWvzZE9qaTcwSFZtU0U
- [x] create landing page (prototype being reviewed) [Manning / LT-kk]
- [x] change name in header from "Boaters Tool" to "Boaters' View" [RPS] @Bobfrat 
- [x] move development version to production server [RPS]
- [x] create GeoNetwork records to make Boaters searchable/accessible from Portal [LT-kk]

Issues to be resolved before beta release (new)
> error drawing map layers for models (see below) [RPS] (this appears to have been a moment-in-time issue so am removing this as a check box but keeping it here in case it happens again) <
- [x] change text for metadata (see below) [RPS]

Enhancements to be completed after beta release [NOTE: pulled these off the Beta checklist and made a new ticket --LTIkk]
add login capability [RPS]
add alerts [RPS] 
add alerts access to hamburger menu [RPS]
create webpage with list of marinas [?] [for beta will just be a pdf document]
add marinas webpage to hamburger menu [RPS]
zooming issue for 'find buoy' (see below) [RPS] (note: this is not a show-stopper for beta if RPS cannot isolate the issue so moving it to the after beta section)

Longer Term Enhancements   [NOTE: pulled these off the check list and put in a separate tracker ticket -LTkk]

Next step on alerts is for RPS to get LT  a LOE
Will need review by GLOS staff and possibly run by SeaGrant.  Kristin wants to create videos.

**Comment by kknee** [comment]
@kkoch don't kill me, but i reorganized the above so it would be easier for folks to follow while I'm out.  I think all the task are still there.

Also hamburger button is good to go on dev

**Comment by kkoch** [comment]
Working on user guide but getting an error on dev (thus making difficult to pull screenshots).  Note that I tested this and it displayed the layer for a brief second before removing it and showing the error.

![image](https://user-images.githubusercontent.com/6392982/27399515-066f5d4e-568b-11e7-8b90-0920a3476873.png)

**Comment by kkoch** [comment]
Also noticed that the metadata link from Boaters left nav for existing buoys reads "Data Access" instead of "Metadata Record" as we have on the Portal.

![image](https://user-images.githubusercontent.com/6392982/27399722-bfd93e08-568b-11e7-81d7-73903dddf907.png)

Portal looks like > 
![image](https://user-images.githubusercontent.com/6392982/27399773-e40f8796-568b-11e7-9503-bf3352e3e5b2.png)

**Comment by kkoch** [comment]
Zooming acting poorly when user clicks on the 'find on map' icon versus just hovering.  Behavior is: first time accessed it zooms super giant sized (image 1) and then resizes slightly smaller but zoom is still too high (see 2nd image where all the user sees is water and then needs to zoom out to get a realistic view). Suggest we leave them at whatever resolution they are currently at or at least not zooming so far in.

Image 1:
![image](https://user-images.githubusercontent.com/6392982/27401437-40465418-5691-11e7-9e63-5828d9f093d6.png)

Image 2:
![image](https://user-images.githubusercontent.com/6392982/27401574-b47055be-5691-11e7-83e5-4b845ed55e9b.png)

**Comment by kkoch** [comment]
Up for discussion but I believe for GLBuoys users wanted units to be in English not Metric so since this is a similar audience, do we want to do the same?  Also, then do we want to provide a toggle to allow them to go to metric?

**Comment by kkoch** [comment]
DRAFT versions of users guide and a quick start guide completed: 

User Guide: https://drive.google.com/open?id=0B7pJZVmOuWvzM0p1RnY2SEVjREk
Quick Start: https://drive.google.com/open?id=0B7pJZVmOuWvzTVc0X3FQWWU1UDQ

PDFs > @Bobfrat the below links are ready to put under the hamburger menu (please list them with a (pdf) after the menu item)
Quick Start (pdf): https://drive.google.com/open?id=0B7pJZVmOuWvzQmNYOF8wMEkzWE0
User Guide (pdf): https://drive.google.com/open?id=0B7pJZVmOuWvzYXJJa1p0Ny1MdW8

**Comment by kknee** [comment]
@kkoch for your forecast drawing error comment above, which lake are you looking at?

**Comment by kknee** [comment]
@kkoch for the zoom issue reported above, are you can you replicate the behavior in Image 1, but with your bookmarks bar closed?  I'm wondering if it's a weird screen res issue because things look good to me

**Comment by kkoch** [comment]
1) Erie.

2) Yes it does it with bookmarks closed.  Generally just the first time I click then subsequent clicks more normal (although still too far zoomed but not giant).  This is with FF latest version and on two different PC's.  (Added > just tested with Safari on Mac and does it there as well as well as Chrome on several different PC's)

NOTE: Tad and I tested this today in Chrome.  It is repeatable and appears to be totally related to the very first time the tool is opened in the browser and the very first time the user clicks on the magnifying glass. We tested zooming out more for the lake view and while the dot still jumps larger, it is at least not as 'in your face'.  We think if you dial back on how far it is zooming in when the user clicks this will take the annoyance factor (for me anyway) down as the blue dot still jumps larger but doesn't fill the screen.  I also think the zoom is too high anyway as for some buoys all you see is water so the user then needs to zoom back out on their own.  Example: 45164 shows all water. Two clicks on the minus (-) seems to be the better resolution.

**Comment by kknee** [comment]
@kkoch the text update from 'Data Access' to 'Metadata Record' is complete

**Comment by Bobfrat** [comment]
@kkoch How's this look? It's on the dev site now.
<img width="198" alt="screen shot 2017-06-23 at 2 25 20 pm" src="https://user-images.githubusercontent.com/5702672/27495985-2e5b74bc-5822-11e7-9cc9-2fa148c48958.png">

**Comment by kkoch** [comment]
@Bobfrat looks good.  I have the GLOS staff looking at the pdf content.  Once they approve I'll remove the 'draft' notations and we'll be good to go.  

NOTE: Tad would eventually like to have these be html but we would then need a landing site/place to host so pdf is good enuf for now.

**Comment by tslawecki** [comment]
@Bobfrat - I'm checking in on deployment - do you have the necessary credentials for the Docker host? @

**Comment by Bobfrat** [comment]
@tslawecki Yes, I have all the docker credentials. Do you know what server we are going to deploy on?

**Comment by tslawecki** [comment]
@Bobfrat, it goes on myglos.glos.us AFAIK.

**Comment by Bobfrat** [comment]
@tslawecki I'm not sure I have access to myglos.glos.us. Do you mean portal.glos.us?

Are we going to use the same url for the new version? http://data.glos.us/boaters/

**Comment by tslawecki** [comment]
@Bobfrat, myglos.glos.us is the VM where the docker container that portal.glos.us resolves to is hosted ... I can connect to the console from the vSphere client but *do* *not* have the userID and password. I know that Luke was logging in to do updates in May, perhaps @cheryldmorse has those credentials?

As far as URL goes, I think for now let's go for boaters.glos.us and redirect the old one there.

**Comment by cheryldmorse** [comment]
@Bobfrat @tslawecki I don't have the credentials.

**Comment by tslawecki** [comment]
Can we reach out to Luke?

**Comment by kkoch** [comment]
Just a thought >  I thought @gcutrell had all those figured out

**Comment by Bobfrat** [comment]
I have access to the docker container that runs the data portal at portal.glos.us if that's what we're after. I was just confused about the server names.

**Comment by Bobfrat** [comment]
@tslawecki What's the time frame for deployment? I'm going to be out all of next week except for Thurs.

**Comment by tslawecki** [comment]
Would it be easy for you put it up today as a production test with just IP access?



________________________________

**Comment by Bobfrat** [comment]
yeah I can get it all set up on the server that is hosting the data portal docker image

**Comment by kkoch** [comment]
@Bobfrat  Here is the about text.  Ideally would like this to be an html link 'somewhere' or could be a popup. Also feel free to tweak/put your own spin on the couple of places where RPS is mentioned.

The Boaters' View is a custom view of the Great Lakes Observing System (GLOS) Data Portal<http://portal.glos.us/> designed to provide recreational boaters information on lake and river conditions to help them determine if it is a good boating day. The latest generation of this tool is built on the OceansMap platform which provides users the ability to access near real-time data as well as model forecasts for the Great Lakes region using maps and navigational tools.

 Boaters can view information about marinas and boat launches in an easy-to-use web interface, including ones that are designated 'clean marinas'. Users can also access model forecasts for currents, waves, and wind, and near real-time data from buoys and weather stations around the lakes.

 The first generation of this tool was developed in collaboration with New York Sea Grant and NOAA's Great Lakes Environmental Research Laboratory (GLERL) and piloted in the St. Lawrence River.  OceansMap is a product of RPS.

**Comment by Bobfrat** [comment]
@kkoch How about in the menu dropdown on the upper right?
<img width="198" alt="screen shot 2017-07-13 at 10 40 11 pm" src="https://user-images.githubusercontent.com/5702672/28196105-6803a1c6-681c-11e7-85df-5f0d8da50326.png">


<img width="947" alt="screen shot 2017-07-13 at 10 41 46 pm" src="https://user-images.githubusercontent.com/5702672/28196121-82fb175c-681c-11e7-8244-f53d151295b3.png">

**Comment by kkoch** [comment]
@Bobfrat re: about > Perfect!

**Comment by kkoch** [comment]
@Bobfrat the hamburger menu is still pointing to the draft versions of the user guides.  Can you update?

Quick Start (pdf): https://drive.google.com/open?id=0B7pJZVmOuWvzQmNYOF8wMEkzWE0
User Guide (pdf): https://drive.google.com/open?id=0B7pJZVmOuWvzYXJJa1p0Ny1MdW8

**Comment by Bobfrat** [comment]
@kkoch I just updated the user guides. You may need a hard refresh.

**Comment by kkoch** [comment]
Perfect. Thanks!

**Comment by kkoch** [comment]
@Bobfrat Can you make one small tweak to the landing pop-up?  Please add to the top above the choose your lake text > "Welcome to the newly designed GLOS Data Portal: Boater's View. First time visitors, please see our user guides in the top right menu for assistance."

**Comment by Bobfrat** [comment]
@kkoch Hows this look?

![screen shot 2017-07-21 at 12 33 23 pm](https://user-images.githubusercontent.com/5702672/28472958-d1ae8fec-6e10-11e7-90e2-e8fe4873de4f.png)

**Comment by kkoch** [comment]
Make it so Number One.  (NOTE: we will most likely need to change this to something more generic down the road but this is great for roll-out)

**Comment by Bobfrat** [comment]
Ok deployed to http://boaters.glos.us/

**Comment by kkoch** [comment]
I believe this ticket is pretty much done with the only pending item Manning's links from the glos.us site (a non-dmac task).  I've moved the action items related to after-beta release to a new ticket and will close this once we have the glos.us change made.

**Comment by kkoch** [comment]
Closing this.  Looks like all our Beta release tasks are complete.  After Beta and future enhancements have been moved to new issue trackers.
