### ISSUE TITLE
GLBuoys transition

### ISSUE THREAD

**Issue by kkoch** [glos/myglos#133]
glbuoys.org site developed; includes ability to link directly to a buoy (e.g., glbuoys.org/xxxxx).  

Load testing is in progress with some issues noted.  Also some minor issues with user displays on mobile devices.

**Comment by kkoch** [comment]
Also from our SeaGrant folks > _I have a request for the new data portal (which I'm very glad will now include all of the buoys in the Great Lakes and be mobile-friendly!!): would you please include the links for our IISG pages on our individual buoy pages somewhere? I know we're not the only groups tailoring data presentation for local audiences, and it would be very nice for the individual organization links to be included. Back when Ed Verhamme first approached us about sending data from 45170 to GreatLakesBuoys.org, our main concern was that we didn't want our organizational identity to be lost. The buoys are really important for our program._

45170 is: http://iiseagrant.org/buoy/index.php
45174 is: http://iiseagrant.org/wilmettebuoy/index.php

NOTE: I've already added these as External Links for the Portal and GN Metadata.

**Comment by gcutrell** [comment]
I'll need to add a new key to the metadata files since I imagine others will like to add a link to their own data as well. The question is where to put this link and its styling?

**Comment by tslawecki** [comment]
Buoy information at the bottom, like the (future) uglos links.Could it just be in the text instead?



________________________________

**Comment by gcutrell** [comment]
How does something like this look? [http://limnotechdata.com/ALP/45169.php]

I could just add this information to the current station description so there would be no need to create a new metadata key in all the metadata files.

**Comment by kkoch** [comment]
I like (Kathy)

**Comment by gcutrell** [comment]
Have been added in http://glbuoys.glos.us/45174 and http://glbuoys.glos.us/45170
