### ISSUE TITLE
Portal emails not going anywhere

### ISSUE THREAD

**Issue by kkoch** [glos/myglos#135]
Comments/feedback from Portal do not appear to be working.  Should go to dmac email address but no one is receiving anything.  I looked at the page source and while I'm guessing this is something driven by oceansmap and some javascript, I didn't see any submit 'behind' the buttons nor anything that called up the dmac email so not quite sure what is supposed to be happening behind the curtain so to speak.  So needs to be looked at by the RPS team.

**Comment by kknee** [comment]
we're on it, will let you know what's going on and whether any changes are necessary to GLOS servers.

**Comment by kknee** [comment]
update - emails from the dev instance of oceansmap are working fine and there have been no recent changes to the feedback code.  need to dig a little deeper.

**Comment by kknee** [comment]
this is fixed.
