### ISSUE TITLE
UMN reports GLOS ftp server not letting them write

### ISSUE THREAD

**Issue by kkoch** [glos/myglos#136]
> beginning last night, we have been getting FTP 451 errors when trying to send you these XML files for both buoys (meaning the GLOS server is not allowing us to write the files.....though we can log in).  Do you have any ideas what may have caused us to start getting those errors?  I think it is is on the GLOS server end.

**Comment by gcutrell** [comment]
Which buoys are those?

**Comment by kkoch** [comment]
UMN > 45027 and 45028

**Comment by gcutrell** [comment]
It appears not to be isolated to UMN. The error is sporadic with data coming in intermittently. I spoke to Guan about 45170 and 45176's issues this morning and just alerted to him that not being able to ftp data into glos is more widespread. He said he will look into it today.

**Comment by gcutrell** [comment]
We ran out of disk space. Can you confirm that they havnt seen the error today?

**Comment by kkoch** [comment]
UMW says it is working.  Closing ticket.
