### ISSUE TITLE
GN records not pushing to Production

### ISSUE THREAD

**Issue by kkoch** [glos/myglos#141]
Not seeing changes made in GeoNetwork on production portal.  I do see them on Dev.  

Changes were made to numerous records (about 10) between about 10-11am (it is 1:20pm now).

Last time this happened there was an issue with a metadata record that was preventing the push to production but supposedly Luke had put some code in place to prevent that. Not sure if same thing is happening but see Issue #95 for details.

**Comment by kkoch** [comment]
Appears to be working now.  Do we know if there was an issue or if the cycle has changed such that it took over 5 hours (at least still hadn't rolled over at 3pm yesterday)?

**Comment by kknee** [comment]
the catalog should refresh every hour on the hour, but I wonder if there is some other latency in info flowing from GN to OM?

**Comment by kkoch** [comment]
Closing for now. Will re-open if problem arises again.

**Comment by kkoch** [comment]
Need to revisit this.  Would someone at RPS @cheryldmorse ? please verify that pushes to production are happening?  I made changes in GN this morning between 9-10am.  Those changes are appearing on DEV but not on production so apparently the rollover on the hour is not occurring.

Example below:  
Updated GVSU1 to fix why we were seeing no results for some variables.  Image 1 is from production. Image 2 is from Dev at 1:25pm
![image](https://user-images.githubusercontent.com/6392982/28330741-a24c5f5a-6bbc-11e7-9d03-204852a2a951.png)

![image](https://user-images.githubusercontent.com/6392982/28330766-b600f268-6bbc-11e7-813a-f60b82909688.png)

**Comment by cheryldmorse** [comment]
@Bobfrat - Do you have an info on this?

**Comment by Bobfrat** [comment]
Yes, I think I figured out why it wasn't updating. I pushed an update so I'm hoping we won't see this issue again.
