### ISSUE TITLE
Update Boaters Tool 'Data Access' links to read 'Metadata Record'

### ISSUE THREAD

**Issue by kknee** [glos/myglos#142]
@bobfrat FYI.  Can't assign you yet...

**Comment by Bobfrat** [comment]
Looks like I don't have write access to this repo.

**Comment by kknee** [comment]
@tslawecki can you add @Bobfrat - looks likeI don't have permission to do so.

**Comment by tslawecki** [comment]
Invited bobfrat to asa team and as direct collaborator.


-------- Original message --------

**Comment by kkoch** [comment]
Looks good > and looks like @Bobfrat is all set.  So closing.
