### ISSUE TITLE
Missing NDBC stations from Env Canada

### ISSUE THREAD

**Issue by kknee** [glos/myglos#143]
@Bobfrat @cheryldmorse  we're still missing NDBC stations - there is only one in Lake Ontario right now.

Is there a way to make sure that we're pulling everything (except those that have been specifically excluded because they are also coming in from GLOS)?

**Comment by kkoch** [comment]
These are the buoys I think we should be seeing that we are not. Note that these are all Environment and Climate Change Canada which might be why they are being missed.
Ontario > 45139, 45159, 45135
Erie > 45142, 45132
Lake St. Clair > 45147 (altho' this one is not currently reporting data)
Huron > 45149, 45143, 45137, 45154
Michigan > all is well
Superior > 45136

**Comment by kknee** [comment]
well that explains it, these aren't in the NDBC SOS feed:

http://sdf.ndbc.noaa.gov/sos/server.php?request=GetCapabilities&service=SOS

Can we close this and setup a new ticket for a new harvest of EC buoys?

**Comment by kkoch** [comment]
Let's just keep this same ticket (with slightly changed title but it's still same importance).  I know @gcutrell is pulling them into glbuoys already so it must be readily available.  Greg: are you using a separate feed?

**Comment by gcutrell** [comment]
Yes. We are pulling data straight from the NDBC's website 45-day real-time tables.

**Comment by cheryldmorse** [comment]
@gcutrell Where are you pulling the station location from? Are you hard coding the lat/lon or is there a site you are dynamically pulling that data from too?

**Comment by gcutrell** [comment]
@cheryldmorse We are pulling data from NDBC's 45-day tables based the station ID. 
The only dynamic part of the link is the station ID for all their stations. http://www.ndbc.noaa.gov/data/realtime2/45002.txt

**Comment by gcutrell** [comment]
Sorry. Read your question wrong. We are hard coding the lat/lon although I guess you could pull it from their NDBC pages (ex. http://www.ndbc.noaa.gov/station_page.php?station=45154).

**Comment by cheryldmorse** [comment]
NDBC  Environment Canada stations are now being harvested and the data can be viewed on the portal.
