### ISSUE TITLE
Add bgsusd2 to data portal

### ISSUE THREAD

**Issue by gcutrell** [glos/myglos#144]
Bowling Green deployed a new buoy in Sandusky Bay call "bgsusd2". It is in glos_obs and is reporting specific conductivity, pH, turbidity, BGA RFU, RGA RAW, chlorophyll ug/L, chlorophyll RFU, DO saturation and DO mg/L. All the parameters bgsusd is measuring is measured by their new station.

The buoy is located at 41.469318 N/ -82.750450. Let me know if you need any other specific information. 

@kknee @kkoch

**Comment by kkoch** [comment]
I will create a GN record (assume copy of bgsusd will work - but need to know if there are metadata differences).  I don't see this appearing in my obs json view so need to get that linking and/or the data_url.  

NOTE: I've modified this record a bit - put the habs part over in the habs github tracker (see issue #148) and changed this one to the Data Portal part.

**Comment by kkoch** [comment]
I will add a GN record (assuming copy of bgsusd will work). Let me know if there are changes.  I don't see this in my obs json view so will need the data url and parameter variables.

NOTE: changed title of this to just portal and created a separate ticket in the habs git repository for the habs part.

**Comment by kkoch** [comment]
GN record created.  @gcutrell let me know the url (old buoy's was http://data.glos.us/portal/getObsByPlatform.php?provider=glos&platform=Sandusky+Bay)

**Comment by cheryldmorse** [comment]
@kkoch Here is the obs cache link : http://data.glos.us/portal/getObsByPlatform.php?provider=glos&platform=bgsusd2%20-%20Sandusky%20Bay%202

**Comment by kkoch** [comment]
Thanks GN updated. 

@cheryldmorse I've just been having a conv. with @cgalvarino on why I wasn't seeing this plus the parameters list on the json view I use.  Although I see it is there now.  Is there something Greg should be doing to make these show up automatically?

**Comment by cheryldmorse** [comment]
@kkoch An entry was missing from one of the database tables. I pointed it out to Greg and that step wasn't in the documentation so he's updating the procedure.

**Comment by kkoch** [comment]
I see bgsusd2 on the portal but no results for data.  @gcutrell are we actually getting data for this buoy into the ftp folder?

**Comment by gcutrell** [comment]
I see up-to-date data in their glos_obs table.

**Comment by kkoch** [comment]
I see the problem (I think).  URL above that Cheryl gave me has the ascii codes - will see if a copy/paste directly from the json works better (in case there is an extra % in there or somesuch) > http://data.glos.us/portal/getObsByPlatform.php?provider=glos&platform=bgsusd2+-+Sandusky+Bay+2

So we will see if this fixes.

**Comment by kkoch** [comment]
yep working. closing issue
