### ISSUE TITLE
Boaters additional items

### ISSUE THREAD

**Issue by kkoch** [glos/myglos#151]
Figured the other ticket was getting too large, so here are the new items:

@benjwadams Two critical items needed for push to production are:
a) ability to go from new url boaters.glos.us and see an entire GL view and/or have a splash entry screen that allows the user to select their lake.  Right now it goes to erie and the user somehow would need to know to navigate to the water body selection nav.  We cannot assume everyone will come in from the glos.us landing page so this is essential  (NOTE: This was originally listed under longer term enhancements but the priority is raised.)

b) right now the link when one chooses their lake is a # mark. This does not give them the ability to bookmark their preferred lake.  Example: http://portal.glos.us/boaters_dev/#  - this gives a cookie to the last lake I was looking at but user might want to go to another browser or have all the different lakes bookmarked.

**Comment by Bobfrat** [comment]
@kkoch just seeing this now. So the plan is to release on Tuesday?

**Comment by kkoch** [comment]
@Bobfrat yes (that is what @tslawecki would like - if at all within reason)

**Comment by tslawecki** [comment]
Assuming the landing page glos.us/boaters is available.



________________________________

**Comment by kkoch** [comment]
Kristin thinks we will have the Manning landing page done early next week.

**Comment by Bobfrat** [comment]
@tslawecki thought it was boaters.glos.us? Did you get my email about that? Do you know who's managing the glos.us DNS entries?

**Comment by kkoch** [comment]
@Bobfrat I'll answer for Tad > two different things.  We have the landing page on glos.us which is a wordpress page that users will be able to use to access the tool and that is being supported by a different contractor.  Then we have the one that you and @tslawecki are concerned with which is the boaters.glos.us.  I'll let Tad answer the DNS part (but I think it is himself).

**Comment by tslawecki** [comment]
Thanks @kkoch!

@BobFrat, there is now a DNS A record for boaters.glos.us pointing to 64.9.208.40 - currently reporting unreachable, presumably because the rest of the internet doesn't know about it yet ...

**Comment by Bobfrat** [comment]
It's actually pointing to myGlos portal because we're directing traffic on port 80 on that IP address to the MyGlos portal. Do you want me to make it point to the Boaters View now? Or make it unreachable until Tuesday?

**Comment by tslawecki** [comment]
Let's change it now.



________________________________

**Comment by Bobfrat** [comment]
Ok, unfortunately updating nginx config restarts all the docker containers on that machine so the myGlos portal will go down for a minute. I see from Google Analytics that 3 users are on the site right now so I'll just wait for a better time to update if thats ok?

**Comment by Bobfrat** [comment]
Ok we should be set now.

**Comment by Bobfrat** [comment]
@kkoch we pushed up a solution to these additional items on dev. Can you please have a look and see if they will suffice? Thanks!
http://dev.oceansmap.com/boaters/#

**Comment by kkoch** [comment]
@Bobfrat I think that works well.  @tslawecki what do you think - push to production?

Also landing page on glos.us by Manning is done > http://www.glos.us/boaters-view/  (once we have the dev changes moved to production I will update or have them update with the full urls (e.g., <url>/boaters/#lake-huron).

**Comment by tslawecki** [comment]
Looks good to me, too. Let's push it on out!



________________________________

**Comment by Bobfrat** [comment]
Ok http://boaters.glos.us/ has the same version as dev.oceansmap.com/boaters now

**Comment by kkoch** [comment]
I think the only thing I noticed is that if one clicks 'cancel' from the pop-up it does nothing.  Should we direct them somewhere if they've decided they don't want to choose a lake?  Alternately I would say don't offer them a cancel.

**Comment by tslawecki** [comment]
Good catch, Kathy ... maybe it's "back" instead of "cancel"?



________________________________

**Comment by Bobfrat** [comment]
Removing the cancel is definitely the easiest. Does that work for you guys?
