### ISSUE TITLE
GLCFS 2D Nowcast archives not available 2016--2017

### ISSUE THREAD

**Issue by kkoch** [glos/myglos#152]
Kyle Wilcox <kyle@axiomdatascience.com> noticed that the 2D Nowcast archives for the GLCFS model have either disappeared or haven't been generated since the beginning of 2017. In 2016 they were generated every 50 days.

2017: http://tds.glos.us/thredds/catalog/glos/glcfs/archive2017/erie/ncfmrc-2d/files/catalog.html
2016: http://tds.glos.us/thredds/catalog/glos/glcfs/archive2016/erie/ncfmrc-2d/files/catalog.html

Any ideas if they will come back? It was a very convenient way to gather the data efficiently every 50 days.

**Comment by gcutrell** [comment]
The 2017 archive was prematurely made earlier this year. It was never deleted because it would eventually need to be created at the end of 2017 and it was not messing up anything. The current year's data is in http://tds.glos.us/thredds/glcfs/nowcast/glcfs_nowcast_current.html.

**Comment by gcutrell** [comment]
@kkoch  Where you able to point Kyle to the correct directory for 2017?
