### ISSUE TITLE
Google Tag Manager issues with Boaters & GLBuoys

### ISSUE THREAD

**Issue by kkoch** [glos/myglos#153]
Issue reported from Devra: 

Hi, Chris--

 It looks like we're having some issues with the GTM implementation on boaters.glos.us. I'm seeing 0 stats appear on the shared GA glos.us property (UA-16070728-1) for this domain in the past 7 days, and it's been live for 2-3 of them with testers on it.

 I took a look in Tag Assistant and am seeing some issues:

 1) This doesn't seem to be using standard GTM implementation, with the main script in <head> and the noscript in body. I notice you have a div (include?) set up for it, which GTM doesn't like at all. It's turning up with errors.

 Can you try using GTM's native code for implementation?

 I.e., paste this code as high in the <head> of the page as possible:

 

<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-PH3LF3X');</script>

Paste this code immediately after the opening <body> tag:

<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-PH3LF3X"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>

2) It looks like you have additional GA tracking code in there for UA-16070728-1, and it's not happy with that either. It detects that you're tracking this property twice and that it's also not in the <head> area. 

 Is this just left over from initial testing? Is there some reason GA tracking snippet is being used here? I think it will help smooth things out to just use the above GTM code and both the glos.us and glos.ca analytics properties are being tracked from there.

 Let me know if there's some conflict or issue here--

 Thanks,
 Devra

**Comment by kkoch** [comment]
Update >
1) First off, good news and an update: I was incorrect and boaters.glos.us *is* recording activity. My mistake; I was looking at the dates for last week (ending Sunday) and not this week. It's picked up 140 views/14 unique pageviews from Monday-Wed. of this week. So: whew!

 2) Yes, these are errors/warnings from Tag Assistant (which is a GTM console for Chrome). Detailed reports attached.

 3) On the GA side: I don't see evidence of traffic being doubled on the GA side so far for the Portal (it's helpful to have such detailed User-ID sessions recorded in the User Explorer).

 The bugginess I have been experiencing in GA views has been: 
 
a) View filters being ignored on certain product views. So a view that has filters to include only traffic to a specific subdomain and/or directory would sometimes include traffic to multiple products. This was last an issue for the test Maumee views and Portal User ID view, both of which are currently working normally.

b) I'm personally unable to see real-time traffic in specific views that are otherwise getting captured in the inclusive all-glos.us-and-subdomains view. This includes not capturing myself on new views implemented since User-ID was activated in May. Prior to that, I had no issues seeing real time traffic. This isn't crucial, but signs of something going awry and malfunctioning.

The tag errors/warnings may or may not be the culprit, but it seems like a logical first place to start and something we should get resolved.

 Thanks again,
 Devra

**Comment by kkoch** [comment]
@Christopher.Adams@rpsgroup.com
@Bobfrat

**Comment by kkoch** [comment]
@gitchrisadams @Bobfrat > Do we have a status on this? High priority!

**Comment by everhamme** [comment]
Note this needs to cover the glbuoys.glos.us website too.

Greg c is tracking but needs help



Ed Verhamme
Project Engineer
LimnoTech www.limno.com
Ph: (734) 332-1200<tel:(734)%20332-1200>
Direct/Cell:  (734) 681-0577<tel:(734)%20681-0577>
everhamme@limno.com<mailto:everhamme@limno.com>


-------- Original message --------

**Comment by Bobfrat** [comment]
We've been working on this with Devra. There is a long email correspondence. I think we're close

**Comment by kkoch** [comment]
Done Life is good
