### ISSUE TITLE
Remove Blue Notification box and update login page

### ISSUE THREAD

**Issue by kkoch** [glos/myglos#154]
1) Remove the blue notification to users about passwords >

![image](https://user-images.githubusercontent.com/6392982/28467351-99a2c8d8-6dfd-11e7-8317-b1d83467ff6e.png)

2) On MyGLOS Login page, change "Forgot Password" button to "Change Password"

3) Update the login screen to include the following text:

If you haven't logged in recently your account password may not work. If this is the case, or if you've forgotten your password, please click "Change Password" to reset your user account's password.

**Comment by Bobfrat** [comment]
@kkoch 
I made those updates on dev: http://dev.oceansmap.com/myglos/
How's it look? Might need to hard refresh to see the updates

**Comment by kkoch** [comment]
How hard would it be to put that text on the bottom (underneath the buttons)? And a slightly smaller font.

**Comment by Bobfrat** [comment]
@kkoch this will be a true test of my abilities but i will give it a shot!

**Comment by Bobfrat** [comment]
@kkoch How's this look?
<img width="1438" alt="screen shot 2017-07-25 at 3 32 56 pm" src="https://user-images.githubusercontent.com/5702672/28590005-954a6aee-714e-11e7-9b57-ace406f6e391.png">

**Comment by kkoch** [comment]
Yep. I like.

**Comment by Bobfrat** [comment]
Ok its on http://portal.glos.us/ now

**Comment by kkoch** [comment]
@Bobfrat I'm having an issue where I go to the myglos login page and if I decide I really didn't want to login > 'map' button is grayed out (inspecting the element says it is disabled). 'Catalog' button is not grayed out but doesn't do anything when I click on it.  I can honestly say I haven't tried that before so I don't know if this is new bad behavior or old bad behavior.  I've tried in both FF and IE. Can you take a look-see?

**Comment by Bobfrat** [comment]
I just rolled back to an older version and the map button is greyed out but catalog works so it appears this is a new issue. I'll have a look.

**Comment by Bobfrat** [comment]
@kkoch another option might be to remove the catalog and map buttons up top and add a cancel button with the login and change password buttons that brings you back to the catalog. Let me know what you think.

**Comment by kkoch** [comment]
I could live with that if you can't fix.

**Comment by Bobfrat** [comment]
Ok login fix on http://dev.oceansmap.com/myglos/ Let me know if you approve and I'll move it over to production

**Comment by kkoch** [comment]
Looks good. Thanks! Make the move when you have a chance.

**Comment by Bobfrat** [comment]
@kkoch its on portal.glos.us now too
