### ISSUE TITLE
Major parameters missing - SRAD1 and MWDIR

### ISSUE THREAD

**Issue by everhamme** [glos/myglos#155]
ITs been brought to our attention by Guy Meadows that SRAD1 and MWDIR and missing from all GLOS data products (glbuoys and portal).  These two parameters are major parameters that don't appear to be in the GLOS catalog or database.

**Comment by kkoch** [comment]
NOTE: Per conv. with Ed these are not rush, but should be added to OBS and thus portal (and glbuoys).  @cheryldmorse if you can at least provide LOE that would be great.

**Comment by everhamme** [comment]
Just edited to add ADCP data to this list.

**Comment by kkoch** [comment]
Consolidated this into issue #146
