### ISSUE TITLE
Add 45166 to Portal (and GLBuoys)

### ISSUE THREAD

**Issue by kkoch** [glos/myglos#159]
Here is the data cache for 45166. 
http://data.glos.us/portal/getObsByPlatform.php?provider=glos&platform=Lake+Champlain+%3F+Inland+Sea

The contact is Tom Manley for 45166 (tmanley@middlebury.edu). He knows about glbuoys but probably not about GLOS and why you would like metadata. 

I’ve created a webpage for 45166 but tds has not yet created a directory for 45166. I thought this was done automatically but maybe RPS has been creating it manually?

**Comment by kkoch** [comment]
I have contacted the user who brought this up (Richard Furbush at Middlebury) and Tom Manley asking for the GN metadata form to be filled out.   In the interim I will create at least a bare-bones GN record.  If @cheryldmorse would work with @gcutrell to finish the process.  I also would like the process of adding a new buoy to be documented so I can add to our wiki.

**Comment by kkoch** [comment]
GN record > http://data.glos.us/metadata/srv/eng/main.home?uuid=ef5af3b2-aea9-4125-a85f-b08f521b771b

**Comment by kkoch** [comment]
We are all set on portal.  Gads I love it when the magic works.  Still pending 'real' metadata from owner (above GN record is based on me going to their website and NDBC, but good enough for now).

![image](https://user-images.githubusercontent.com/6392982/28839883-0fe44800-76c3-11e7-94c3-dfaaa9619ed9.png)

**Comment by gcutrell** [comment]
@cheryldmorse Can y'all add 45166 to the list of the stations that are placed in thredds->buoys? We need data to be in there to populate the glbuoys website.

**Comment by cheryldmorse** [comment]
@gcutrell  This is done. 
FYI - To add a new station to thredds just copy the uglos_tables.dat file to the following directory on process1: '/usr/local/glos/buoy_harvester/glos_harvest'

**Comment by kkoch** [comment]
@gcutrell I have updated the GN metadata that Tom Manley provided.  Looks like we are good from the Portal standpoint so I'm closing this part of the ticket.  I see a direct link to http://glbuoys.glos.us/45166 but not on the main page so I'll leave that ticket open.
