### ISSUE TITLE
Alerts in Portal do not appear to be working

### ISSUE THREAD

**Issue by kkoch** [glos/myglos#162]
Behavior:
User adds model to portal (e.g., GLCFS, Huron, Currents).
User creates virtual buoy and has option to manage alerts (if not logged in - prompts for login so that part works)
![image](https://user-images.githubusercontent.com/6392982/29717834-9e8becca-897e-11e7-9704-d7815e2eb4cd.png)

User clicks on manage alerts and gets the following note to apply changes but no changes or options appear (NOTE: This same behavior occurs on Dev).
![image](https://user-images.githubusercontent.com/6392982/29717869-c797c148-897e-11e7-8f01-a7c9e75cffe2.png)

We need to either fix the above issue or remove "Manage Alerts" option until fixed.

Side note: we also need a tutorial on how to do this once fixed.

**Comment by kkoch** [comment]
Note that Becky has also found that she sometimes does not see manage alerts for a 'real' buoy.  I just tested and saw alert options for one (users may not know that they need to add to map but that's a documentation issue).

![image](https://user-images.githubusercontent.com/6392982/29718546-1f89816e-8981-11e7-981c-803bbbc64905.png)

@Bobfrat  >  I did notice that if you add to map from within the popup it does not show alerts.  If you add to map from the catalog bar it does:

Screenshot 1: I clicked on add to map after I already showed the pop-up on the map
![image](https://user-images.githubusercontent.com/6392982/29718796-e55f1732-8981-11e7-8a8f-55ea48c570fe.png)

Screenshot 2: I added to map from the catalog bar
![image](https://user-images.githubusercontent.com/6392982/29718872-2081bb3a-8982-11e7-929d-ec64d34e4a23.png)

**Comment by kkoch** [comment]
@Bobfrat : I just detailed what I believe the issues are for Becky (although I could be wrong and there might be some randomness kicking in for her that I'm not seeing) >

1) click on a blue buoy icon without ‘adding to map’.  There is no alert option whether you are logged in or not – but I believe this is designed that way since you haven’t added it to map yet.  Now, that might not be what we ‘want’ for a behavior, but I think at least at this point the behavior isn’t broken.

2) click on blue buoy icon and then ‘add to map’ from the parameters pop-up box such that icon changes from blue to black.
	Alerts option is not given – this is broken.  To clarify: you do not see an alerts option UNLESS at this point you close (‘x’) the pop-up and then bring it back up from the lower left collection screen or if you just click on the icon again.  So I believe this is a refresh issue that RPS needs to look at and fix. Expected behavior would be that the alerts option would show up the minute you add it to the map (basically that the box should refresh the same as if I click on the black icon again).

3) click on little plus sign in the nav box to add to map from there (instead of from the map pop-up) – and alerts option always shows

4) add a virtual buoy – alerts definitely don’t work from there and again if they are not supposed to then we need to suppress this option from showing up when the user adds a virtual buoy.

**Comment by Bobfrat** [comment]
@kkoch, So the alerts themselves are working ok, it's just the button that's not behaving correctly? 

I've got a fix on dev and if that's working as you'd like I'll move it over. http://dev.oceansmap.com/myglos/

**Comment by kkoch** [comment]
Dev fix appears to work correctly.  May be moved to production.

**Comment by Bobfrat** [comment]
ok all set!
