### ISSUE TITLE
Add buoy 45179

### ISSUE THREAD

**Issue by kkoch** [glos/myglos#164]
Per J. Lenters new glos-funded buoy to be added to Portal and GLBuoys at Stannard Rock (45179).  

@gcutrell has added necessary obs database link 
@kkoch has created a preliminary metadata record into GN

Pending:  
- data to start flowing (J. Lenters says QAQC wrapping up and they hope to start data this afternoon, 9/5)
- we will need parameters
- John is filling out a metadata form and will send a photo of the buoy for the Portal

**Comment by kkoch** [comment]
Received metadata form and buoy pic from John.  Pending QA/QC data.

**Comment by kkoch** [comment]
@gcutrell Parameters for Obs

Variable | Variable name | XML Parameter tag | Format / units
Timestamp | Date/Time |   | m/d/y
Barometric pressure | Rel. BP | baro1 | inHg
Air temperature | AirTemp | atmp1 | C
Wind direction | Magnetic WindDir | wdir1 | Degree
Wind speed | WindSp | wspd1 | m/s
Water Temperature |   | wtmp1 | C
Wave height | Hs | wvhgt | m
Wave period | Ts | dompd | sec

**Comment by gcutrell** [comment]
@kkoch John is having a couple issues with the reporting timestamp but the data is at http://data.glos.us/portal/getObsByPlatform.php?provider=glos&platform=Stannard+Rock+Buoy

**Comment by kkoch** [comment]
Data is appearing nicely in Portal and GLBuoys. Done!

![image](https://user-images.githubusercontent.com/6392982/30288368-7be8ccf8-96f6-11e7-807d-84195e49d054.png)
