### ISSUE TITLE
ESF2 issue with data

### ISSUE THREAD

**Issue by kkoch** [glos/myglos#165]
Left a message with Mike Satchwell at ESF regarding the data we are getting for the ESF2 buoy.  Mostly around several 'no results' and that wind gust reporting as -1939.96 knots which I would assume should be the in 2-5 knot range based on other stations in the area (including the NWS GL Portal).

His reponse: 
"ESF2 is having issues, or rather, iChart is having issues with ESF2.  I fixed the problems yesterday.  The only data ESF2 is now sending to GLOS are Water temp @ 1m, water temp @5m, wind gust and wind speed. This was all fine until 11:30 last night when the batteries on the buoy failed. This will not be fixed until early next week, unless the sun decides to come out again!"

I have checked values coming in to obs and glbuoys and looks about the same today. Checking with @gcutrell to see if we want to suppress the wind gust data.

**Comment by gcutrell** [comment]
Suppressing individual measurements is possible but I would lean against going down this road. People will see it isn't working. Quartod should pick this up in the future. We could always put up a alert telling people when it is planning to be fixed.

**Comment by gcutrell** [comment]
Added an alert on the buoy page stating it should be fixed next week.

**Comment by kkoch** [comment]
done and buoy out of water this Friday
