### ISSUE TITLE
Portal swapiness issue (related to portal down (or just very slow))

### ISSUE THREAD

**Issue by kkoch** [glos/myglos#167]
Ed reported that the portal was down this morning although it appeared that it would eventually load - but very very slow.

Greg noted that after closer inspection into process1 it appears storage.glos.us is 99% full and /dev/mapper/centos-root is 96% full. 

@gcutrell please provide status on resolution

**Comment by tslawecki** [comment]
I restarted the portal VM, seems to be much better now. Also freed up about 200 GB on the NFS device, so now *only* 97% full.

**Comment by tslawecki** [comment]
@bnfish noted: I looked prior to the restart.  It looked as if the Gunicorn process used to run the application web servers were using a lot of swap space, which can cause slow access speeds.  Bob and I checked the kernel "swappiness" setting in /sys/proc/vm/swappiness, and it's at 30, (from 0 to 100 scale, 0 does not use swap unless memory is completely full, 100 always prefers swap).  It may be desirable to set it lower, say around 10 or so.  I did not see a lot of swap paging, but it may be worthwhile looking.

**Comment by Bobfrat** [comment]
@tslawecki, it was @benjwadams that reported the swappiness. I think you may need to add him as a collaborator to see him in the autocomplete fields.

**Comment by kknee** [comment]
@Bobfrat @benjwadams -do you still recommend that we address the swappiness issue?

**Comment by benjwadams** [comment]
NB: this might not be swap, I was simply speculating on one possibility.  I did reduce the swappiness value permanently.  See if it works any better in the coming weeks.  

@tslawecki: Has munin returned any useful metrics that might help diagnose this?  The box also has the `sar` utility, for which `sar -b` can be used to diagnose high I/O wait times.

**Comment by benjwadams** [comment]
Should probably close for now.  If portal has poor performance characteristics again, a new issue can be created.
