### ISSUE TITLE
Suppress ndbc feed for 45179

### ISSUE THREAD

**Issue by kkoch** [glos/myglos#168]
45179 snuck in there and is showing both an NDBC feed and GLOS (GN) feed.  @Bobfrat please suppress the NDBC for this one.

![image](https://user-images.githubusercontent.com/6392982/31395763-85f72bf2-adaf-11e7-97d1-44e1a12cb162.png)

**Comment by kknee** [comment]
complete on dev

**Comment by Bobfrat** [comment]
Fixed on production too
