### ISSUE TITLE
thredds.glos.us out of space

### ISSUE THREAD

**Issue by gcutrell** [glos/myglos#172]
@tslawecki  thredds.glos.us will probably hit 100% capacity this week. Wasn't sure if there was a plan to increase storage or remove log files? I see something was done at the beginning of October to drop the usage down almost 20%.

**Comment by cheryldmorse** [comment]
@gcutrell - I just deleted the thredds log files and we are back down to 95% full

**Comment by gcutrell** [comment]
@cheryldmorse - Could you point me to the directory that the log files are located? If I see the issue again I can go ahead and quickly temporarily fix it.

**Comment by tslawecki** [comment]
I recovered about 30 GB at /var/lib/tomcat/applications/thredds-4.6.6/content/thredds/logs

**Comment by kknee** [comment]
This has been happening more frequently.  I think we need a longer term solution than manual clean up of logs.  We can setup log rotate as a start, for both threads and nginx.

**Comment by tslawecki** [comment]
There were hourly log files here dating back to 2016 for the thredds servlet ... maybe we have too high a logging level?



________________________________

**Comment by cheryldmorse** [comment]
The nginx logs are also getting large. The 'host_access.log' in /usr/local/nginx/logs is over 12 GB
