### ISSUE TITLE
Odd new categories appearing on catalog

### ISSUE THREAD

**Issue by kkoch** [glos/myglos#173]
Some categories have appeared on catalog that were not generated (requested) from my direction and thus have no content >

Can someone let me know what these are and where they came from? They are on Dev too.

![image](https://user-images.githubusercontent.com/6392982/32345606-157be400-bfe1-11e7-9ca7-06989deaa476.png)

**Comment by Bobfrat** [comment]
Looks like they crept in from another portal. I can remove.
