### ISSUE TITLE
Lake Erie has disappeared

### ISSUE THREAD

**Issue by kkoch** [glos/myglos#174]
MTRI Lake Erie Remote sensing is not appearing in portal

![image](https://user-images.githubusercontent.com/6392982/32345652-4493cfaa-bfe1-11e7-8e05-b4dd645b448a.png)

Colin has verified that things look good on his end (he's seeing data).

**Comment by Bobfrat** [comment]
Looks like kd490_erie is missing from the [GetCapabilities](http://spatial.mtri.org/cgi-bin/mapserv?REQUEST=GetCapabilities&SERVICE=WMS&map=watersensing_map&version=1.1.1) XML causing the layer to fail in our data-catalog.

**Comment by ColinNBrooks** [comment]
Is this something we should fix on the MTRI end? I don't see any Lake Erie Kd490 data on our own portal right now at www.greatlakesremotesensing.org

**Comment by Bobfrat** [comment]
@ColinNBrooks is that a question for me? Yes, I believe that is on the MTRI end. The kd490_erie layer used to be in that GetCapabilities response until recently. Thanks!

**Comment by ColinNBrooks** [comment]
We've removed the kd490_erie and PZD Erie layers from our WMS stream until we're more confident of the data. Can the Getcapabilities statement be edited so that the GLOS portal doesn't try to get these? Then Lake Erie should show up again, right?

**Comment by kknee** [comment]
@Bobfrat can you fix this on the data catalog end, rather than having MTRI mess with the GetCaps?

**Comment by Bobfrat** [comment]
yes, just let me know when its back

**Comment by kknee** [comment]
ok, lets go that route, thanks!

**Comment by ColinNBrooks** [comment]
Thanks. I wasn't sure what needed to be done. We hope to restore the data in 2018 when we're more confident about these two Lake Erie data layers.

**Comment by Bobfrat** [comment]
Lake Erie is back now.

**Comment by kknee** [comment]
We removed the kd490_erie and PZD Erie layers from the OceansMap catalog to match the MTRI GetCaps.  If these come back online we'll need to add them back to OceansMap.
