### ISSUE TITLE
Battery replacement NFS & VM migration

### ISSUE THREAD

**Issue by kkoch** [glos/myglos#175]
We are scheduling a battery replacement for the NFS server and a VM migration for next Thursday afternoon (11/30). 
 
Kristin - do you think there should be an announcement at glos.us? Estimated outage is 4 hours (1 PM - 5 PM).
 
Team - The NFS server will be down for a CMOS battery (OR possibly motherboard) replacement, and we will wrap up the migration of VMs from dad.glos.us to daughter.glos.us. This includes portal.glos.us as well as several backend VMs (db2, web2, web3, web4, and mon).

@tslawecki > please update with status when item is complete

**Comment by kkoch** [comment]
@kknee put a warning message on portal.glos.us so users will have a heads up.  Won’t do much good while the site is down, do we want to think about a redirect to a simple landing page for those four hours?

@tslawecki agrees redirect is a good idea (who will be doing that?)

**Comment by kkoch** [comment]
Message is live on Portal.  " The GLOS Data Portal will be down for scheduled maintenance on 30 Nov from 12 pm to 6 pm."

(Suggest that we tweak it to say E.T. or EST.)

**Comment by tslawecki** [comment]
I was told by IT that we don't actually know the time window, so let's (1) change the message to "The GLOS Data Portal will be intermittently unavailable on Thursday, November 30 due to maintenance." (@kknee?)  and (2) I will set up a temporary landing page.

I will coordinate timing of DNS changes with IT.

**Comment by gitchrisadams** [comment]
Updated message:
![image](https://user-images.githubusercontent.com/9978238/33325512-7af03d60-d420-11e7-8592-7227f96296b8.png)

**Comment by tslawecki** [comment]
@gitchrisadams, git outtahere with your too-rapid responses!

:)
