### ISSUE TITLE
TDS PQT Internal Server Error

### ISSUE THREAD

**Issue by gcutrell** [glos/myglos#177]
@kknee @tslawecki Kelly, we first received notification from Greg Lang 12/4 3:30 PM that he was receiving an error when trying to obtain Lake Erie Nowcast data. It also happened overnight and I believe it occurred around 1 ET today. A thredds restart temporarily fixes the issue but it continues to occur. I've attach the tomcat error that is associated with the data request. I've also confirmed that the error does not occur when a new GLCFS file is downloaded to the storage because the error occurred at a time when new files were not being retrieved. This is only occurring with Lake Erie for some reason. Could someone at RPS look into this? 
![glcfs](https://user-images.githubusercontent.com/23699668/33679644-4d34ac58-da8d-11e7-8ae1-cd98e1c38dbe.PNG)

**Comment by kknee** [comment]
@gcutrell , @cheryldmorse is taking a look.  The error is not occurring right now and we haven’t been able to figure out why it  was in the log. It appears that the NC file was corrupt, but I think we need to wait until it happens again to dig into what is happening.

**Comment by gcutrell** [comment]
@kknee, @cheryldmorse The error is occurring now and can be viewed at http://data.glos.us/glcfs/glcfsps.glos?lake=erie&i=-82.90866&j=41.53578&v=air_u,air_v&in=1&latest=1&h=6&order=asc&pv=1&gi=1&doy=1&tzf=0&f=csv. Could you look into it this morning? I'll tell Greg L. that we are not going to restart thredds yet so you can dig more into it.

**Comment by cheryldmorse** [comment]
@gcutrell I'm looking into it now

**Comment by cheryldmorse** [comment]
@gcutrell I found incorrect permissions on the erie folder in the tds cache. I updated the permissions and the request is now working

**Comment by kknee** [comment]
@cheryldmorse is a TDS update the solution to this issue as well?

**Comment by cheryldmorse** [comment]
@kknee - No this was an issue with owner/permissions. I think someone probably started TDS as root instead of using the service. This issue is fixed and I think it can be closed
