### ISSUE TITLE
Improve Portal Load Time

### ISSUE THREAD

**Issue by kkoch** [glos/myglos#179]
It was noted in the GLOS Google Analytics meeting the following:
•	The average monthly load time has been fluctuating. It went up to 7 seconds in November.  What is the reason for this fluctuation? 
•	Organic search went up which is good. It would be nice to know why. 

https://docs.google.com/spreadsheets/d/1Q6Gs-J6yaZFHOaRBYezbahteXP8K23gqiJH9bBx9Nb0/edit#gid=2041614704

And also noted that GLBuoys load time has been improved by implementing some recommended strategies from Google (mainly smaller image sizes and such).

Would like to see if there is anything that can be done for the Portal to also accomplish improvements (and/or at least know why we are seeing the fluctuations in the numbers).  Devra did note that possibly the numbers might not be representative of reality because the page can continue to be loading in the background while users are able to use the tool.  

Is it possible for someone on the RPS team to look at the numbers, provide an answer (or possible answers) to the "why" and then some discussion on what might need to be done to improve it?

**Comment by devrap** [comment]
@kkoch  and @kknee, I just wanted to follow up with a bit of an update here and say that:

1)  this continues to fluctuate and in Dec. the page load time went down to 3.54 seconds. 

2) For this and pretty much everything, it's helpful to look at Google's PageSpeed Insights tool for recommendations. The Portal's is at https://developers.google.com/speed/pagespeed/insights/?utm_source=analytics&url=http%3A%2F%2Fportal.glos.us&tab=desktop 

Of interest is the "Eliminate render-blocking JS and CSS in above-the-fold content" item and the suggestion of reducing image sizes by 43%. I don't recommend leveraging browser caching, as this should be loading fresh and not cached data.

**Comment by kknee** [comment]
@tslawecki let me know if we should spend time on this

**Comment by kkoch** [comment]
Per DMAC, need to keep this as a 'keep an eye' on load time with no action at this point in time.  HOWEVER, @kknee we do need to do what is necessary to have the click on the map view button as a trackable event.

**Comment by Bobfrat** [comment]
@kkoch I was able to speed up the load time by updating the URL that we fetch notifications from on S3. @gitchrisadams is working on tracking the map/catalog button click event.

**Comment by gitchrisadams** [comment]
Created top level category of "Site Navigation", action of either "Map" or "Catalog" "Button Clicked".
For the label it is "Map Button" or "Catalog Button". How do these names sound?
![image](https://user-images.githubusercontent.com/9978238/36213827-b7ab212e-1175-11e8-8d32-f647baa7e00b.png)
![image](https://user-images.githubusercontent.com/9978238/36213848-c88fde58-1175-11e8-9a95-610c0dc861f2.png)
![image](https://user-images.githubusercontent.com/9978238/36213793-a7911c44-1175-11e8-97bb-1c1ffbe8877f.png)

**Comment by kkoch** [comment]
@devrap Does that seem clear to you?

**Comment by devrap** [comment]
Yep, @kkoch and @gitchrisadams  - this should work well. The current multi-dimensional events report filters by page (which is the same on this product) then by category > label > action, so map and catalog interactivity should show up well here. Thanks.

**Comment by kkoch** [comment]
Closing for now.  Will re-open if load time does not really appear to be improving.
