### ISSUE TITLE
Point Query Tool/GLCFS/Obs (ATW20 issue)

### ISSUE THREAD

**Issue by kkoch** [glos/myglos#181]
Jeff Houghton contacted us with the following:
"A quick question regarding the GLOS Point Query Tool.  I’m comparing wave data from our Milwaukee 20m buoy with GLCFS Nowcast wave data, the data in my query seems to be shifted early 6 days 6 hours.  Is this because its reporting a forecast or for some other reason?  If it’s a forecast I can say it’s very impressive how accurate it is to our measured wave heights."

**Comment by kkoch** [comment]
Follow up (in case this was related to our other GLCFS issues) 
Jeff: "Looks like my issue persists.  I’ve run a Nowcast Query at -87.8243, 43.0946 degrees for Significant Wave Height (m) and the data appears to be shifted early by 6.25 days.  I’ve come across other issues as well.  Using this link (http://data.glos.us//obs//station//15-402.html#) for our ATW20m buoy the AirTemp data appears to be shifted from my records by 4.5 hours.  Furthermore, the Nowcast data is shifted from the GLOS archive by +/-5 hours.  Not sure how our reported data has shifted time in your database?"

**Comment by kkoch** [comment]
From @gcutrell > Thanks Jeff for the additional details. Hopefully we can figure out something soon. For the Point Query Tool were you using the date range or “latest” option? We’ve been working on fixing the Nowcast data archive  since we reached a server disk capacity the other day. 

As for your ATW20m buoy data does it appear to be all years? 4.5 years is a strange offset. I can check our database and possibly eliminate that issue but could you provide just a few records of significant wave height from your buoy that I can match to our database? We will be releasing a new data tool similar to the “observations explorer” this spring so you can download and view archived data that way. I believe maintenance of the observations explorer is low right now. 

 Much of the GLOS system will be down for the rest of the afternoon for scheduled maintenance so we won’t be able to troubleshoot till tomorrow.

**Comment by kkoch** [comment]
Jeff > No problem.  For the Point Query Tool I was using the date range option.  The ATW20m buoy data is off by 4.5 hours not years, which will make more sense I think.  Attached is my comparison of measured wave data and Nowcast wave height with the 6.5 hour correction.  Extremely impressed these data match up as well as they do.  Glad to hear archived data tool is coming online, still not sure how to find that on the data portal site…

**Comment by gcutrell** [comment]
Issue was not GLOS's. Jeff did not realizing the timezone of the glos obs and nowcast data.

**Comment by kkoch** [comment]
just clarifying > GMT vs local time zone thus the 6 hour gap
