### ISSUE TITLE
Boaters: ndbc Canadian buoys

### ISSUE THREAD

**Issue by kkoch** [glos/myglos#186]
Noticed that the ndbc buoys in boaters differs from Portal.  See issue #143 which is that the ndbc feed was not pulling in the canadian buoys so I'm guessing the fix would be the same.  

Buoys missing in Lake Ontario in Boaters are : 45159, 45139, 45135 

I did not check the other lakes.

This also begs the question as to how do we ensure that changes made to the main Portal are also reflected in the Boater's View?

**Comment by Bobfrat** [comment]
Right now the entries in the boaters portal are static and separate from the collection in the main portal because they are split up by lake. I can take the main portal NDBC buoys and filter them by location though.

**Comment by kkoch** [comment]
@Bobfrat yes please

**Comment by kknee** [comment]
This is all set on dev, should we push the change to production?

**Comment by kkoch** [comment]
Yes please push to production

**Comment by Bobfrat** [comment]
Should be set, please let me know if any other buoys seem to be missing from either portal
