### ISSUE TITLE
HECWFS not working in portal

### ISSUE THREAD

**Issue by kkoch** [glos/myglos#187]
I am getting errors in portal when I go to hecwfs links:

http://portal.glos.us/?map=MzkyNTljMjYtNjIxMS00ZThlLTk4YzMtMTczOTdkMTYxNmIyOmhlY3dmcyAyMDE4&
name=hecwfs+2018

![image](https://user-images.githubusercontent.com/6392982/34998680-b9df33e2-faad-11e7-9463-529e613752b1.png)

**Comment by kknee** [comment]
hmm, no data since 12/31 on either the GLOS or EDS TDS, but forecast images do appear to be available on the GLERL site.  Will have the EDS team investigate and report back.

**Comment by kknee** [comment]
From the EDS team:

There has not been any new files posted at the source since 12/31/2017.

Here is the endpoint we hit to collect the data: http://tds.glos.us/thredds/catalog/HECWFS-Forecast-Files/catalog.html .

The file we used to grab was the %YYYYDDD%00.nc file.

**Comment by tslawecki** [comment]
@gcutrell , please take a look too. http://data/glos.us/status shows HECWFS nowcasts and forecasts happening successfully, maybe they're being put in a wrong place because of the calendar year turnover?

![image](https://user-images.githubusercontent.com/5224254/35009758-8db3eb02-face-11e7-9aa9-6a96b342e043.png)

**Comment by kknee** [comment]
@cheryldmorse any insight here about whether the new year could have caused a snag in data collection for HECWFS?

**Comment by cheryldmorse** [comment]
@kknee - Files are showing in TDS now: http://tds.glos.us/thredds/catalog/HECWFS-Forecast-Files/catalog.html
I missed the TDS catalog entry for individual forecast files when I updated the HECWFS catalog for the new year

**Comment by kknee** [comment]
thanks @cheryldmorse, let's wait for EDS to catch up with their harvest and then we can confirm the fix in the portal and close this out.

**Comment by kknee** [comment]
Everything is in order on EDS staging.  Turning acquisition back on for production this afternoon.

**Comment by kkoch** [comment]
Looks like things are working fine.  I created a permalink http://portal.glos.us/?map=MzkyNTljMjYtNjIxMS00ZThlLTk4YzMtMTczOTdkMTYxNmIyOkhFQ1dGUw%253D%253D&name=HECWFS and notified Kristin regarding the HECWFS tile on glos.us
