### ISSUE TITLE
Point Query Tool issue

### ISSUE THREAD

**Issue by kkoch** [glos/myglos#188]
User sent the following issue.  I was able to get data from Lake Huron, Ontario, Superior but Lake Michigan and Lake Erie as well does indeed give the internal error she reports >

I'm trying to download wave data for a point in Lake Michigan. This offshore wave data is of very importance since I will use the information to help calibrate a nearshore wave model. I've been able to do this in the past using the GLCFS Point Query tool, however, when I try to download data for my required period of time (11/06/17 - 01/05/18), it tells me the server encountered an internal error that prevented it from fulfilling the request (see error at the end of the email).
Would it be possible to get the wave data from another source? Is there something I can do differently to avoid this error? I'd really appreciate any kind of help you can provide me.
Thanks in advance and have a wonderful day!
Best regards,
Alejandra Lira
HTTP Status 500 - opendap.dap.DataReadException: Inconsistent array length read: 1165128303 != 1914731274
type Exception report
message opendap.dap.DataReadException: Inconsistent array length read: 1165128303 != 1914731274
description The server encountered an internal error that prevented it from fulfilling this request.
exception
java.io.IOException: opendap.dap.DataReadException: Inconsistent array length read: 1165128303 != 1914731274
ucar.nc2.dods.DODSNetcdfFile.readData(DODSNetcdfFile.java:1662)
ucar.nc2.Variable.reallyRead(Variable.java:879)
ucar.nc2.Variable._read(Variable.java:865)
ucar.nc2.Variable.read(Variable.java:677)
ucar.nc2.dataset.VariableDS.reallyRead(VariableDS.java:553)
ucar.nc2.dataset.VariableDS._read(VariableDS.java:533)
ucar.nc2.Variable.read(Variable.java:677)
ucar.nc2.Variable.read(Variable.java:651)
us.glos.glcfs.serlvet.GLCFSPointSourceServlet.doGet(GLCFSPointSourceServlet.java:429)
javax.servlet.http.HttpServlet.service(HttpServlet.java:620)
javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
org.glc.StartPoint.doFilter(StartPoint.java:55)
note The full stack trace of the root cause is available in the Apache Tomcat/7.0.57 logs.

**Comment by tslawecki** [comment]
Roping in @cheryldmorse too ... does this possibly relate to the error you discussed with @gcutrell last week where you suggested consideration of upgrading TDS? Current version is apparently 4.6.11, you noted we're at 4.6.5.

**Comment by tslawecki** [comment]
@gcutrell or @kkoch - please reach out to Alejandra to find out location; we can help her set up a direct TDS query.

**Comment by kkoch** [comment]
I will do.

**Comment by gcutrell** [comment]
A restart of thredds will enable it to work again although for less than 12 hours. Until it is fixed I can just restart thredds when I get to work and leave work. The PQT is working now.

**Comment by kkoch** [comment]
Painful. But thanks.  I also have a message to user to get the parameters she needs but I will also inform her that we have a bandaid in place.

**Comment by kknee** [comment]
@tslawecki we need to update TDS.  Should we go ahead and do that?

**Comment by tslawecki** [comment]
Yes, please!



________________________________

**Comment by kknee** [comment]
@cheryldmorse will do the update in the early am next week.  The TDS may be up and down for a while while the update occurs - what's the best day to do this?

**Comment by cheryldmorse** [comment]
@tslawecki - Is there a specific day that I should (or shouldn't)  update TDS? The server may be down for a short period of time

**Comment by tslawecki** [comment]
Go when convenient, just notify the group so (1) we can put up a notice on the main portal and (2) we're prepared if anyone using PQT or direct THREDDS/ERDDAP complains.



________________________________

**Comment by cheryldmorse** [comment]
@tslawecki @kknee - I plan on updating THREDDS in the morning o 1/29.

**Comment by kkoch** [comment]
I sent a reminder to Kristin and Becky as well in case we have longer term issues for users that day.

**Comment by cheryldmorse** [comment]
@tslawecki, @kknee -  TDS version 4.6.11 is now up and running

**Comment by gcutrell** [comment]
Thanks!

**Comment by kknee** [comment]
per @cheryldmorse TDS has been updated.  Closing this issue.
