### ISSUE TITLE
Federal Shutdown notice

### ISSUE THREAD

**Issue by kkoch** [glos/myglos#189]
We will need to put a banner on all data products notifying users that the federal shutdown will  effect our federal data sources.

**Comment by everhamme** [comment]
I see NOAA GLERL is still open..  any idea when that might change?

**Comment by beckypearson** [comment]
NOAA GLERL is closed.  Employees have four hours this morning to close things down and then they have to be out. At this time they cannot even access their email. 

Interesting times.
