### ISSUE TITLE
thredds.glos.us Critical disk usage

### ISSUE THREAD

**Issue by gcutrell** [glos/myglos#191]
@cheryldmorse I noticed today that thredds is at critical capacity again. I couldn’t remember what you did in November (guessing it involved a log file) but could you do it again? Could you also note in this github issue what your doing for the future? 

FYI I noticed it takes ~2 months to run through 50% of the disk capacity. 
@tslawecki @kknee

**Comment by cheryldmorse** [comment]
@gcutrell - It's back to 80%. 
I removed old thredds and tomcat log files from the following places:
/var/lib/tomcat/applications/thredds-4.6.6/content/thredds/logs
/var/lib/tomcat/applications/thredds-4.6.6/logs

**Comment by gcutrell** [comment]
@cheryldmorse Thanks!
