### ISSUE TITLE
Reroute portal feedback/contact forms to GLOS CRM

### ISSUE THREAD

**Issue by tslawecki** [glos/myglos#192]
Per Becky,

_We are implementing a Saleforce-based CRM, and we would like to get all those who contact us via the Data Portal or the GLBuoys feedbacl forms integrated into Salesforce. Attached are the code for both data products.  I hope it isn't too much trouble to reformat these forms.  Let me know if you have any problems._ 

For the portal forms, the intent is to transmit the form information to the CRM using new HTML based on the attached; the CRM will then send on appropriate e-mails. @kknee, could you have someone look at the attachments and assess LOE? 

[html.zip](https://github.com/glos/myglos/files/1682934/html.zip)

**Comment by kknee** [comment]
@tslawecki  - @gitchrisadams is looking at this.  

It's difficult to assess effort until he can test locally with the saleforce endpoint. It hits this endpoint: https://webto.salesforce.com/servlet/servlet.WebToLead?encoding=UTF-8
Chris has some local code to test, be we don't want to be sending data to  salesforce crm if it will cause issues. Is there a test endpoint?   Also to see if it actually gets to salesforce, we would need some way to view the sales force data, such as a login or someone to check for us whether data is coming through.

**Comment by kkoch** [comment]
@kknee @gitchrisadams From Kristin: We are trying to get our contact forms to play nice with Salesforce. The one on the portal does not, so I have some code for you to use so it will. Let me know if you have questions, I'll connect you with our Salesforce consultant.  (@kknee I've also forwarded the email to you)

`





<META HTTP-EQUIV="Content-type" CONTENT="text/html; charset=UTF-8">





<form action="https://webto.salesforce.com/servlet/servlet.WebToLead?encoding=UTF-8" method="POST">

<input type=hidden name="oid" value="00D36000000H0Im">
<input type=hidden name="retURL" value="https://www.glos.us/">









<label for="first_name">First Name </label><input  id="first_name" maxlength="40" name="first_name" size="20" type="text" /><br>

<label for="last_name">Last Name </label><input  id="last_name" maxlength="80" name="last_name" size="20" type="text" /><br>

<label for="email">Email address </label><input  id="email" maxlength="80" name="email" size="20" type="text" /><br>

<label for="company">Organization </label><input  id="company" maxlength="40" name="company" size="20" type="text" /><br>

<label for="description">Feedback or Issue </label><textarea name="description"></textarea><br>

<input type="hidden" id="lead_source" name="lead_source" value="Web - Data Portal">

<input type="submit" name="submit">

</form>
`

**Comment by kknee** [comment]
This is working on dev.

**Comment by kkoch** [comment]
Message to Kristin & Becky to see if we are good to close this.

**Comment by kkoch** [comment]
From Becky >the leads are getting populated from the portal, the glbuoy feedback form and the general web contract form.  So, it looks like you can close the issue in github.
