### ISSUE TITLE
Alerts API

### ISSUE THREAD

**Issue by kkoch** [glos/myglos#193]
Create an alerts API.  Will be utilized by Portal (and Boaters View) as well as GLBuoys.  See also: Boaters enhancements ticket #158.

@tslawecki @kknee Tasks need to be defined here >

**Comment by kknee** [comment]
here's my take on tasks, we are most of the way there, will provide an update on today's call.

@cheryldmorse FYI

- [x] Set an alert: API is passed email and/or phone number, buoyID, parameter name, comparison type(s) (>, <, =, etc), comparison value(s).  In this case a new alert will be added to the alerts DB and the user will start receiving emails when the alert is triggered: 
- [x] Send text message alerts – set up API to send SMS, but don't implement yet
- [x] Allow users without accounts to set up alerts as long as they provide email/phone number.  
- [x] View Existing Alerts: API is passed a username.  The API returns a list of alerts for that user.
- [x] Delete Alerts: API is passed ID of alert to be deleted, the API removes that alert from the DB 
- [x] allow unregistered users to delete alerts by unsubscribing to the emails/texts.  
- [x] Edit Alerts:   Users must have accounts to edit alerts
- [x] allow the user to set an alert for a forecast - site expected to pass layer name (model/parameter) and lat/lon to API, API checks next 12 hours of forecast for alert
- [x] autodelete alerts for unregistered users
- [x] boolean indicating contact permission
- [x] add creation date

**Comment by kknee** [comment]
This is all set.  @kkoch did you put the documentation on the GLOS wiki?  Also here are the answers to Tad's questions, good to document these somewhere too:

1) How often do we check?
 - Hourly

2) For buoys, we check the most recent value?
 - The most recent obs within the last 24 hours

3) For models, we check the most recent forecast and look at now through now + 12 hours?
 Yes

4) What is the alert condition ... max_threshold = xxx means tell me if value > xxx? min_threshold = yyy -> tell me if value < yyy
 Exactly. You can set just one or both conditions. If you specify both then the condition would be > max or < min

5) What are valid GLOS catalog IDs for models?
 GLERLECUR_CURRENTS 
GLERLEWND_WINDS 
LAKE_ERIE_ELEVATION 
LAKE_ERIE_ICE_CONCENTRATION 
LAKE_ERIE_WAVE_DIRECTION 
LAKE_ERIE_WAVE_HEIGHT 
GLERLMCUR_CURRENTS 
GLERLMWND_WINDS 
LAKE_MICHIGAN_ELEVATION 
LAKE_MICHIGAN_ICE_CONCENTRATION 
LAKE_MICHIGAN_WAVE_DIRECTION 
LAKE_MICHIGAN_WAVE_HEIGHT 
GLERLSCUR_CURRENTS 
GLERLSWND_WINDS 
LAKE_SUPERIOR_ELEVATION 
LAKE_SUPERIOR_ICE_CONCENTRATION 
LAKE_SUPERIOR_WAVE_DIRECTION 
LAKE_SUPERIOR_WAVE_HEIGHT 
GLERLOCUR_CURRENTS 
GLERLOWND_WINDS 
LAKE_ONTARIO_ELEVATION 
LAKE_ONTARIO_ICE_CONCENTRATION 
LAKE_ONTARIO_WAVE_DIRECTION 
LAKE_ONTARIO_WAVE_HEIGHT 
GLERLHWND_WINDS 
GLERLHCUR_CURRENTS 
LAKE_HURON_ELEVATION 
LAKE_HURON_ICE_CONCENTRATION 
LAKE_HURON_WAVE_DIRECTION 
LAKE_HURON_WAVE_HEIGHT 
HECWFS_CURRENTS 
HECWFS_SST 
HECWFS_ELEVATION 
NOSLEOFS_ELEVATION 
NOSLEOFS_SST 
NOSLEOFS_CURRENTS 
NOS_MICHIGAN_ELEVATION 
NOS_MICHIGAN_3D_SST 
NOSMICHCUR_CURRENTS 
NOS_HURON_ELEVATION 
NOS_HURON_3D_SST 
NOSHURCUR_CURRENTS 
NOS_SUPERIOR_ELEVATION 
NOS_SUPERIOR_SST 
NOSSUPCUR_CURRENTS 
NOS_ONTARIO_ELEVATION 
NOS_ONTARIO_3D_SST 
NOSONTCUR_CURRENTS 


6) What's the structure for valid GLOS URLs for stations?
 Here is an example: https://portal.glos.us/api/observations?provider=glos&platform=leorgn&parameter=WaterTemperature


7) What's the format for the alert text? Same or different for SMS and e-mail?
The format of the email is below. The text message format has not been defined, however the API is setup to accept a phone number

'Here are the alerts you have subscribed to and have been triggered:'
'Alerted on {parameter} from {origin} being out of valid threshold range ({min_threshold}, {max_threshold}).
'Value was observed at {value:.2f} ({units}) on {time}
To Unsubscribe from this alert visit this link: ‘ {unsubscribe_link}

8) Is it trivial to add one more text field - a user string?
This would be 1-2 hours

**Comment by kkoch** [comment]
@kknee I have not re: the Wiki other than an empty page/placeholder.  So... I can copy above. Is there any other documentation?
