### ISSUE TITLE
Update Google Analytics to track date range choices

### ISSUE THREAD

**Issue by kkoch** [glos/myglos#195]
GLOS raised the question whether the date range dropdown on the portal is useful (primarily because this seems to be a heavy hitter off-season and Google Analytics team were wondering if people were just clicking it to see what was there and what it does).  

In order to better determine usefulness, team would like to track what specific date users are attempting to change to. This would require RPS to make a change in the analytics for the page. 

@kknee can you determine LOE to do this?

**Comment by devrap** [comment]
@kkoch and @kknee, just to clarify: this is currently recorded as an event action ("Time Change") but with no value. @Bobfrat, can we have this capture the value?

**Comment by kknee** [comment]
low LOE, so this is on dev now

**Comment by kknee** [comment]
this has been on production since late March, closing
