### ISSUE TITLE
Add GLOS Gliders to Portal

### ISSUE THREAD

**Issue by kknee** [glos/myglos#198]
I believe this is wanted as part of the 2018 scope, but @tslawecki or @kkoch please confirm.  I believe the LOE is low, but will come back to you if not.

**Comment by kkoch** [comment]
I believe so.  I think it came up either in an email or meeting that IOOS was wondering where our gliders were.  And Tad has it on today's DMAC agenda to discuss.

**Comment by kknee** [comment]
Gliders are appearing on the portal!  

![image](https://user-images.githubusercontent.com/196868/37480665-33834c76-2856-11e8-830f-94fb6e88a809.png)
