### ISSUE TITLE
Issue accessing json from browser

### ISSUE THREAD

**Issue by kkoch** [glos/myglos#199]
I don't know if this is related to the existing server space issues but when I try to go to view the json files for the buoys directly from a browser I get no data, just a couple of brackets (e.g., [ ] )

The command I usually use (via Chrome with a json viewer) to see all the buoys is 
http://data.glos.us/portal/getObsCatalog.php?providers=glos

I also tried it with one of the direct links to the json files that I have in geonetwork, e.g., this is the link for 45179 > http://data.glos.us/portal/getObsByPlatform.php?provider=glos&platform=Stannard+Rock+Buoy
Same thing, I just get brackets, but that and other buoys seem to display okay in portal.

I did also try to view the conservation authority records which is using kisters for the provider and that works. http://data.glos.us/portal/getObsCatalog.php?providers=kistersCSV

If I enter this command which is one Charleton had me use for testing awhile back > http://data.glos.us/glos_obs/platform.glos?tid=15 > I get an error: "Service Temporarily Unavailable. The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later."   But I don't really know whether that one should be working.  The above ones definitely should.

**Comment by cheryldmorse** [comment]
@kkoch - All good now. The tomcat instance on data.glos.us was down so data couldn't be retrieved from the obs database

**Comment by gcutrell** [comment]
This probably started after the servers were down for maintenance. Same issue as GLCFS. Good to know for the future.
