### ISSUE TITLE
Canadian water levels stuck in 2016?

### ISSUE THREAD

**Issue by tslawecki** [glos/myglos#201]
It looks like the harvest of Canadian water levels stopped in 2016 - last date clicking around at random is 12/30/2016. @gcutrell or may @cheryldmorse  could one of you look to see if this is process-stopped-and-never-restarted or format-changed-and-harvest-is-crashing? I'm not sure if this was implemented by Guan or RPS, maybe @kknee knows?

**Comment by kkoch** [comment]
You had brought up in an email Nov of 2016 (pre github time) that data was frozen at 10/1/2016.  My research at the time shows that they (meaning Canadia) had a notice on their page "Service Interruption... GL Water Levels is currently unavailable...."  I do not have any follow on emails after that so I'm assuming they had a website change and we did not pick up on that after they came back online.  They do appear to be back online.

Also if I go back further to when it was implemented - it was a Luke creation of a 'collection' so RPS.

**Comment by kkoch** [comment]
http://www.tides.gc.ca/eng/find/region/6

**Comment by tslawecki** [comment]
Ingest is working again, problem was a new year directory (2018) needed to be created under each station. We will probably backfill what we can (back to 10/2017).  Three additional steps needed:

 1 - correct Little Currents location, currently in Wisconsin/Michigan

 2- Check that our list of stations is current (see below)

 3- Verify current station data are showing correctly (checked)

- [x] 10050 Thunder Bay
- [x] 10220 Rossport
- [ ] 10750 Michipicoten Harbour __not sure why but the record on TDS does not look complete_
- [x] 10920 Gros Cap
- [x] 10980 Sault Ste Marie above/amont
- [x] 11010 Sault Ste Marie below/aval
- [x] 11070 Thessalon
- [x] 11195 Little Current
- [x] 11375 Parry Sound
- [x] 11445 Midland
- [x] 11500 Collingwood
- [ ] 11690 Tobermory __not sure why but the record on TDS does not look complete_
- [x] 11860 Goderich
- [x] 11940 Point Edward
- [x] 11950 Port Lambton
- [x] 11965 Belle River
- [x] 11995 Amherstburg
- [x] 12005 Bar Point
- [x] 12065 Kingsville
- [x] 12250 Erieau
- [x] 12400 Port Stanley
- [x] 12710 Port Dover
- [x] 12865 Port Colborne
- [x] 13030 Port Weller
- [x] 13150 Burlington
- [x] 13320 Toronto
- [x] 13590 Cobourg
- [x] 13988 Kingston (Portsmouth)
- [x] 14400 Brockville
- [x] 14600 Iroquois above/amont
- [x] 14602 Iroquois below/aval
- [x] 14660 Morrisburg
- [x] 14870 Cornwall
- [x] 14940 Summerstown

**Comment by tslawecki** [comment]
Let's also change the referenced URL to http://tides.gc.ca/eng/find/region/6

**Comment by kkoch** [comment]
All items checked and most displaying in portal.  There are two odd ones: 10750 and 11690, so obviously data still showing as 2016 in portal. @tslawecki the TDS records look incomplete.

@kknee the above referenced URL by Tad (for external links "Canadian Water Levels Gauging Stations" will need to be assigned and changed on your end since we don't use the GN record for the collection.  (NOTE: I have changed in GN for correctness and consistency.)  Also, I believe it is on your end to correct the location for Little Current out of the Hiawatha National Forest location.  It should be somewhere around 45.98 -81.92 (Lake Huron region - at least that's what  I have in GN. I am going to guess the error is a -86 instead of -81 for lon).

**Comment by kknee** [comment]
@kkoch can you confirm the GN link for this layer?  The one we have is throwing an error:
http://data.glos.us/metadata/srv/eng/main.home?uuid=9b0556ed-689b-4ba0-95de-8882680d8e77

**Comment by kkoch** [comment]
Well I'm a little freaked out because that record is missing from GN. And I haven't deleted anything and I was looking at it a couple days ago. I will investigate.

**Comment by kkoch** [comment]
@tslawecki @gcutrell can you check the GN25 server?  I'm puzzled on this one and the error logs I can read don't tell me much (but they might you). Log directory is /var/lib/tomcat/applications/geonetwork/logs

I'm somewhat concerned that we have a corrupted file but also we've seen this before when the server filled up.  The catalina-daemon.out log is ginormous ....

![image](https://user-images.githubusercontent.com/6392982/38098830-fe07ca58-3346-11e8-9aa3-07d808bfbedd.png)

... which we've also had issues before and which we at one point not too long ago needed to clean up and reset (I remember Luke suggesting we put a process in place to automatically purge that file but that was never done - maybe Greg remembers the conversation???)   See also: issue #117

**Comment by gcutrell** [comment]
I cleared the catalina-daemon.out a couple months ago so it might look big but there is still plenty of space on the server. Luke suggested logrotate. I think there are a few log files that need that across GLOS's servers. 

I found a little more information in localhost log on the error but not sure what it means.
'org.apache.catalina.core.StandardWrapperValve invoke
SEVERE: Servlet.service() for servlet [gn-servlet] in context with path [/metadata] threw exception'

There is a genetwork.log that might reveal more information but it appears the current day is only generated at the end of the day so we can't see one for today right now.

**Comment by kkoch** [comment]
Well I was hoping.  I'm going to go see if I can find the record in my backups.  I'm not sure when the error happened but I'm guessing it would be in yesterday's log as well.  I believe it was in a good state 2 weeks ago.

See attached for text of the error that happens when you go to the url. Looks like its giving an access error (but I can get to other GN records just fine) ???


[canadian_errormsg.txt](https://github.com/glos/myglos/files/1861121/canadian_errormsg.txt)

I should add that I restarted geonetwork just in case but it made no diff.

**Comment by kkoch** [comment]
Okay. the metadata record reappeared ????  I did nothing.  Thoughts? @gcutrell @cheryldmorse @kknee

**Comment by kknee** [comment]
update, the link  is throwing an error again (http://data.glos.us/metadata/srv/eng/main.home?uuid=9b0556ed-689b-4ba0-95de-8882680d8e77)

**Comment by kkoch** [comment]
weird - did someone edit the record recently?  I can't tell but the privileges were removed from "all".  I've just reset them and link appears to work (but won't flow thru to the portal until the next refresh).  So for future reference, if it does that for any record and I'm not around > log in to admin for GN and check the privileges as follows (Other Actions, click on Privileges) >
![image](https://user-images.githubusercontent.com/6392982/40059535-4a701620-5822-11e8-85a8-0602d8c60500.png)

If there are no checks in the Privileges for "All" at the top, 
![image](https://user-images.githubusercontent.com/6392982/40059423-ff5be664-5821-11e8-82a7-139575ecafeb.png)

... then click on the "Set All" button (or you can manually check all the boxes) and click the SUBMIT button at the bottom of the pop-up.
![image](https://user-images.githubusercontent.com/6392982/40059477-24c267a2-5822-11e8-9dea-a58087d169a6.png)
![image](https://user-images.githubusercontent.com/6392982/40059623-863d94a2-5822-11e8-9163-7a0afc02301c.png)

**Comment by kknee** [comment]
metadata record is loading after @kkoch fix.  all set here.
