### ISSUE TITLE
Change navigation from Catalog/Map to show only "Switch to X view"?

### ISSUE THREAD

**Issue by devrap** [glos/myglos#203]
Hi, all.

We've only been tracking Portal users' top navigation choices for a few days, but so far the results are alarming. It looks like the # one action people are taking so far is to click on the Catalog button from the Catalog page--53 went through and 58 dropped off, likely after seeing nothing change.  We can track this for longer, but this seems to be a red flag that our navigation needs improving--why would people know they're in a catalog view?-- and is a clear place we're losing people instead of getting engagement.

Sneha (who I don't think is on GitHub) and @tslawecki both suggested changing the navigation to dynamically only show the alternative option, e.g..: "Switch to Map View" or "Switch to Catalog View."  Or it may have just been "Switch to X". 

Additionally, it would help by having a view title show. Becky suggested changing the | Data Portal in the title to | Data Portal Catalog and | Data Portal Map (unsure if View was in there.)

Please discuss. Tagging @kkoch, @kknee and @Bobfrat in here, too.

**Comment by Bobfrat** [comment]
Very interesting and good to know. I like the idea of only showing Switch to Map View when on the catalog and vice versa.

**Comment by devrap** [comment]
@tslawecki or @kkoch : can we add this 1) toggle and 2) Title change (showing which view people are in) to the RPS to-do list? Not sure where it lands in terms of priority. Thanks.

**Comment by tslawecki** [comment]
On an analytics call right now, let's get this done ASARP - no later than the end of the month.



________________________________

**Comment by kknee** [comment]
this is done on dev: http://dev.oceansmap.com/myglos/#

**Comment by devrap** [comment]
Thanks for the update, @kknee . Given the really high number of users clicking on Catalog from the Catalog view (and exiting), I don't think just adding "switch to"  is going to be sufficient here. We need the toggle to remove visibility so people are not trying to click on Catalog and wondering why nothing is changing.

Per the original post, we need to also: 

--remove the Catalog button from the Catalog view and the Map button from the Map view. 

--have the title toggling as well: Data Portal Catalog and Data Portal Map.  Otherwise, people don't/won't know they're in the Catalog. (As that's currently part of a full logo , it will need to be split up and change to dynamic text.) 

Thanks.

**Comment by kknee** [comment]
@devrap apologies, we misunderstood the first point, will look into making that change.  

for the second point, when you say 'title' do you mean the header of the page:
![image](https://user-images.githubusercontent.com/196868/40092104-8714c168-5889-11e8-9cea-247020f4f00f.png)

**Comment by kknee** [comment]
@gitchrisadams kindly mocked this up, he'll push to dev shortly, but NOTE we will be switching the title images out, they show the concept but need correct font, spacing etc:

![image](https://user-images.githubusercontent.com/196868/40129845-58e75b78-5903-11e8-8d21-a685375bdbac.png)

![image](https://user-images.githubusercontent.com/196868/40129847-5c719aa6-5903-11e8-811c-9f63e801e66d.png)

**Comment by kkoch** [comment]
Do you already have the necessary text and graphics for the splits?  I have the ones I've been creating for the Boaters view and GLBuoys which might differ from what you used originally but then at least they'd all be the same.

**Comment by devrap** [comment]
@kknee and @gitchrisadams --Yep, this would work! Alternatively: "Catalog View" or "Map View" could display as a small title in the center. This would keep Data Portal untouched. Thanks.
