### ISSUE TITLE
Portal refresh?

### ISSUE THREAD

**Issue by kkoch** [glos/myglos#205]
Added metadata at 9am and still don't see it in production portal (2pm).  Do we need someone to kick something?

Also can't test to be sure it isn't something I've erred on my end because Dev isn't showing buoys either (which is usually where I go if things aren't showing up - because if things are done right in GN, it will show there first).

**Comment by kknee** [comment]
@kkoch what did you add metadata to?  Assuming you still can't test since buoys are still not available?

**Comment by kkoch** [comment]
It was an addition to the new Lorain sonde.  And obviously when I submitted the ticket there "were" stations.  So guess we just need to wait.

**Comment by Bobfrat** [comment]
Is it on the dev site now? Buoys are back on dev. I can push to production if we're happy.

http://dev.oceansmap.com/myglos/

**Comment by kkoch** [comment]
Yep. Looks good. Make it so...
