### ISSUE TITLE
GLENIJC Metadata (linking to QA documentation)

### ISSUE THREAD

**Issue by kknee** [glos/myglos#21]
@kkoch processed the data into netCDF format and would like to add a link to quality control document. ASA suggested putting the link into the global attribute ‘references’.  @lukecampbell will send an example and @kkoch will manually insert it into the nc files

**Comment by kkoch** [comment]
Example: 
mass_concentration_of_oxygen_in_sea_water:references = "http://www.hrecos.org/images/Data/forweb/HRECOS.QAPP.2013.03.14.pdf" ;
http://sos.maracoos.org/stable/dodsC/hrecos/STCPBY1/STCPBY1_2016-07-05.nc.html

**Comment by kknee** [comment]
@kkoch is this all set?

**Comment by kkoch** [comment]
Nope. Still waiting on document from PI

**Comment by kkoch** [comment]
Greg Cuttrell  has updated the netCDF files.  Per Tad at last DMAC > Tad needs to take one last look at the netCDF files Greg Cuttrell has modified and then he will run them by ASA

**Comment by tslawecki** [comment]
The link to QA documentation is in there properly, so perhaps @gcutrell or @lukecampbell  can do one last compliance check and we close this?

**Comment by gcutrell** [comment]
In a previous email it was noted from an example of Lukes that the qa/qc information was placed as a "references" attribute under each parameter. Looking back at my files I placed the instrument type and model for each parameters "references" and placed the qa/qc information under the global "references" attribute . If this is OK I did not receive any compliance alerts that a parameter or global references was missing.

**Comment by kknee** [comment]
@lukecampbell can you do one final check that this looks okay to you and then close?

**Comment by gcutrell** [comment]
The QA documentation (https://drive.google.com/file/d/0B7pJZVmOuWvzWUhuNDF4djBkeDA) is located in the global attributes "references" for each station and year.

**Comment by lukecampbell** [comment]
For some reason we're marking the instruments as belonging to CenCOOS?

```
instrument:long_name = "urn:ioos:sensor:cencoos:leorgn:sea_surface_water_temperature" ;
```

**Comment by gcutrell** [comment]
That's strange. Is it only instruments from HABs stations?
