### ISSUE TITLE
Need to block TDS access for selected IP ranges ASARP Monday AM

### ISSUE THREAD

**Issue by tslawecki** [glos/myglos#217]
Starting May 1, someone has been harvesting model data from the TDS server using a very fast connection that is blowing away our hosted bandwidth cap. The IPs shown in [AWStats](http://tds.glos.us/cgi-bin/awstats.pl?month=05&year=2018&output=allhosts&config=tds&framename=index) are from the Google Cloud (filter on "bc.google"), so I've (1) contacted Google and (2) requested our hosting service to block port 8080 access from the IP ranges in AWStats. However, the TDS logs show continued connections and downloads, so I'd like to block access directly on the TDS server using either a Tomcat valve or iptables/firewall-config.

I'd prefer for RPS (@kknee, is this for @cheryldmorse or an Adams?) to do this Monday as it's outside of my comfort zone. Also advising @gcutrell as GLBuoys and PQT should be spot checked after RPS implements block.

The suggested ranges for blocking are:

35.187.*
35.195.*
35.205.*
35.233.*
104.155.*
104.199.*
130.211.*
146.148.*

**Comment by cheryldmorse** [comment]
@ajosephides - can  you take a look at this?

**Comment by cheryldmorse** [comment]
@Andrewjosephides - Can you take a look at this?

**Comment by andrewjosephides** [comment]
@tslawecki @cheryldmorse Continuing discussion through email correspondence.

**Comment by kknee** [comment]
outcome for this is in @andrewjosephides email, closing

**Comment by tslawecki** [comment]
@andrewjosephides, @kknee - AWStats still shows access from 35.195.\*, 35.205.\*, 35.233.\*, and 35.187.\* yesterday (and I'm guessing access today will show in the raw logs) ... any thoughts?

**Comment by tslawecki** [comment]
Closing for now - will work later to (1) have accessor cut down bandwidth and (2) limit bandwidth on TDS server in nginx/apache.
