### ISSUE TITLE
Add MTRI WMS Sources

### ISSUE THREAD

**Issue by kknee** [glos/myglos#22]

**Comment by ColinNBrooks** [comment]
Thanks for adding this, this is still a priority for me to represent the remote sensing data in the best way possible.

**Comment by kknee** [comment]
Update, GFI for time ranges was not working.

Mike Billmire fixed week of 8/15.

ASA needs to integrate new requests and test

**Comment by kkoch** [comment]
Not sure if this fits in this issue or if we need a new one. But MTRI has re-posted all of the 2016 data to their FTP to capture any missing data on the Portal.  Let Amanda Grimm (aggrimm@mtu.edu) know if there is something else that they need to do on their end.

**Comment by kknee** [comment]
@kkoch yes, and all the latest data is on the GLOS TDS, so we're in good shape on that front.

Still working out a few issues with the new MTRI MapServer services and we'll be good to switch to those services for the portal.

**Comment by kknee** [comment]
see sources called "MTRI..." in catalog
