### ISSUE TITLE
MTRI layers not displaying 

### ISSUE THREAD

**Issue by tslawecki** [glos/myglos#224]
In Data Portal,  using Chrome and IE - tried to add MTRI Lake Erie satellite temperature, DOC, chlorophyll. In "Data Layers" tab in map view, the message is "There was an error drawing this layer". @kkoch, can you replicate this? If so, any thoughts from @kknee, @Bobfrat, @cheryldmorse, @ColinNBrooks, @gcutrell?

**Comment by ColinNBrooks** [comment]
Not yet. I checked that our server is up & displaying data and things seem OK there. 

I just checked MTRI Erie Cholorphyll and it seems to be displaying OK:
![image](https://user-images.githubusercontent.com/20344813/40728465-2bee20a2-63f8-11e8-82f5-3b3f3ab7e4ec.png)

**Comment by kkoch** [comment]
I have not been able to replicate.  Tried all lakes, various parameters, virtual buoy using FF, IE, Chrome, two different computers.  All behaving.

**Comment by ColinNBrooks** [comment]
Temporary blip, perhaps?

**Comment by tslawecki** [comment]
Let's call it a blip. Closing.
