### ISSUE TITLE
Add new OSU buoy to Portal, GLBuoys, HABs Portals (OSUSS)

### ISSUE THREAD

**Issue by kkoch** [glos/myglos#228]
The buoy was deployed 2 weeks ago.
Sandusky Subbasin | 41.53277, -82.4611

It measures the standard YSI EXO parameters except dissolved oxygen. We are down a DO probe and through surface DO is not too exciting.
Justin Chaffin, PhD
Research Coordinator, Senior Researcher
The Ohio State University
Franz Theodore Stone Laboratory Ohio Sea Grant
P.O. Box 119, 878 Bayview Ave., Put-in-Bay, OH 43456-0119
419-285-1845 Office / 419-285-1878 Fax

**Comment by kkoch** [comment]
Justin has sent me metadata form and image for portal.  Pending for Greg to get data for Obs.  I've also set up a ticket for HABs portal.

@gcutrell and Ed are working with him on how to get the data ftp'd to us

Here is text of latest emails >
Kathy Koch will have some metadata forms for you to fill out. I won’t be able to get everything up till next week but I created a directory called “osuss” that you can start sending data. Just ftp data to ‘ftp.glos.us/osuss” in ichart.  Once I get everything set up all the old data will be ingested into GLOS so it can at least be stored and retrieved from GLOS’s database in the future. 

>
Justin – you likely need ot instruct Fondriest to do this for you..  we do not have access to your stations like we do for UToledo and BGSU (however we could if you’d like to go that route).
Ed

**Comment by gcutrell** [comment]
@kkoch I lost track of the metadata. Could you attach it to this issue?

**Comment by kkoch** [comment]
metadata record > http://data.glos.us/metadata/srv/eng/home?uuid=d52a49ce-d046-43bf-ba1b-067b93b66501

@gcutrell  I just added it to GN  :)

**Comment by kkoch** [comment]
@gcutrell what is the status on these?  

I saw the email trail on discussions about parameters but still don't see osuss in obs at all 
and while I see the green bay buoys is in obs, no data yet.

**Comment by gcutrell** [comment]
I found a mistake in a database table. Here is a working obs link http://data.glos.us/portal/getObsByPlatform.php?provider=glos&platform=Sandusky+Subbasin+Buoy

**Comment by kkoch** [comment]
Okay. I've updated GeoNetwork.  Will check tomorrow to see it things show up on the Portal following the standard refresh cycle.
