### ISSUE TITLE
Add links to appropriate GL buoy pages

### ISSUE THREAD

**Issue by kristinschrader** [glos/myglos#234]
We have individual fundraising pages set up for GLOS-supported buoys. Please add the links to the pages. 

thehttps://donate.glos.us/campaign/western-lake-superior-40528

https://donate.glos.us/campaign/duluth-mcquade-45027

https://donate.glos.us/campaign/south-keweenaw-45025

https://donate.glos.us/campaign/ludington-buoy-45024

https://donate.glos.us/campaign/buoy-45023-north-entry

https://donate.glos.us/45022LittleTraverse 

https://donate.glos.us/45013Atwater 

https://donate.glos.us/SGreenBay

**Comment by everhamme** [comment]
Yeah!





_____________________________________
Ed Verhamme
Project Engineer
501 Avis Drive, Ann Arbor, MI 48108
Office: 734-332-1200<tel:734-332-1200> Direct/Cell: 734-681-0577<tel:734-681-0577>
Email: everhamme@limno.com<mailto:everhamme@limno.com>
http://twitter.com/eddiegreatlakes
LimnoTech           www.limno.com<http://www.limno.com/>
Water Environment | Scientists Engineers


-------- Original message --------

**Comment by kkoch** [comment]
Closing and moving this issue to GLBuoys repo.
