### ISSUE TITLE
45175, 45184, 45185, 45023, 45025, glrcmet no data in obs but ok in glbuoys

### ISSUE THREAD

**Issue by kkoch** [glos/myglos#236]
45175 (Mac Straits) buoy is showing no results in Portal (no data in obs) but does show recent data in GLBuoys.

See older closed 2016 issue that might be related #40.

**Comment by gcutrell** [comment]
Opps. This could be because they added PAR to to their buoy. Could that be missing it up?

**Comment by kkoch** [comment]
Hmmm. Maybe something needs to be regenerated?  I don't see a parameters list in my json view at all >

{
name: "Mackinac Straits West Buoy ? Mackinac Straits, MI",
lon: -84.77,
lat: 45.83,
tmin: null,
tmax: null,
abstract: "The buoy at the Mackinac Straits West buoy station (NDBC Station 45175) is a Total Integrated Data Acquisition Systems (TIDAS) model S2 Yachts-900 marine research station equipped with an Acoustic Doppler Current Profiler.",
keywords: null,
parameters: null,
categories: null,
provider_url: "",
data_url: "http://data.glos.us/portal/getObsByPlatform.php?provider=glos&platform=Mackinac+Straits+West+Buoy+%3F+Mackinac+Straits%2C+MI",
image_url: null,
source_name: null,
info_url: null
},

**Comment by kkoch** [comment]
@gcutrell  I also noticed this morning as with above that GLRCMET, 45023, 45025 buoys also do not have parameters showing in json and not showing data in Portal although I do see .nc files on thredds and for the buoys appear okay on GLBuoys.

**Comment by kkoch** [comment]
@gcutrell status?

**Comment by kkoch** [comment]
@cheryldmorse (or @kknee someone else at RPS?) > can you take a look at obs cache and see if you can figure out what is going on?  @gcutrell has made some changes but we still aren't seeing these buoys in the Portal.  This started right after he add the photosynthetic radiation parameter/variable which has some 'interesting' display challenges for units.

**Comment by cheryldmorse** [comment]
@kkoch this should be fixed now. 
@gcutrell the column 'definition' in the obs_type table for Photosynthetic_active_radiation contained a newline character which is an illegal character in json. This caused the obs cache to not process any stations that contained that variable because the json couldn't be parsed ( ie - the following endpoint returned non-parseable json: http://data.glos.us/glos_obs/sensor.glos?pid=438# )

**Comment by kkoch** [comment]
Awesome.  All looks well, closing issue.  Thanks @cheryldmorse!
