### ISSUE TITLE
Clicking on buoy name pops over to glos.us

### ISSUE THREAD

**Issue by kkoch** [glos/myglos#239]
I was hoping this was a glitch, but it's happened twice now >

On map view, have category narrowed to 'buoys...', clicked on a buoy name and it popped me over to glos.us website. Weird.  I have not been able to force it to occur (seems random), but can RPS folks can think of what would be making this happen?

**Comment by kknee** [comment]
@kkoch I know you said it seems random, but can you give me an example?

**Comment by kkoch** [comment]
@kknee I wish I could make it do it.  I remember that the 2nd time, the buoy title  (in catalog view on map), I clicked on was GVSU1.  I don't remember what the first one was but was a page or two before that.  I just ran through all the buoys again to see if it would repeat the behavior and it was fine.  So dunno.

**Comment by kkoch** [comment]
I'm going to consider this an anomaly.  Let's re-open the issue if it re-occurs.
