### ISSUE TITLE
Add two new Illinois Buoys (45186/45187)

### ISSUE THREAD

**Issue by kkoch** [glos/myglos#240]
From Ed >
We’ll be adding two new buoys to lake Michigan tomorrow or next week.
 
Can we set up the stations with GLOS?    Contact for the buoy is 
 
 
Ethan J. Theuerkauf, Ph.D.
ejtheu@illinois.edu 
Coastal Geologist
Illinois State Geological Survey
Prairie Research Institute
The University of Illinois at Urbana-Champaign
Great Lakes Coastal Geology Research Group
Adjunct Assistant Professor
Department of Earth and Environmental Sciences
The University of Illinois at Chicago
 
 
Here’s what was sent to NDBC
 
Waukegan, IL Buoy (45186)
Lat/Lon: 42.367168 -87.795225
Site Elevation: 176m above sea level
Air temperature height: 1m above site elevation
Anemometer height: 1.5m above site elevation
Sea temp depth: 1meter below water line
 
 
Winthrop Harbor, IL Buoy (45187)
Lat/Lon: 42.490631 -87.778884
Site Elevation: 176m above sea level
Air temperature height: 1m above site elevation
Anemometer height: 1.5m above site elevation
Sea temp depth: 1meter below water line
 
Both buoys will have an identical parameter set
Wind speed
Wind direction
Air temperature
Water temperature
Significant wave height
Dominant wave period
Mean wave direction
Surface Currents (uv001 & vv001)
Webcam
Air pressure

**Comment by kkoch** [comment]
Message sent to PI to fill out metadata form.

Preliminary (bare bones) GeoNetwork record created based on above details from Ed.

**Comment by gcutrell** [comment]
Here you go:
http://data.glos.us/portal/getObsByPlatform.php?provider=glos&platform=Winthrop+Harbor+Buoy

http://data.glos.us/portal/getObsByPlatform.php?provider=glos&platform=Waukegan+Buoy
