### ISSUE TITLE
Feedback forwarding for Portal

### ISSUE THREAD

**Issue by kkoch** [glos/myglos#241]
Please verify where the Feedback (Contact Us) gets forwarded to on the Portal.  If it goes to dmac then we are probably okay.  If it just goes to Kristin at GLOS, can you have someone switch that to my email (Kathy).

Needs to be done by August 17 which is Kristin's last day   :(

**Comment by Bobfrat** [comment]
Here's the email list:

> 
    - Kelly.Knee@rpsgroup.com
    - Robert.Fratantonio@rpsgroup.com
    - kkoch@limno.com
    - tslawecki@limno.com
    - bpearson@glos.us
    - kschrader@glos.us

**Comment by kkoch** [comment]
Okay I think we are good and can just remove Kristen (kschrader) after or close to depart date. Thx!

**Comment by kkoch** [comment]
@Bobfrat Can you remove kschrader@glos.us and let me know when done?

**Comment by Bobfrat** [comment]
Ok she's now been removed from feedback forwarding on the boaters portal and myglos portal
