### ISSUE TITLE
Boaters' missing units toggle

### ISSUE THREAD

**Issue by kkoch** [glos/myglos#243]
User Thomas Martin (email: tmartin8025@gmail.com) noticed that we don't have the Set Units toggle in the hamburger menu like on the Portal.  He would like to change from metric to english units.

Is this an easy implementation over to Boaters'?

**Comment by Bobfrat** [comment]
@kkoch we have this enabled in Dev. It should work for all the models and station data but i don't believe we'll convert any of the marina metadata. Are there any marina attributes that need to be converted? If it looks good can we push to production?

**Comment by kkoch** [comment]
@Bobfrat I think you are correct - I can't think any of the marina data that would include a unit needing conversion, so I think we are good.  

(As a side note, I'm still waiting on the clean marina details from SeaGrant before I have an updated csv for you on those.)

**Comment by kkoch** [comment]
@Bobfrat  status on the push to production? (as noted above, we can do so assuming it doesn't muck with marinas at this point).

**Comment by Bobfrat** [comment]
@kkoch the version on dev has been pushed to production. Note there was about 5 minutes of downtime as I deployed.

**Comment by kkoch** [comment]
Works (doubt anyone noticed on the downtime - but if so, we can at least know the reason).
