### ISSUE TITLE
Data display issue 45020 (Grand Traverse Bay)

### ISSUE THREAD

**Issue by kkoch** [glos/myglos#245]
Data looks odd in main Portal but okay in GLBuoys (and I see what looks like good data on thredds as well as the obs data link from json) >

![image](https://user-images.githubusercontent.com/6392982/45626696-2083c980-ba5e-11e8-8a13-80d3a3b0167d.png)

**Comment by kkoch** [comment]
Here's what I see on GLBuoys

![image](https://user-images.githubusercontent.com/6392982/45627101-24fcb200-ba5f-11e8-8c27-e50b97002e3a.png)

**Comment by gcutrell** [comment]
@kkoch Probably should have mentioned it to you but the buoy owners noticed the temp data looks good again so I started pushing it to GLOS. Maybe a bug in the portal?

**Comment by kkoch** [comment]
Thanks.  Looking okay now.  I'll close the issue and monitor for a couple days.
