### ISSUE TITLE
Duplicate `<gmd:fileIdentifier>` fields in ISO records

### ISSUE THREAD

**Issue by kkoch** [glos/myglos#247]
@brianmckenna As per discussion at DMAC meeting, please look into ISO file identifier issues brought up by Kyle Wilcox (see IOOS Catalog github ticket #68 [](https://github.com/ioos/catalog/issues/68) as it relates to the GLOS data.

**Comment by cheryldmorse** [comment]
Added the attributes naming_authority and id to the Lake*-Agg aggregations. Regenerated the WAF. This issue should be fixed now.
