### ISSUE TITLE
NOAA GLERL WE4 (glerlwe4) - no data

### ISSUE THREAD

**Issue by kkoch** [glos/myglos#25]
no data reporting in obs or in HABs but per Russ Miller > "We4 is trying too but it's cell signal is iffy and I don't have ftp retry turned on yet".   Need to just keep an eye out for this working or continuing not to work.

**Comment by hellocomrade** [comment]
@kkoch probably I need hook it up

**Comment by kkoch** [comment]
Last transmission: July 10

**Comment by hellocomrade** [comment]
@kkoch 

we4 has data:

http://data.glos.us/obs/station/15-428.html

**Comment by kkoch** [comment]
Yep. Looks like it is back. Thanks @hellocomrade
