### ISSUE TITLE
GLCFS GetCapabilities failing

### ISSUE THREAD

**Issue by Bobfrat** [glos/myglos#250]
Many of the GLCFS forecast GetCaps requests are failing. Here's an example:

http://tds.glos.us/thredds/wms/glos/glcfs/huron/fcfmrc-2d/Lake_Huron_-_2D_best.ncd?service=WMS&version=1.3.0&request=GetCapabilities

**Comment by tslawecki** [comment]
Looks like disk usage stepped up - there's 8.5 GB in /var/logs/nginx. I'll ask @gcutrell to clean that up and then check the URL again. 

Although looking at the output, I wonder if there's a file corruption issue?

**Comment by tslawecki** [comment]
@Bobfrat, since @gcutrell is out in the field I copied (to backup server), then truncated the localhost error log. Your example now seems to work correctly, is there anything else you'd like to test before we close?

**Comment by Bobfrat** [comment]
Everything is looking good, thank you
