### ISSUE TITLE
Duplicate dates in 45165_1 aggregated netcdf

### ISSUE THREAD

**Issue by gcutrell** [glos/myglos#251]
@cheryldmorse, I have been pulling off all the data from the aggregated netcdf files for buoys in Lake Erie and I noticed 10/18/2018 had its time duplicated and the values paired with the duplicate times are erroneous values. 

I believe this is the only aggregated station that does this. Could you see what happened and note here how to fix it in case I run across others? Thanks!

@kknee @tslawecki

**Comment by cheryldmorse** [comment]
@gcutrell The .ncml file hadn't been updated to exclude the records from the profile netCDF files so the aggregations were showing the time records from both files. I updated the .ncml file to only include the data from the non-profile netCDF files.

**Comment by gcutrell** [comment]
Thanks @cheryldmorse! Looks good.
