### ISSUE TITLE
Buoy data showing Nan values for thermistor string

### ISSUE THREAD

**Issue by snehabhadbhade** [glos/myglos#259]
@gcutrell reported - "As buoys have been deployed we noticed GLBuoys was not showing temp string data. I noticed on thredds that all temp string data is showing up as NaN’s which explains why GlBuoys doesn’t have data."

**Comment by gcutrell** [comment]
Also since the migration the ADCP profile data has not been processed for thredds (see http://tds.glos.us/thredds/catalog/buoys_standard/sbedison/2019/catalog.html). I’m guessing a script just needs to be started?

**Comment by snehabhadbhade** [comment]
Resolved!
