### ISSUE TITLE
NOAA GLERL WE13 (glerlwe13) - not in portal yet.

### ISSUE THREAD

**Issue by kkoch** [glos/myglos#26]
Nothing appearing yet in obs cache or status but info was sent to us by Russ Miller so think it should be set up.  @gwang.  @kkoch to set up metadata record in GN.

lon/lat,
 41° 44.58' N 83° 08.10' W   

station name,
WE13 

any id?
guess it's the same WE13

any description
GLERL Western Lake Erie Buoy Netowrk 
relevant links:
GLERL HABS and Hypoxia program page
http://www.glerl.noaa.gov/res/HABs_and_Hypoxia/rtMonWLEPreSQL.html

realtime buoy page
http://www.glerl.noaa.gov/res/HABs_and_Hypoxia/rtMonWLEPreSQL.html

**Comment by hellocomrade** [comment]
@kkoch 

You @ the wrong ID...

**Comment by kkoch** [comment]
GeoNetwork record added http://data.glos.us/metadata/srv/eng/main.home?uuid=a1742429-c80e-4870-a075-7bb8b96d95eb  > I will tweak the parameters and the obs links once I see it actually showing up in obsCache
