### ISSUE TITLE
Great Lakes cc website Issues

### ISSUE THREAD

**Issue by snehabhadbhade** [glos/myglos#260]
Aaron Thompson reported that the the glcc website is too slow. Kathy also pointed out that the site is too sluggish(it used to pretty responsive).

@Bobfrat Can you please look into this?

**Comment by snehabhadbhade** [comment]
Other Pending Issues as reported by Kathy -
Have this persistent error appearing on the dashboard underneath the message to update to WP 5.2

 

Warning: count(): Parameter must be an array or an object that implements Countable in /var/www/html/wp36/wp-content/plugins/download-monitor/includes/product/class-dlm-product-manager.php on line 137

 

2) G this error when I clicked on the ‘media’ tab >

 

Warning: A non-numeric value encountered in /var/www/html/wp36/wp-includes/ms-functions.php on line 2504

 

3) Then I would expect to see documents in the media library as the following image from my documentation shows… >

 



 

…instead I see this >

 



 

4) The user/client reports that when they attempt to upload files they get an error as follows.

 

“We are trying to upload new .csv and .txt files on the Coordinating Committee website (http://www.greatlakescc.org/wp36/wp-login.php) using an admin account.  We’ve done this in the past but this time, we are getting the error:  “Sorry, this file type is not permitted for security reasons”. However, the files I deleted were of the same file type.”

 

When I attempt the same thing I get the message >

LakeErie_HistoricalAverage_BeginningOfMonthWaterLevels_1918to2018.txt

Unable to create directory wp-content/uploads/2019/05. Is its parent directory writable by the server?

**Comment by brianmckenna** [comment]
@snehabhadbhade have them check now, we were able to upload a file successfully. We moved the upload directory off of S3 as wordpress seems to do a lot more I/O operations than one would expect to facilitate that functionality.

**Comment by kkoch** [comment]
@brianmckenna 

I just tried and still get the same error messages (I am logging in as administrator).  Note also that I don't see any media files listed:

![image](https://user-images.githubusercontent.com/6392982/57804139-f1764280-7727-11e9-8d17-ce129426c1fd.png)

**Comment by snehabhadbhade** [comment]
Issue Update from RPS - The general problem here is turning out to be ancient code long ignored, e.g. https://github.com/jeremymadea/manage-upload-types being used to define what files can be uploaded. Wordpress official docker images don’t go back far enough to use the original Wordpress version and new security features implemented by the core Wordpress team are counter to the setup passed on.At some point it may be worth looking at the hosted Wordpress options (e.g. Bluehost) to see if they support back far enough. In the meantime, we were going to follow a few of the seemingly related issues we could find to see if it resolves the upload.
Related Trac ticket: https://core.trac.wordpress.org/ticket/45615
Note - Upgrading WordPress major versions may solve this, but could potentially break other components of the system.

**Comment by snehabhadbhade** [comment]
Ben upgraded the wordpress version to 5.2! This seems to have fixed the issues with the files.
