### ISSUE TITLE
HEC Oil Spill not working

### ISSUE THREAD

**Issue by snehabhadbhade** [glos/myglos#261]
From Collin Brooks -  "I tried accessing the HECspill tool a couple more times today but I got the same "circling wheel" logo and couldn't get access to the spill modeling results."

The HEC spill tool works locally on RPS servers, but doesnt work for other users.

**Comment by ColinNBrooks** [comment]
Are other people seeing this? GLOS has water intake managers that were going to use the tool but presumably can't right now.

**Comment by snehabhadbhade** [comment]
@ColinNBrooks I am not sure about other users. I did not see any email coming to GLOS inquiring about HEC Spill tool issues. RPS is working on the issue. 
I assume you are still facing the issue of seeing the circular wheel.

**Comment by snehabhadbhade** [comment]
Colin Brooks confirmed that the tool is working fine now.
