### ISSUE TITLE
Adding collections to custom map

### ISSUE THREAD

**Issue by kkoch** [glos/myglos#35]
One does not see a "plus" sign for the ndbc buoys and co-ops (and potentially usgs stations) and only see 'add-to-map' by doing a right click hover.  Expected to see the same + to the right that you get with individual stations [at first I thought it wasn't even possible to do].

**Comment by kknee** [comment]
Not sure if there is a reason that this option is turned off. Will check in with @cgalvarino.

**Comment by kkoch** [comment]
Adding screenshot for clarification >

![plussign_coops](https://cloud.githubusercontent.com/assets/6392982/18675170/88363530-7f1f-11e6-88b8-5e9b3c0b1c54.jpg)
