### ISSUE TITLE
Adding new thumbnails to buoys (and other catalog records)

### ISSUE THREAD

**Issue by kkoch** [glos/myglos#36]
In cleaning up GN thumbnails, discovered some that aren’t showing in the portal.  Probably added after Charleton and I (Kathy) did all our back and forth in beta.

Would it work to update Charleton’s google spreadsheet (assuming it is still there and I can get to it), or is there another process (like just put the below in github for someone to take care of)? Also, need to know the process going forward.
- ESF1 > http://data.glos.us/metadata/srv/eng/resources.get?uuid=562f9b89-5232-450f-9b0f-d96cb29a5c8e&fname=ESF_1_s.png
- Bgsusd > http://data.glos.us/metadata/srv/eng/resources.get?uuid=4d80205f-433f-4b65-8d9b-34f4bec1ac04&fname=bgsusd_s.png
- ESF2 > http://data.glos.us/metadata/srv/eng/resources.get?uuid=23836466-294b-479e-bb61-151df48f44c4&fname=ESF_2_s.png
- ESF4 > http://data.glos.us/metadata/srv/eng/resources.get?uuid=beb0ae42-9c9d-44b2-a164-d004dd206661&fname=ESF4_s.png

**Comment by lukecampbell** [comment]
For MyGLOS the thumbnails should be coming from Geonetwork.

```
/gmd:MD_Metadata/gmd:identificationInfo/gmd:MD_DataIdentification/gmd:graphicOverview/gmd:MD_BrowseGraphic[gmd:fileDescription/gco:CharacterString="thumbnail"]/gmd:fileName/gco:CharacterString/text()
```

![screen shot 2016-07-26 at 9 48 31 am](https://cloud.githubusercontent.com/assets/1155163/17140349/2bededa2-5316-11e6-885d-14eab554d1d9.png)

![screen shot 2016-07-26 at 9 48 48 am](https://cloud.githubusercontent.com/assets/1155163/17140358/307dbf78-5316-11e6-8062-a9a94df1d1dd.png)

![screen shot 2016-07-26 at 9 48 53 am](https://cloud.githubusercontent.com/assets/1155163/17140364/33928d06-5316-11e6-853e-ab584f865cc6.png)

**Comment by lukecampbell** [comment]
I looked at ESF1 and ESF2, they look fine to me, are these not the images you are expecting to see?

**Comment by lukecampbell** [comment]
![screen shot 2016-07-26 at 9 51 11 am](https://cloud.githubusercontent.com/assets/1155163/17140434/7b499284-5316-11e6-996c-91e1d6316e18.png)

**Comment by kkoch** [comment]
Ah. I bet I was experiencing delay on the pics showing up and was thinking I needed to do something else. Patience is obviously something I need to work on (although I thought I waited longer than an hour - but obviously not).  All is good.
