### ISSUE TITLE
45020 GTBOSS1 buoy no data in portal

### ISSUE THREAD

**Issue by kkoch** [glos/myglos#37]
This was a buoy that previously we had as decommissioned but I noticed on NDBC site and GL Buoys that it is now transmitting data. I’ve corrected GeoNetwork but we need to look at getting data back showing in portal (no data showing in obs cache). May need to get with PI to ensure it is being entered into the new ftp site.

**Comment by everhamme** [comment]
We supported the re-deployment of this buoy.  Data is coming from the LimnoTech GLOS ftp account.. which is different that its original deployment.  Guan needs to update this.

**Comment by kknee** [comment]
can I suggest that @lukecampbell  or @cheryldmorse take a look at this with given Guan's departure

**Comment by kkoch** [comment]
fixed
