### ISSUE TITLE
Add 45175 (Mac Straits) buoy

### ISSUE THREAD

**Issue by kkoch** [glos/myglos#40]
Believe this is a glos funded buoy so should be in Portal/Obs.  

GN permalink > http://data.glos.us/metadata/srv/eng/main.home?uuid=6a0ba163-9a9e-4266-8c10-ebc25fcd84bf  (will need updating once we get into obs)

**Comment by kknee** [comment]
45175 is in the portal and pop-up correctly displays no results at the moment because there's no data in obs cache.  @kkoch @tslawecki who do you want to tackle the obs cache piece?

**Comment by kkoch** [comment]
Guan says there is a bug. Seems a bit odd that we would see a bug between ndbc data and ours since we do this all the time (see below), but I'm sure I don't really understand the issue. (To answer you @kknee it is Tad's call but I'd like to see more ASA involvement).
Following is Guan's last email on this >
"OK, took a look on 45175 and 45176.
Obs explorer API provides 45176 data without any issue, but 45175 is not properly served. The bug occurs if both of the two conditions are met:
1. Data are submitted to both NDBC and GLOS;
2. The same data arrives at NDBC first and arrives at GLOS in a "delay" mode. For 45175, there is a 40 minutes lag on GLOS side. Since the last update timestamp is updated using NDBC feed, request on 45175, which is under GLOS category, will return nothing."

**Comment by kkoch** [comment]
All is well in Portal.
