### ISSUE TITLE
GLENIJC - add to GLOS obs

### ISSUE THREAD

**Issue by kkoch** [glos/myglos#43]
Add to obs database and to portal the GLENIJC stations (do not know if this is a new procedure since we have been working on the netCDF files). Some of them are currently showing in portal from NDBC but I believe we want to link through to our GeoNetwork metadata.  PI contact(s) are Greg Cutrell and John Lenters at Limno.  Tad will need to advise on what the process really should be.

Spectacle Reef SRLM4 (showing NDBC feed)
Long Point LNPQ6
White Shoal WSLM4 (showing NDBC feed)
Stannard Rock STDM4 (showing NDBC feed)
Granite Island GRIM4

NOTE: I have a query in to Greg on why the two above are not showing in NDBC.

**Comment by kknee** [comment]
@tslawecki let us know if @cheryldmorse should tackle this one.

**Comment by kknee** [comment]
@cheryldmorse the plan is for you to coordinate with Greg and @kkoch to get this data into the GLOS obs cache and subsequently GN and the portal.  

at the same time we nee to document this process, including the GLOS Cookbook for PIs.

**Comment by cheryldmorse** [comment]
@kkoch  Do you have the metadata for these stations?

**Comment by kkoch** [comment]
All the metadata is on GeoNetwork.  Here are the permalinks:
Spectacle Reef SRLM4 > http://data.glos.us/metadata?uuid=10d10ee5-6bca-45cf-a140-b2ef9fea69e7
Long Point LNPQ6 > http://data.glos.us/metadata?uuid=04c0d6a5-f2ff-47c1-aeab-86f9b2be7b5c
White Shoal WSLM4 > http://data.glos.us/metadata?uuid=d1766782-a3ff-44be-a59f-296d656b6239
Stannard Rock STDM4 > http://data.glos.us/metadata?uuid=c9cf4bfb-f4f4-41f1-a748-0621723c8e21
Granite Island GRIM4 > http://data.glos.us/metadata?uuid=e5357aed-7af0-4c63-97b6-2ecde90e6a68

**Comment by kkoch** [comment]
Let me know what updating I need to do to make the magic on your end happen.

**Comment by kknee** [comment]
@kkoch the Obs Cache link in the GRIM4 GN record points to STDM4, can you take a look?

**Comment by kkoch** [comment]
Ooops. Fixed

**Comment by cheryldmorse** [comment]
@kkoch I'm getting an error now when trying to access this:  http://data.glos.us/metadata?uuid=e5357aed-7af0-4c63-97b6-2ecde90e6a68

**Comment by kkoch** [comment]
Every once in awhile GN goes rouge on me and resets the access privileges when I edit a record.  98% of the time, I can edit and it retains it's privileges but then there are those times... I usually remember to double-check but apparently did not do so when I tweaked the record the other day.  Should be okay now.

**Comment by kknee** [comment]
@cheryldmorse or @kkoch, whats the status of this issue?

**Comment by kkoch** [comment]
GRIM4 Granite Island looks good
WSLM4 White Shoal - had to fix the variables, should look good after next refresh
SLRM4 Spectacle Reef - had to fix the variables, should look good after next refresh

LNPQ6 Long Point - not showing data but does show the QA documentation link I added the other day [I see a record in obs but doesn't have variables - guessing this was one @cheryldmorse was trying to get Greg Cuttrell to fix or verify >
`{
name: "Station LNPQ6 - Long Point, MI",
lon: -80.05,
lat: 42.57,
tmin: null,
tmax: null,
abstract: "Lake Erie Evaporation and Meteorological Data from Long Point (LNPQ6)",
keywords: null,
parameters: null,
categories: null,
provider_url: "",
data_url: "http://data.glos.us/portal/getObsByPlatform.php?provider=glos&platform=Station+LNPQ6+-+Long+Point%2C+MI",
image_url: null,
source_name: null,
info_url: null
},`

STDM4 Stannard Rock - same as long point above 
`{
name: "Station STDM4 - Stannard Rock, MI",
lon: -87.23,
lat: 47.18,
tmin: null,
tmax: null,
abstract: "Lake Superior Evaporation and Meteorological Data from Stannard Rock (STDM4)",
keywords: null,
parameters: null,
categories: null,
provider_url: "",
data_url: "http://data.glos.us/portal/getObsByPlatform.php?provider=glos&platform=Station+STDM4+-+Stannard+Rock%2C+MI",
image_url: null,
source_name: null,
info_url: null
},`

So looks like Long Point and Stannard Rock are the only issues.

**Comment by cheryldmorse** [comment]
@kknee We don't have any data for LNPQ6 or STDM4 yet.  I sent an email today to the contact at GLERL  to see if he can start pushing the STDM4 data. I asked  Greg Cuttrell about LNPQ6 and he said that  the real-time data is technically Environmental and Climate Change Canada's data and he doesn't have any contact information for their data mangers.

**Comment by kkoch** [comment]
I'm also sending an email to Greg to verify since he filled out the metadata forms which if we don't have access to the data for LP then we shouldn't have it in the portal IMHO and then what is in the form is incorrect. Same for Stannard.  I also fixed the longitude in GN for Spec Reef since what he had in his form differs from obs (and it was placing the point in Lake Michigan).

**Comment by kknee** [comment]
@kkoch to follow up with @gcutrell

**Comment by kkoch** [comment]
Per Greg per Tad relying on NDBC feeds. Removed links to GN however they are still showing in Portal. Possibly needs manual RPS effort to remove?
