### ISSUE TITLE
Add 45176b to HABS

### ISSUE THREAD

**Issue by kknee** [glos/myglos#45]
@lukecampbell - if you'd prefer that @cheryldmorse take this on please reassign.

**Comment by lukecampbell** [comment]
I need information. 
- Is this already on thredds as netCDF files?
- Station Name
- Institution
- Institution logo
- Parameters
- Location (Lat/Lon as decimal degrees, not minutes/seconds)
- Institution Description

**Comment by kkoch** [comment]
Don't have the thredds answer but metadata is:

45176b
lon/lat: 41.55016 N, 81.76528 W
station name: Cleveland Crib Lake Bottom
YSI sonde is suspended ~1’ from the lake bottom. We are sending at 10 minute intervals:
• YSI sonde depth
• Temperature
•  Specific conductivity
•  DO sat
•  DO
• BGA rfu/ugl/raw
• CHL rfu/ugl/raw

parameters: [
"ysi_chlorophyll",
"ysi_blue_green_algae",
"water_conductivity"
],
contact(s): Ed Verhamme everhamme@limno.com

I will go back to Greg & Ed for Institution logo and description.

**Comment by kkoch** [comment]
Institution is LimnoTech

**Comment by kknee** [comment]
It's not in thredds yet, @cheryldmorse can you tackle that part?  You might need to ask Guan about the process that he used to get started.

**Comment by lukecampbell** [comment]
This is the one that I'll have to stagger it's location for right? Since HABS can't display two points on top of each other.

**Comment by kknee** [comment]
you got it.

**Comment by kknee** [comment]
@cheryldmorse apparently there is a script that writes data from the obs cache to netCDf that Guan used.  I'm not sure where to point you to track it down.

**Comment by tslawecki** [comment]
I've added @cheryldmorse to https://github.com/glos/glos_server_script/tree/master/habs, which has the source code. @hellocomrade should be able to tell you where to look, my first guess is on \process1 - there's a habnc executable in /usr/local/glos/habs that might be related.

**Comment by tslawecki** [comment]
Note to self. Push "Comment", not "Close and comment". Unless I actually know what I'm doing.

**Comment by hellocomrade** [comment]
@kknee 

It has been on TDS for a week. For example:
http://tds.glos.us/thredds/dodsC/glos/habs/lakes/ysi_blue_green_algae/45176b/45176b.ncml.ascii?blue_green_algae[0:1:973]

**Comment by hellocomrade** [comment]
@cheryldmorse 

I will need to push 45176b's files onto git at https://github.com/glos/glos_server_script/tree/master/habs

**Comment by hellocomrade** [comment]
@kknee 

I never read from obscache. habs2nc is the code base I use. It's a revision from obs2nodc.

**Comment by hellocomrade** [comment]
@lukecampbell, @tslawecki, @kknee 

I don't think you have to swift the location for 45176b on Habs viewer since 45176 is definitely not on Habs.

This is actually a "mistake" to split 45176 between "regular" NDBC recognizable measurements and HABs specific. NDBC's script can discard unrecognized tags.

**Comment by cheryldmorse** [comment]
This buoy is already on TDS.

**Comment by lukecampbell** [comment]
The rest of the task is for me to add it to the habs portal
