### ISSUE TITLE
Add 45173 (Munising) buoy

### ISSUE THREAD

**Issue by kkoch** [glos/myglos#48]
Not sure how I missed this all these months, but we also are not seeing the Munising buoy 45173 in the portal.  I've added preliminary links to GeoNetwork, but will need to know the exact Obs title and parameters once we get that added.  The data provider should be Greg Cuttrell here at Limno so let me know if there needs to be some back and forth to get data into the ftp folder.

GN permalink > http://data.glos.us/metadata?uuid=4cbfa856-ea71-4d51-be58-a0ce07e28c0f (will need updating once we get into obs)

**Comment by kkoch** [comment]
I've been informed this buoy has been recovered for the season. We can postpone until spring.

**Comment by kkoch** [comment]
Not getting obs data from PI.  Need to investigate.

**Comment by kkoch** [comment]
@gcutrell can you check on why we wouldn't be getting data into obs?  I believe Ed said you were the "PI" for this one

**Comment by gcutrell** [comment]
45173 is not deployed right now.

**Comment by kkoch** [comment]
Okay. I'm putting the notice in that it is out of the water. Let me know when (if) it is deployed.

**Comment by kknee** [comment]
@kkoch since there is no issue specific to this buoy i'm going to close this.

**Comment by kkoch** [comment]
This was originally closed because of above comment that there was no data coming from this buoy.  However, looks like we should revisit even if we are just showing for purposes of glbuoys that this is a valid buoy in the system for TDS etc.  There is a GN record for this and does show minimal record in the Portal > http://data.glos.us/metadata/srv/eng/main.home?uuid=4cbfa856-ea71-4d51-be58-a0ce07e28c0f

**Comment by gcutrell** [comment]
@kkoch Data is available in the glos_obs database. @cheryldmorse Can y'all add 45173 to the list of stations on thredds -> buoys?
