### ISSUE TITLE
Add descriptive metadata to portal for GOOGLE search summary

### ISSUE THREAD

**Issue by kkoch** [glos/myglos#51]
Right now a Google Search is displaying a description of the leash buoy in the catalog.  Which is somewhat odd since that isn't even the first buoy in the list.

> GLOS Data Portal
> portal.glos.us/
> A YSI EXO2 sonde is installed in the raw water intake pipe at the water treatment plant operated by Aqua America in Ashtabula, Ohio. The sensor is located ...

I looked at the page source and do see a tag for description which just reads "oceansmap".  I also read Google's information regarding summary snippets and they say that if the description is not descriptive enough they will pull text from the page.  I think that is what is happening here.

I believe we need to add a better metatag for description.  Something similar to >
`<meta name="Description" content="The GLOS Data Portal provides access to near-realtime and archived observations and to model forecasts for the Great Lakes.">`

This will definitely go far to aid users who find the portal by search.

**Comment by kkoch** [comment]
We need to change this line (or add an additional line) in the html code for the site:

<meta name="description" content="OceansMap">

...to something similar to what we have on HABs…

<meta name="description" content="The HABs Data Portal provides access to real-time data from stations around the Western Lake Erie Basin, including measurements of temperature, specific conductivity, turbidity, pH, chlorophyll and blue green algae.">

Suggest something like:  The GLOS Data Portal provides access to near-realtime and archived observations and to model forecasts for the Great Lakes region. Data is provided by the Great Lakes Observing System (GLOS) partners.

**Comment by kkoch** [comment]
![image](https://cloud.githubusercontent.com/assets/6392982/22379074/cc981876-e485-11e6-9054-0a19418aac2d.png)

Looks like this is done thus I'm closing.

**Comment by kkoch** [comment]
Partly done.  At least the old portal is showing something useful.  The new portal has changed from the YSI Sonde text, but is still showing HABs info.

![image](https://cloud.githubusercontent.com/assets/6392982/22379145/2030e404-e486-11e6-8c6a-4b4e7dc755f3.png)

**Comment by kkoch** [comment]
Keywords: 
observations
point observations
satellite observations
model forecasts
model forecasting
nowcasting
nowcasts
forecasts
models
computer models
winds
waves
water temperature
water surface temperature
water level
air temperature
dissolved oxygen
streamflow
turbidity
base reflectivity
chlorophyll
colored dissolved organic matter
cdom
dissolved organic carbon
natural color 
suspended minerals
water surface temperature
currents
ice thickness
data portal
decision support
great lakes
lake superior
lake huron
lake ontario
lake michigan
lake erie
maumee river
beach health
buoy
weather station
climatology
harmful algal blooms
habs
nearshore
water quality
nutrients
nutrient load
hydrology
hydrologic
sonde
oceanographic data
environment
environmental assessment
glider
optical properties
thermistor
predictions
eddy covariance
watershed
modis
stream gage
stream gauge
stressors
moderate resolution imaging spectroradiometer
remote sensing

**Comment by lukecampbell** [comment]
Ok, I implemented this and it's available on DEV.
