### ISSUE TITLE
Fix Google Analytics tracking

### ISSUE THREAD

**Issue by kkoch** [glos/myglos#52]
GLOS is only seeing 9 hits for Portal traffic for last month.  (Not sure if this is a Charlton fix or not, but tagging him as assignee for now since that's who I have in my notes as having the responsibility).  Please feel free to re-assign as appropriate.)

I do not see GA code in the page source on Production portal. However I do see it on DEV as follows (which I assume is where the 9 hits is coming from.  Also do not know if it being in DEV will automatically make it appear in Production once we push the upcoming changes.  If so, please comment to that effect.

```
<div id="google-tag-manager-view" data-google_tag_manager_id="GTM-W3GV39">
</div>
<div id="google-analytics-view" data-google_analytics_id="UA-16070728-1">
</div>
```

**Comment by kkoch** [comment]
Intel from Devra >

I'd imagine the reason the analytics code has been in testing on dev.oceansmap.com/myglos and not up on the live http://portal.glos.us yet is that it has 2 complicated factors:
1) The default Google Tags Manager event tracking doesn't actually capture events tracking for this product the way it does for, say, internal files like .pdf's. So Charlton had to add custom event tracking coding to actually capture the events flow of how people use the product.

2) Because this product is also being used by ASA for traffic coming from ASA, Charlton also had some experimenting to do with isolating stats from this audience--I suspect from referral source, but possibly using cookies or other forms of tracking.
Worth testing, for sure. It looks likely that this will be going live tomorrow or soon after.

**Comment by kknee** [comment]
@kkoch if you can give us the thumbs up that dev looks okay to push to production (generally, not the GA stuff specifically) we'll release on Monday.

**Comment by kkoch** [comment]
Sent you an email. Some concerns about MTRI but since that is a production issue as well, doesn't preclude the push to production IMHO.  And my comment about the checkboxes is also minor.  Don't see any reason why you can't move forward.

**Comment by kknee** [comment]
Analytics went live this morning
