### ISSUE TITLE
MTRI Satellite metadata (abstracts)

### ISSUE THREAD

**Issue by kkoch** [glos/myglos#53]
Suggested titles and abstracts for MTRI satellite mapping (from old portal):

• Cdom 

Title: Colored dissolved organic matter (absorption/m @ 443nm)

Abstract: Water Color of inland and coastal zones results mainly from three different parameters known as color-producing agents (CPAs). Colored Dissolved Organic Material (CDOM) is the optically measurable component of the dissolved organic carbon in water and is naturally occurring due to decaying plant matter and micro-organism metabolism. CDOM is highly absorbent of blue light which results in a yellow-brown color. CDOM is typically delivered to large aquatic ecosystems via river discharge. For more information, please visit www.mtri.org and www.greatlakesremotesensing.org - data are provided by the Michigan Tech Research Institute (MTRI). Or visit the GLOS projects page for more information.

• Chlorophyll

Title: Chlorophyll concentration (ug/L)

Abstract: Water Color of inland and coastal zones results mainly from three different parameters known as color-producing agents (CPAs). Chlorophyll (Chl) is a green pigment found in plant and phytoplankton cells. Algal cells that are suspended in water produce a green-yellow color. For more information, please visit www.mtri.org and www.greatlakesremotesensing.org - data are provided by the Michigan Tech Research Institute (MTRI). Or visit the GLOS projects page for more information.

• Doc

Title: Dissolved organic carbon (mgC/L)

Abstract: Water Color of inland and coastal zones results mainly from three different parameters known as color-producing agents (CPAs). Dissolved Organic Carbon (DOC) is a form of organic carbon that is produced during micro-organism metabolism and may also be transported from decaying vegetation via rivers and streams. DOC only absorbs light, it does not scatter light, and appears yellow to brown in color. A significant fraction of the total DOC concentration is invisible and must be estimated empirically from the colored portion known as Colored Dissolved Organic Carbon (CDOM). For more information, please visit www.mtri.org and www.greatlakesremotesensing.org - data are provided by the Michigan Tech Research Institute (MTRI). Or visit the GLOS projects page for more information.

• Lake Surface Temperature

Title: Water surface temperature (deg F)

Abstract: These data represent night-time temperature data derived from 250-meter resolution MODIS satellite imagery, collected at the 4-micron wavelength when cloud cover is not significant. Previous analysis has shown these data to be accurate within approximately 1/2 degree Celsius. For more information, please visit www.mtri.org and www.greatlakesremotesensing.org - data are provided by the Michigan Tech Research Institute (MTRI). Or visit the GLOS projects page for more information.

• Natural Color Imagery

Title: Natural Color

Abstract: Water Color of inland and coastal zones results mainly from three different parameters known as color-producing agents (CPAs). Collected by the MODIS satellite sensor, these natural color images are produced using the Red, Green, and Blue channels at a spatial resolution of 1 kilometer. For more information, please visit www.mtri.org and www.greatlakesremotesensing.org - data are provided by the Michigan Tech Research Institute (MTRI). Or visit the GLOS projects page for more information.

• Suspended Minerals

Title: Suspended minerals (mg/L)

Abstract: Water Color of inland and coastal zones results mainly from three different parameters known as color-producing agents (CPAs). Suspended Minerals (SM) consist of inorganic particulate matter (such as sand, silt, and clay), which scatter and absorb light. For more information, please visit www.mtri.org and www.greatlakesremotesensing.org - data are provided by the Michigan Tech Research Institute (MTRI). Or visit the GLOS projects page for more information.

**Comment by kknee** [comment]
@kkoch just realized that we don't break down these layers by variable in the catalog anymore.  How should we proceed with metadata in that case:

![image](https://cloud.githubusercontent.com/assets/196868/22256191/05eaafea-e228-11e6-92f8-1eab1a0373f2.png)

**Comment by kkoch** [comment]
Colin approved >

Title:  
MTRI Great Lakes Remote Sensing Products: Lake [insert lake name here]

Abstract:
Mapping of remote sensing products for Lake [insert lake name here]. Imagery is provided for colored dissolved organic material (CDOM), chlorophyll (Chl), dissolved organic carbon (DOC), lake surface temperature, natural color imagery, and suspended minerals. Note that satellite data is generally unavailable from early November to late March due to cloud cover. These data are provided by the Michigan Tech Research Institute (MTRI) http://www.mtri.org.

Keywords: 
chlorophyll
chl
organic carbon
water quality
great lakes
modis
mtri
satellite
suspended minerals
colored dissolved organic matter
cdom
doc
lake surface temperature
natural color imagery
natural color
color producing agents
cpas

**Comment by kknee** [comment]
@kkoch the above are showing up as a separate set of records in GN and thus we have two records for each lake in OceansMap: we need to combine/sync:

![image](https://cloud.githubusercontent.com/assets/196868/26260314/bcd90cca-3c9a-11e7-8cea-a779510fa01c.png)

**Comment by kkoch** [comment]
GN changes have been made for awhile.  Needs RPS to remove from catalog.

**Comment by kknee** [comment]
@kkoch looks like we're good on the number of records in the portal, but still no abstracts.  Can you point me to exactly which records in GN we should be pulling from for the abstracts?  it wasn't obvious when I was poking around.

**Comment by kkoch** [comment]
@kknee @cheryldmorse We weren't pullling from GN for abstracts.  See above Apr 18 comment for text.

**Comment by kkoch** [comment]
Just noticed that the abstracts for this manually curated data set still not showing in portal (brought to my attention by Colin). Can we get this done please @cheryldmorse @Bobfrat 

Again reminder that the text that I'd suggested originally is in the first comment of this ticket/issue.

**Comment by kkoch** [comment]
Comment from Colin at MTRI >

I was reminded in poking around the portal yesterday that the MTRI Great Lakes remote sensing products just have "MTRI Great Lakes Remote Sensing Products: Lake [name]" as their description when you display them in the Catalog or Map version. In the original way of accessing them, they had a slightly longer description that helped describe them as a group. I can't find the exact wording, but it was close to this description we sent as part of a "Data conversion & metadata application methods" document back in 2014, that I'm updating slightly:

"The Chlorophyll, CDOM, DOC, and Suspended MInerals remote sensing derived products are created using the Color Producing Agent Algorithm (CPA-A) described in Shuchman et al. 2013 and Shuchman et al. 2006. The Lake Surface Temperature and Natural Color Imagery products are based on available MODIS products, but made available for the Great Lakes region. They all generally processed approximately once a week during the relatively 'cloud free' Great Lakes season (approximately mid-April to mid-October each year) and shared via ftp and WMS with the GLOS DMAC team and GLOS community."

Can we make it so that appears as the layer description, in addition to the basic "MTRI Great Lakes Remote Sensing Products: Lake [name]" text?

**Comment by Bobfrat** [comment]
@kkoch can we shorten the title from the suggested one:
```
Colin approved >

Title:
MTRI Great Lakes Remote Sensing Products: Lake [insert lake name here]
```

<img width="313" alt="screen shot 2017-08-09 at 10 43 36 am" src="https://user-images.githubusercontent.com/5702672/29127672-c1405116-7cef-11e7-92d1-c0fae16096b5.png">

Or maybe put the lake first? 'Lake [insert lake name here]: MTRI Great Lakes Remote Sensing Products'

**Comment by Bobfrat** [comment]
@kkoch any thoughts on the title? Things are looking pretty good other than that.

**Comment by kkoch** [comment]
Sorry I was on vacation.  

Colin (MTRI) let me know that he likes >

cdom @ MTRI Lake Superior

The problem with that is that the parameters don't show up until you click on the item as a pop-up which I get the impression he does not like.  But then it gets pretty ugly to have each of the parameters listed in a long list for each lake.  So I'm pushing back on that . I'll let you know.  

As a side question or thought, is it possible to get the parameter list on a hover rather than a click?

**Comment by Bobfrat** [comment]
@kkoch I'm not sure if thats possible because the parameter list would show on hover, but when you move your mouse towards the popup to add a parameter to the map, the window would disappear so you wouldn't be able to select anything.

**Comment by kkoch** [comment]
@Bobfrat No worries on the pop-up - just thought I'd ask.

Colin has approved the following for the titles:

MTRI Remote Sensing Lake [name]

>>  MTRI Remote Sensing Lake Superior

**Comment by Bobfrat** [comment]
@kkoch Metadata is updated but the layers are not showing. I'll check if this issue is on my end

**Comment by kkoch** [comment]
@Bobfrat  I see layers (random check of some parameters) but the boxes around the lakes don't seem quite right.  Also Lake Michigan is only showing the top half of the lake which is an even bigger issue.

**Comment by Bobfrat** [comment]
@kkoch We're getting the bounding box info from the GetCaps request. http://spatial.mtri.org/cgi-bin/mapserv?REQUEST=GetCapabilities&SERVICE=WMS&map=watersensing_map&version=1.1.1
