### ISSUE TITLE
GLEAM pop-up box pushes map off screen

### ISSUE THREAD

**Issue by kkoch** [glos/myglos#54]
The pop-up with all the child records currently pushes the map off screen (down).  Suggest that it be a scrollable box or be positioned to the side instead of top.  Kelly noted that they’ve been wanting to make the boxes scrollable anyway so that might be the easier of the two options.

![gleam_childrecords](https://cloud.githubusercontent.com/assets/6392982/18675739/54fa788c-7f21-11e6-8714-2d0eae04f827.PNG)

**Comment by kknee** [comment]
fixed by adding scroll bar
