### ISSUE TITLE
GLEAM website deployment

### ISSUE THREAD

**Issue by kkoch** [glos/myglos#56]
Need to have a landing place (server location) for GLEAM. 

Message sent to Guan on 9/8. No reply to Kathy but he may have talked with Tad (?). 

> Before  you left, we'd talked about setting up a data.glos.us/gleam website.   If you recall, we'd originally thought we wanted WordPress, but I'm thinking straight html would be better for me at this point.   We are moving forward on that and Tad wanted me to ask your opinion (you don't need to do anything at this point) > what glos server would be the best to put the website on?  Would it be the same vm that GeoNetwork is on or should it be the one that the current WordPress and Drupal one is on, or is there a better one for load balancing (or other reasons)?

**Comment by kkoch** [comment]
For now am creating a sub-directory on 64.9.208.36 in the data.glos directory called 'gleam'.  We can always move it later if needed.

**Comment by kkoch** [comment]
@lukecampbell 
Here’s what I think I need
• A production landing place for the gleam website/html and a proxy redirect (reverse proxy?) so that data.glos.us/gleam functions for the user
• Ability to sftp files easily (I usually use winSCP and/or dreamweaver) for both the initial setup and subsequent changes
• If I am not able to sftp to the production landing spot, then I also need a dev URL where I can sftp files and also view them via browser to test before moving to production (see note below)
• And if we have both a dev and a production site, then we will need to figure out a procedure to push to production when changes are made

Note: If ‘dev’ is okay where it lives now on 64.9.208.36, since I can easily access and sftp there, I need to have a way to view the files in a browser.  Nothing I’ve tried seems to work for that. But always possible/likely there is some user error going on there.

**Comment by kknee** [comment]
from @lukecampbell on 1/19:

http://data.glos.us/gleam/

As far as setting up a dev site, that needs to fall onto the network administrator to find or register a domain for testing, open up the port and if you guys need my help after that I can help set up Apache to host content on that port.
