### ISSUE TITLE
Suppress ndbc feed for GLOS supported buoys

### ISSUE THREAD

**Issue by kkoch** [glos/myglos#57]
45161 is showing both NDBC and ‘our’ feed.  Should the NDBC be suppressed?

![45161](https://cloud.githubusercontent.com/assets/6392982/18713785/8639e034-7fe1-11e6-9c1d-a6fea9b3b9d8.PNG)

**Comment by kkoch** [comment]
Looks like other buoys are now showing ndbc feeds that were not before as well.  Listed below are the ones I've come across >

45026
45028
45161
45171

**Comment by kkoch** [comment]
Bumping this up to be worked on for new buoy season (buoy does appear back in water).

**Comment by kkoch** [comment]
Actually I just started checking and somehow most of the GLOS buoys are now not being suppressed (originally it was just the 4 in the original title of this issue ticket), so something got changed to un-suppress the others.  This means that if someone searches in the catalog for a buoy that we have a GN record on, they see two hits and of course they aren't going to understand why.

Basically anything we pull from GN into the portal needs to not also get an ndbc hit when someone searches)

@cheryldmorse what needs to be done to get this taken care of?  Is this something @Bobfrat could easily do?

**Comment by Bobfrat** [comment]
@kkoch i can add a blacklist when we're collecting the NDBC stations in the Great Lakes.

**Comment by kkoch** [comment]
@Bobfrat   just updated my comment above.  Somehow I think our blacklist has stopped working as most of the GLOS buoys are now showing double records.  Do you need a full list?

**Comment by Bobfrat** [comment]
yes please

**Comment by kkoch** [comment]
45013, 45014, 45020, 45022, 45023, 45024, 45025, 45026, 45027, 45028, 45029, 45161, 45162, 45163, 45164, 45165, 45167, 45168, 45169, 45170, 45171, 45172, 45173, 45174, 45175, 45176

**Comment by everhamme** [comment]
What about 45164?



Ed Verhamme
Project Engineer
LimnoTech www.limno.com
Ph: (734) 332-1200<tel:(734)%20332-1200>
Direct/Cell:  (734) 681-0577<tel:(734)%20681-0577>
everhamme@limno.com<mailto:everhamme@limno.com>


-------- Original message --------

**Comment by kkoch** [comment]
@everhamme typo, fixed

**Comment by Bobfrat** [comment]
@kkoch I removed those stations from the NDBC feed.

**Comment by kkoch** [comment]
Looks good. Closing and thanks.
