### ISSUE TITLE
Permalink lost its data

### ISSUE THREAD

**Issue by kkoch** [glos/myglos#58]
My permalink to all the GLOS buoys is no longer working - shows a link in my list but there are no buoys listed below or in the map >

http://portal.glos.us:/?map=cURYbFNEc0hSOXFSLUVURzNwN3BzZzpHTE9TIEJ1b3lz&name=GLOS%20Buoys

This concerns me on several levels in addition to the time spent to build the link:

• I’ve given this link to several people to ease their angst about not seeing buoys when they open the map
• I am in the process of building even uglier links for the GLEAM website and now am really concerned that I am creating them and then to have them go away

NOTE: I know the link was working on Sept 8 because that is the last time I went to grab it to give to Becky.

It doesn’t look like any of the other links I’ve built are gone (other links I built at the same time are one to just CILER buoys, one to “all” buoys and a couple more).

**Comment by kkoch** [comment]
I've rebuilt the link.  Luke looked into this but not sure why it occurred and hoping it was a momentary network error/glitch. Do we want to close for now as unresolved but we can re-open if it happens again?

**Comment by lukecampbell** [comment]
I'll just knock off the high priority. it's still a bug and I don't feel any closure with this since we couldn't find any evidence or information as to what happened. And that worries me.

**Comment by kkoch** [comment]
Just lost all my gleam permalinks.  They still appear in my saved collection but don't do anything.  This is pretty major since that is what I'm using for the website.

Example permalinks:
http://portal.glos.us:/?map=cURYbFNEc0hSOXFSLUVURzNwN3BzZzpnbGVhbQ%3D%3D&name=gleam

http://portal.glos.us:/?map=cURYbFNEc0hSOXFSLUVURzNwN3BzZzpHTEVBTSAtIEFxdWFjdWx0dXJl&name=GLEAM%20-%20Aquaculture

![gleam_permalinks](https://cloud.githubusercontent.com/assets/6392982/19486828/ef4032d4-952d-11e6-8c4a-9da133138261.PNG)

**Comment by kkoch** [comment]
In order to test I have created a new myglos account (dmac2017) to see if the issue is attached to my account instead of an inherent issue in the programming behind permalinks.  I  have added in all the gleam records as saved collections.

**Comment by kkoch** [comment]
Links have disappeared again:

My main one for GLEAM is still there (http://portal.glos.us:/?map=MzkyNTljMjYtNjIxMS00ZThlLTk4YzMtMTczOTdkMTYxNmIyOkdMRUFNIC0gQWxs&name=GLEAM%20-%20All) , as are all my buoy ones, but all the  secondary GLEAM links I'd set up seem to have gone.  

Example: GLEAM - Aquaculture
http://portal.glos.us:/?map=MzkyNTljMjYtNjIxMS00ZThlLTk4YzMtMTczOTdkMTYxNmIyOkdMRUFNIC0gQXF1YWN1bHR1cmU%3D&name=GLEAM%20-%20Aquaculture

![image](https://cloud.githubusercontent.com/assets/6392982/25436590/b9579616-2a61-11e7-8d58-89bf0ab5d18e.png)

Created a new one aquaculture one today so you can see what it 'should' look like >
http://portal.glos.us:/?map=MzkyNTljMjYtNjIxMS00ZThlLTk4YzMtMTczOTdkMTYxNmIyOkdMRUFNIC0gQXF1YWN1bHR1cmUgVEVTVDA0MjcxNw%3D%3D&name=GLEAM%20-%20Aquaculture%20TEST042717
![image](https://cloud.githubusercontent.com/assets/6392982/25437273/cd8b3780-2a63-11e7-9bf6-59ddba68cb41.png)

**Comment by kkoch** [comment]
And it gets more fun.  Sent to co-worker a permalink that should work (the one to the main GLEAM record - "GLEAM - all") - which is showing in my collections list > 

http://portal.glos.us:/?map=MzkyNTljMjYtNjIxMS00ZThlLTk4YzMtMTczOTdkMTYxNmIyOkdMRUFNIC0gQWxs&name=GLEAM%20-%20All

He reported back to me that it didn't work.  

Sure enough I tested using FF, IE and Chrome.  And in all browsers it just takes me to the main portal catalog homepage.  Does not even go to map, much less show the shared data even if I am still logged in.

**Comment by lukecampbell** [comment]
That's a bug that was brought up to me this morning. If you go to the map though, data should be there:

![screen shot 2017-04-28 at 4 27 09 pm](https://cloud.githubusercontent.com/assets/1155163/25546100/8c3f7e58-2c2f-11e7-8fa9-0323d6ac336e.png)

**Comment by kkoch** [comment]
Luke has pushed to production some changes including logging when a user saves a collection. 
Also added ability to export/import collections.  Will close this for now. If we have further issues will re-open.

**Comment by kkoch** [comment]
Was brought to my attention that my GLEAM permalinks are once again not working (the last time I really looked at this was in May following the server crash.  I'd rebuilt them and thought I'd done Luke's 'export' to json for all, but apparently I did not or something odd has even happened with that as I only have exports for 10 out of the 30 links (I am very puzzled about that).  There are only 12 appearing in my MyGLOS collection list - interestingly the 10 I have jsons for are among those 12.

@cheryldmorse or someone with collection expertise > Before I once again go and recreate all my permalinks and edit the website, can you see if programmatically you can get them back again?  The account would be kkoch@limno.com

These are the ones that are still in my account >
![image](https://user-images.githubusercontent.com/6392982/29372587-91e11aec-8279-11e7-9727-e4a8212437ff.png)
![image](https://user-images.githubusercontent.com/6392982/29371698-0e10ccb4-8277-11e7-9fc6-32c42f92bc91.png)

**Comment by Bobfrat** [comment]
@kkoch I think its safe to say any tasks that would have gone to Luke are now my responsibility.

I think I recall Luke discussing this issue before but I'm afraid I'm not sure what it means to programmatically get your permalinks back. Do you have any other info (emails?) detailing what Luke did for you last time? I'll search any resources and pull requests on my end as well. My email is robert.fratantonio at rpsgroup dot com

**Comment by kkoch** [comment]
Status: I have recreated all the permalinks yet again. I have exported all the jsons (34) and verified that they are there and valid.  I have updated the GLEAM website with the new urls and they are all working as of 11:00am today.
