### ISSUE TITLE
Obs displaying knots and degC

### ISSUE THREAD

**Issue by kkoch** [glos/myglos#59]
Portal displaying knots and degC.  

1) knots - we'd had discussions via emails that there was confusion about what is in obs and thought we'd fixed that and decided on mph and haven't really been paying attention so don't know if that was ever resolved or if we just stuck with knots.

2) I am pretty sure it was displaying degF - not sure when it started showing in C although I'm sure our Canadian folks love that.

I am submitting two tickets on this.   This one is this to see if we can go to English units, but will submit a 2nd issue to look into the possibility of having a toggle to switch back and forth for users.

**Comment by kknee** [comment]
This likely got fixed as a results of routine OceansMap updates.  We did not apply a specific change here.
It is worth noting that OceansMap will have the option to switch between metric and english units very soon.
