### ISSUE TITLE
Additional Variables for GLEAM

### ISSUE THREAD

**Issue by kknee** [glos/myglos#6]
1. Combine the individual maps into a single netCDF file with a single catalog entry - @kkoch will let Sigrid know that we need the files in ARCGRID format.  Tad will then have Brian Lord (Limno) convert them into netCDF files.
2. Review legends
3. Combine metadata - use child records in GN

**Comment by kkoch** [comment]
1. Sigrid has been notified re: ARCGRID. She is on travel and will do so when she returns. (kkoch)
2. GN Child record creation in process (kkoch)

**Comment by lukecampbell** [comment]
Are these still regular grid with an EPSG:4326 projection?

**Comment by kknee** [comment]
That's the plan.  We haven't see the updated netCDF yet.

**Comment by kkoch** [comment]
I just sent another email to Sigrid asking her for status on the netcdf files.

**Comment by kkoch** [comment]
Sigrid has put arcgrid and her netcdf files on the limno share.  @tslawecki is on tap for next task.

**Comment by kkoch** [comment]
34 Child Records have been added to GN. Permalink to main record for metadata which should display the child records for users > http://data.glos.us/metadata/srv/eng/main.home?uuid=b47fa3c1-4222-46b1-bc61-7b0138105e58

**Comment by kknee** [comment]
from Tad:

I used NCO ncks to append all of the GLEAM files together, and placed the result at:

https://limno.sharefile.com/d-sbd1105eb0f747a8b

Please check it out and let me know if it works.

**Comment by kknee** [comment]
@lukecampbell reports that the file looks good.  @tslawecki next step to replace what we have in the portal?

**Comment by tslawecki** [comment]
Here's what I want to be able to do:
- Search for a stressor variable in the catalog - e.g. shore hardening. It looks for right now like there is only the combined stressors in the portal catalog, though @kkoch has shown me individual stressors in GN.
- From the record, preview or view on map - show that variable as any other grid.

Separately, I'd like to have a pre-made map (permalink?) with all of the GLEAM variables in it. This would be linked to from the new data.glos.us/GLEAM pages

BTW, @hellocomrade, any quick comments on where we should add these new pages, and the process for adding to DNS? Or is this something straightforward enough for RPS to just make happen?

**Comment by kkoch** [comment]
WMS link has been removed from GeoNetwork so we should no longer see two records in place once the server refreshes data.  Also I will take the action item to create a permalink to use for the website and others once we push the dev site to production.

Luke: how would you suggest being able to search for the child record data as Tad requests?  If we were still pulling from GN, I would put them in the GLOS keywords, but since this is now one of 'your' records, guess I need to pass the buck to you.

**Comment by lukecampbell** [comment]
if you put a list of keywords here, I can add them to the record.

**Comment by kkoch** [comment]
Here you go. Let me know if you need the titles split out from other keywords.

Keywords

environmental impacts, stress, phosphorus, Great Lakes, Laurentian Great Lakes, Lake Huron, Lake Erie, Lake Superior, Lake Michigan, Lake Ontario, Laurentian Great Lakes, Great Lakes, GLEAM, stress, impact, environment, Phosphorus Loading, non-point pollution, models, invasive species, ballast water, models, Ballast Water Invasion Risk, Changing Water Levels, lake levels, sea level change, climate change impact assessment models, Combined Sewer Overflows, CSOs, CSO, nonpoint pollution, non-point pollution, water quality, Aquaculture, fisheries, Areas of Concern, AOCs, toxicity levels, toxic chemicals, AOC, Copper, Commercial Fishing, Zebra and Quagga Mussels, zebra mussels, quagga mussels, Coastal Mining, coastal areas, mining, coastal development, Coastal Power Plants, coal production/use, oil production/use, natural gas production/use, nuclear energy production/use, biomass energy production/use, coal production, oil production, natural gas production, nuclear energy production, power plants, Dams, Recreational Fishing (Charter), recreational activites/areas, recreational fishing, charter fishing, Coastal Road Density, Developed Land, Non-Native Fish Stocking, fish, Nitrogen Loading, nitrogen, nitrate, nitrite, cyanobacteria, blue-green algae, HABs, Hypoxia, dissolved oxygen, Light Pollution, Native Fish Stocking, Industrial Ports and Harbors, harbors, industrial ports, ports, Marinas, pollution, chemical spills, Mercury, Phragmites, weeds, noxious plants, invasive plants, Sea Lamprey, Shoreline Hardening, Suspended Sediments, sediments, turbidity, suspended solids, PCBs, polychlorinated biphenyl compounds, organochlorines, Coastal Recreational Use, environment, Round Gobies, round goby, Reduced Duration of Winter Ice Cover, ice cover, climate change, Shipping Lanes, shipping, Shoreline Extensions, breakwaters, jetties, docks, Warming Water Temperatures, water temperature, Cumulative Stress

Categories

models, HABs, nutrients, water_quality, environmental, climatology, temperature, beach_health, nearshore

**Comment by kkoch** [comment]
Also, still seeing two records on portal even though I have removed links from GN.  So must be something that needs to be removed on ASA side.

**Comment by lukecampbell** [comment]
Right, I have to force clean the catalog for it to remove old records.. I'm making the metadata changes as I type this, once I update the catalog and test it locally, I'll update it on Production with the changes and do a force-clean.

**Comment by lukecampbell** [comment]
http://myglos.asa.rocks/ is all set, do you want to take a look at that to see if it jives with the metadata?

**Comment by kkoch** [comment]
Sorry somehow I missed your comment.  Yes while I didn't search for every keyword, everything I did try came up and I only see the one record with all it's child records.  How soon can we push to production?

**Comment by lukecampbell** [comment]
Monday at the earliest.
