### ISSUE TITLE
Update hover text

### ISSUE THREAD

**Issue by kkoch** [glos/myglos#61]
Need to clarify hover text for the following:

1) Hover for Graph parameters reads: "Create a timeseries parameters graph".  Suggest changing this to: "Click on a parameter checkbox to create a timeseries/parameters graph"

2) Hover for Buoys & Station Obs in sidebar reads "Buoys &amp; Station Obs".  Need to change the &amp; to just an &.

3) Hover for Enter Buoy Virtual Creation Mode reads: "Toggle virtual buoy creation mode". Suggest changing to "Log in to your MyGLOS account to enable access to virtual buoy creation mode" or "Toggle virtual buoy creation mode. Requires logging in to MyGLOS account."

**Comment by kknee** [comment]
1 - but what if they already have parameters checked?
2 - I'm not clear on this one
3 -virtual buoy mode does not require a myGLOS account.

**Comment by kknee** [comment]
@kkoch for no. 1, how about "create a timeseries plot of selected parameters"

**Comment by kkoch** [comment]
3 - okay it wasn't working the other day then but does seem to be today (and I just thought oh maybe I need to be logged in).  So scratch that request.

2 - ah because github changed my code to the appropriate text. Let's try this. Hover for Buoys & Station Obs in sidebar reads "Buoys `&amp;` Station Obs". Need to change the `&amp;` to just an &.

1 - I don't think it will matter if they have them checked already as it is an instruction text.

**Comment by kkoch** [comment]
And yes your suggestion for text on #1 is a good compromise
