### ISSUE TITLE
MyGLOS Message sending failures

### ISSUE THREAD

**Issue by beckypearson** [glos/myglos#65]
I forgot my myGLOS password, and therefore, I requested to change it.  However, I get an error saying that my request could not be sent.  Then I tried to submit some feedback using the feedback form, and I get another error window saying that there was a problem sending your feedback message.

**Comment by lukecampbell** [comment]
This seems like a critical issue. I'm taking a look now.

**Comment by lukecampbell** [comment]
Ok, this should be fixed now. Can you try again?

**Comment by beckypearson** [comment]
I tried both features (password change request and feedback form) again.  They both work!

**Comment by lukecampbell** [comment]
The credentials for sending email through AWS was stale, I updated them to match the latest keys.
