### ISSUE TITLE
Add 45170 to portal

### ISSUE THREAD

**Issue by kkoch** [glos/myglos#67]
45170 (Indiana-Illinois Sea Grant) buoy is also not in the portal/not in obs.  May need to get with data provider (Jay Beugly maybe?) to get into ftp cache.

GN permalink > http://data.glos.us/metadata/srv/eng/main.home?uuid=dbccce4c-6b18-4f4b-b70a-ff043d37c702

Looks like this buoy is still in water and is a glos-funded buoy (and could potentially be looked for at annual meeting next week) so maybe we can get this going quickly.  Let me _Kathy_ know if we do get data in obs and I will update to add the category, variables, etc. links.

**Comment by everhamme** [comment]
This buoy isn’t GLOS funded..  we have assisted in the past with coding and have the ability to easily modify the code.  I will email about getting data sent to GLOS.

**Comment by kkoch** [comment]
Interesting - because GLOS staff this morning told me that it (along with 45174) was funded and I put it on their map for the annual meeting.

**Comment by cheryldmorse** [comment]
We are already receiving data for buoy 45170.

**Comment by kkoch** [comment]
That's good. Now we just need to make it show up in portal.  Doesn't show in obs

**Comment by cheryldmorse** [comment]
Added 45170 to the database. @kkoch here is the obs cache link: http://data.glos.us/portal/getObsByPlatform.php?provider=glos&provider=glos&platform=Illinois-Indiana+Sea+Grant+Buoy+%2845170%29+-+Michigan+City%2C+Indiana

**Comment by kkoch** [comment]
Done. Looking good!
