### ISSUE TITLE
Collections pop-up off screen

### ISSUE THREAD

**Issue by kkoch** [glos/myglos#70]
I made the mistake of updating Firefox on my laptop today to 49.0.1 and it is now doing what I believe is the same or similar behavior Tad was seeing -   I have a large amount of permalinks (maybe hit the practical limit of how many to have - problem with that is that I have more to add) and it would pop-up the list of saved datasets but it would be off the top of my screen and not allow me to get to the close box either by moving map or clicking elsewhere on the page.  Each time I would end up having to do a refresh and then rebuild my map.  And then sometimes it would reposition correctly and at least have the top of the dialog box on the screen and give me a scroll bar to the right of the full webpage.

Here is screenshot showing off the top of the page with no scroll or other way to see what is on top >
![popup](https://cloud.githubusercontent.com/assets/6392982/19196362/3ccf96b0-8c83-11e6-94ab-561f55d96c21.PNG)

And here is a screenshot after refreshing and choosing a link closer to the top of the list. This time it shows me options at the top and also gives me a scroll bar for the page so I can also see the bottom of the list.

![popup2](https://cloud.githubusercontent.com/assets/6392982/19196381/4be5acc0-8c83-11e6-9269-ce0da0b3fbf6.PNG)

**Comment by kknee** [comment]
we can solve this with a scroll bar
