### ISSUE TITLE
Click Speed Issues with Menu Items

### ISSUE THREAD

**Issue by kknee** [glos/myglos#78]
Users reporting no response when clicking on menu items.  @lukecampbell determined it might have to do with click speed.

**Comment by kkoch** [comment]
Luke has a fix on dev. Kathy will test dev and okay push to production on Friday.

**Comment by kkoch** [comment]
Tested dev.  Seems to work just fine. Okay to push to  production.

**Comment by kkoch** [comment]
Luke reported that the fix worked for the popover for "provide feedback, about and tutorial videos". But it's not working for the login popover. We'll have to create a separate fix for that popover at some point.
Production is updated.

User Doug Kane reported issue with not being able to create an account.  Kelli says this is this click speed issue.  He has managed to create an account, but obviously we still need to adjust the click issue.

**Comment by kknee** [comment]
fix is now applied for login menu.
