### ISSUE TITLE
IOOS 52NSOS update

### ISSUE THREAD

**Issue by kkoch** [glos/myglos#79]
Shane at Axiom is updating to latest version. He inquired whether we though Docker is a good idea. Luke doesn’t think the 52N server has a version of Linux that is compatible with Docker, but otherwise, up to Axiom.  NOTE: Tad wants this done so that he can take advantage of the WaterML2 capabilities for an EPA project.

**Comment by tslawecki** [comment]
Checking in with Axiom.

**Comment by tslawecki** [comment]
Also, we need to update the ServiceProvider information in 52N to match new address and phone number, so I requested credentials from Shane.

**Comment by kkoch** [comment]
@tslawecki what is the status on this one - has it been completed?

**Comment by kkoch** [comment]
Pretty sure this is done so closing.
