### ISSUE TITLE
NCEI submittals

### ISSUE THREAD

**Issue by kkoch** [glos/myglos#80]
No one on team is aware of status of NCEI but Tad hasn't received any accession numbers since July. He will check the system and see if there are issues and if so connect with Matt Biddle for next steps.

**Comment by tslawecki** [comment]
Confirmed with Matt that NCEI has not received submittals since July. @gcutrell tasked to start looking into task.

**Comment by gcutrell** [comment]
Matt confirmed that they NCEI started to ingest the new packages on 1/3/16. The bash file "jobs.sh" in /usr/local/glos/obs2nc of process1 was not running as it should be.
