### ISSUE TITLE
Add fields to user feedback form

### ISSUE THREAD

**Issue by kkoch** [glos/myglos#82]
It does not seem intuitive to users if they are having a technical issue to submit a Feedback form.  Suggesting we maybe add to the form something like a check box for 'technical issue' or 'need support' and one for 'general feedback'.    In addition we might want to rename "Feedback" to "Contact Us".

We might also want to add some contact information to the "about us" screen - or point them to Contact Us page.

The recent contact where this came up also mentioned that"the address they have listed on the GLOS website is definitely the GLERL address".  Not sure where that is or what she was looking for so there might also be something we need to make sure is available if someone does go to GLOS home.

**Comment by tslawecki** [comment]
Also, is it feasible to store a permalink and attach it to the e-mail so that we can easily reproduce the state of the portal? We might want to ask for the user's permission to do this at the time of ticket submittal.

**Comment by kknee** [comment]
Decision is to change "Provide Feedback' to "Contact Us" and then update title of feedback text box to "Provide Feedback or Report Issue"

**Comment by kkoch** [comment]
Note this was also a recommendation from the UofM student team.

**Comment by kknee** [comment]
@cgalvarino still need to update title  feedback text box to "Provide Feedback or Report Issue"

**Comment by cgalvarino** [comment]
@kknee, maybe I misunderstood.  This is what I put in place.

![snag-0000](https://cloud.githubusercontent.com/assets/180985/23171206/d9f4a8f6-f81f-11e6-8837-4bd249034e74.jpg)

**Comment by kkoch** [comment]
1) Suggest also changing form header 
from: Please provide us with some feedback.
to:   Please provide us with feedback or report an issue.

2) Suggest changing Feedback box to:
Feedback or Issue

3) Future ehancement might also be adding a checkbox for urgency (e.g., Priority (high, medium, low).

4) Also add a box for User Organization (optional)

**Comment by kkoch** [comment]
Form header, hover, and feedback box text have been updated.  

Changing this now to a lower priority 'future enhancement' label for the adding an urgency box and user organization (optional) box.

Also changed title to reflect that this is now focused on updating the database/form itself.

**Comment by Bobfrat** [comment]
Organization field should be in there. We added that recently.

**Comment by kkoch** [comment]
Ah you snuck that in on me.  Great job.
