### ISSUE TITLE
User seeing incorrect day when using MTRI model and virtual buoy

### ISSUE THREAD

**Issue by kkoch** [glos/myglos#83]
User submitted the following issue >

Thanks for your assistance guys, This might get a little convoluted, but I'll try to the best of my ability to describe a) what I'm trying to do and b) the problem I'm encountering. I actually sent some feedback through the website, so the project team may be getting this twice.

Basically, I have these 15 sites in Western Lake Erie that I've been conducting some research on and I'm interested to see how surface chlorophyll a levels change throughout a bloom season (~May-September). With the exception of 4 locations, there are no pre-existing buoys/monitoring stations in these locations, which is why I want to use the virtual buoys. My original game plan was to drop virtual buoys approximately where those sites are located and then I was going to record the weekly changes in surface chlorophyll at those locations based on the MTRI Lake Erie layer (i.e. record the chlorophyll levels for 5/9/16, 5/16/16, 5/23/16, etc). I've attached a couple of screenshots here for reference, but here's what's happening when I try this: When I first enter the map, I add the MTRI Lake Erie Layer and I drop a virtual buoy in. I always get a reading when I drop the buoy in the first time (I think the default date it lands on is October 7th, with a chlorophyll reading of 43.24 ug/L; see the first attached image). However, when I try to change the time range to a week in a prior month, such as August or July, the MTRI layer updates to reflect the new date range, but the virtual buoy window suddenly jumps to whatever the current ACTUAL day is (in this case, 10/26/2016) and shows no reading (see the second attached image). I tried increasing the date range and trying different months and, while the MTRI layer updates, the data for the virtual buoy won't update. I've played around a little bit and if I toggle back and forth between the map and catalog view and drop a new buoy, then the new buoy will sometimes show the new week I changed it to (September or July or whatever), but the buoys I dropped previously still don't update. So I know there's data THERE, but the virtual buoy won't reflect it. I'm only just now using the data portal for the first time, so it's completely possible I'm just hitting the wrong buttons or something silly like that, but I feel like I've tried all kinds of things at this point and I'm not having much luck.

I appreciate any help and let me know if you need any clarifications. Thanks!

Christine

![glos_portal_1](https://cloud.githubusercontent.com/assets/6392982/19808337/6e33c0a8-9cf2-11e6-94ef-df51db4b217d.PNG)
![glos_portal_2](https://cloud.githubusercontent.com/assets/6392982/19808338/6e386202-9cf2-11e6-92b0-3d7e8a12a793.PNG)

**Comment by kknee** [comment]
I think there are two things in play here:
1. MTRI map services are EPSG 4326, but our GFI sends coordinates in EPSG 3857.  There is already a known issue that the GFI doesn't always return results because of the projection difference.

so...why does the same GFI work for Christine for some dates and not for others....
1. Take a look at the two screenshots closely, the newer image is much higher resolution than the previous image. So a working GFI for one resolution may not work in the other because of No. 1 above.

I think this is an issue for MTRI to investigate first.

**Comment by kknee** [comment]
This is fixed.  We decided to unproject the coordinates in our request rather than ask MTRI for changes.  @kkoch will you get in touch with the user?

**Comment by kkoch** [comment]
Email sent to user.  Will let you know if this resolves it for her.

**Comment by kkoch** [comment]
User reports all is well with the world.
