### ISSUE TITLE
Add GLCFS 50-day netcdf files for days 101-150, and 251-300

### ISSUE THREAD

**Issue by kknee** [glos/myglos#85]
From Greg:

I've posted the GLCFS 50-day netcdf files:
http://www.glerl.noaa.gov/emf/glcfs/tmp/forTad/

There are 34 files, totaling 11 GB.

These would replace the 6-hr nowcast-2d, nowcast-3d, and nowcast-forcing files for doys 101-150, and 251-300.

For example:
http://tds.glos.us/thredds/catalog/glos/glcfs/archivecurrent/michigan/ncfmrc-2d/files/catalog.html
http://tds.glos.us/thredds/catalog/glos/glcfs/archivecurrent/michigan/ncfmrc-3d/files/catalog.html
http://tds.glos.us/thredds/catalog/glos/glcfs/archivecurrent/michigan/nowcast-forcing-fmrc-2d/files/catalog.html

Let me know if you have any questions or difficulty downloading the files.  And please let me know when you've grabbed all of of them so that I can delete then from our server.

**Comment by cheryldmorse** [comment]
All of the files have been updated on the TDS.
