### ISSUE TITLE
HABs portal back data unavailable

### ISSUE THREAD

**Issue by kkoch** [glos/myglos#86]
From: Abigail Tomasek <toma0074@umn.edu>
Sent: Monday, December 19, 2016 4:22 PM
To: dmac@glos.us
Subject: [GLOS DMAC] Problem with HABs data portal 
 
Hello, 

I am trying to download phycocyanin and temperature data from Lake Erie buoys for 2016. It appears that there might be an issue with the website and the data isn't available for the buoys before November (all variables are reporting as 0). Is there a workaround for this? And if not, will the website be updated soon?

Thank you for your help,

Abigail Tomasek

**Comment by kkoch** [comment]
Tad and Cheryl checked thredds and data seems available - just not showing in portal.  Possible aggregation issue?

Tad replied to user > The data are available (not as conveniently) through the GLOS THREDDS Data Server - see 
[http://tds.glos.us/thredds/catalog/glos/habs/lakes/ysi_blue_green_algae/catalog.html]
[http://tds.glos.us/thredds/catalog/glos/habs/lakes/sea_surface_water_temperature/catalog.html]

**Comment by lukecampbell** [comment]
I found the issue. At some point the netCDF the variable names of the files switched from "blue_green_algae" to "ysi_blue_green_algae". This broke the THREDDS aggregation.

http://tds.glos.us/thredds/dodsC/glos/habs/lakes/ysi_blue_green_algae/leorgn/2016/leorgn_ysi_blue_green_algae_2016263.nc.html

http://tds.glos.us/thredds/dodsC/glos/habs/lakes/ysi_blue_green_algae/leorgn/2016/leorgn_ysi_blue_green_algae_2016366.nc.html

The next step would be for someone to go through every file and change the variable name to be consistent, using [ncrename](http://nco.sourceforge.net/nco.html#ncrename-netCDF-Renamer)

**Comment by kknee** [comment]
@kkoch @tslawecki is the above change something that you would like us to tackle or something @gcutrell can do?

**Comment by gcutrell** [comment]
@tslawecki is out on vacation and may be slow to respond. Changing the variable names seems straight forward. Do we want to rename all the old variables "ysi_blue_green_algae"? 

Any idea on why on why there was a name change @lukecampbell? It looks like the platform configurations on process1, which all define the variable name as "ysi_blue_green_algae", have not been modified since 2015.

**Comment by lukecampbell** [comment]
I don't know why there was a name change but files before November of 2016 are named "blue_green_algae" instead of "ysi_blue_green_algae". Maybe more.

**Comment by kknee** [comment]
@gcutrell - please also note that blue_green_algae is just an example - multiple variables seem to have 'ysi_' added to the name after Nov 2016.

**Comment by lukecampbell** [comment]
I just checked and this is still outstanding, we need to patch the files. Let me know if I should take a look.

**Comment by gcutrell** [comment]
Luke, I was planning on tackling this ticket this week, but won't have time. If you could look into the issue more that would be great. I will have some availability next week to help it needed.

**Comment by lukecampbell** [comment]
Ok, I'll take a look at it now. On a historical note, I think I see what happened. It looks like when the metadata attributes were updated, the variable names got perhaps mistakenly altered as well.

![screen shot 2017-01-19 at 1 37 38 pm](https://cloud.githubusercontent.com/assets/1155163/22120160/7724a3bc-de4c-11e6-9b28-7eea271df640.png)

**Comment by lukecampbell** [comment]
I fixed the files but I can't access wms.glos.us to restart the HABS portal and re-harvest dataset metadata from THREDDS.

**Comment by lukecampbell** [comment]
![screen shot 2017-01-19 at 2 49 34 pm](https://cloud.githubusercontent.com/assets/1155163/22122588/870c22b4-de56-11e6-9f6d-a22e5de2d14c.png)

**Comment by lukecampbell** [comment]
This all set now.
