### ISSUE TITLE
TDS catalog "Current Year" not pointing to 2017 files.

### ISSUE THREAD

**Issue by kkoch** [glos/myglos#88]
From Greg Lang, NOAA >

FYI, TDS catalog "Current Year" not pointing to 2017 files.

http://tds.glos.us/thredds/glcfs/glcfs_nowcast.html
http://tds.glos.us/thredds/glcfs/glcfs_forcing.html

And there are no 2017 files:
http://tds.glos.us/thredds/glcfs/glcfs_nowcast.html
http://tds.glos.us/thredds/glcfs/glcfs_forecast.html
http://tds.glos.us/thredds/glcfs/glcfs_forcing.html

Greg

-- 
Gregory A. Lang
NOAA/Great Lakes Environmental Research Lab
4840 South State Rd.
Ann Arbor, MI 48108-9719
(734) 741-2250
https://www.glerl.noaa.gov

**Comment by kkoch** [comment]
? possibly related to http:// to https:// disabling/enabling issue

**Comment by kknee** [comment]
GLERL switched to https 8 weeks ago - @cheryldmorse will update script links to https, create 2017 TDS directories, and look into what else is going on.

**Comment by lukecampbell** [comment]
- [x] GLCFS Nowcast Files exist and "current year" points to 2017
- [x] GLCFS Forcing Files exist and "current year" points to 2017
- [x] GLCFS Forecast Files exist and "current year" points to 2017

**Comment by lukecampbell** [comment]
![download](https://cloud.githubusercontent.com/assets/1155163/22077644/0cdc2c88-dd83-11e6-974a-867a0f1e288e.png)

**Comment by lukecampbell** [comment]
I think this is fixed.

**Comment by kknee** [comment]
this is indeed all set.
