### ISSUE TITLE
Thredds out of disk space

### ISSUE THREAD

**Issue by kkoch** [glos/myglos#92]
Greg C just checked Munin on our remote server and it looks like thredds has run out of disk space (maxed out at 99.94%.

**Comment by kkoch** [comment]
Note: I assigned this to @cheryldmorse because I think you worked on this after Guan left.  Please re-assign if it's really someone else.  And @gcutrell added you just to keep you in the loop.

**Comment by lukecampbell** [comment]
This is resolved, we now have enough space
