### ISSUE TITLE
GLCFS 2016 query not working

### ISSUE THREAD

**Issue by kkoch** [glos/myglos#93]
Ed reports that he can’t access results from GLCFS for 2016 using the following query:

http://data.glos.us/glcfs/glcfsps.glos?lake=erie&i=-81.821&j=41.615&v=wvh&st=2016-01-01:00:00:00&et=2016-10-31:00:00:00&u=e&order=asc&doy=1&tzf=-5&f=csv 

Can someone take a look and determine if this is related to the thredds disk space issue or if it is something else?

**Comment by lukecampbell** [comment]
I get data from that URL and it looks right. Can you verify that this is still an issue?

**Comment by kkoch** [comment]
Tad fixed last week  > 1/13/17 "Access to archived 2016 model results through the Point Query Tool is now available."  Cheryl restarted TDS but Tad found it required a tomcat restart as well.   (Kathy tried to restart tomcat since this is the same machine as GN but she didn't have SUDO privileges to do so.)
