### ISSUE TITLE
Logins/Passwords not working for several servers

### ISSUE THREAD

**Issue by kkoch** [glos/myglos#94]
Greg (and ASA?) have not being able to log into certain servers 

Greg tested each username/password that Tad provided. A quick summary is I can’t log into thredds.glos.us or mon.glos.us with either root/glosea. Gateway.glos.us times out all together when trying to connect and there are another four root passwords that don’t work. 

Per Tad, Greg to check with Guan and/or Luke (or someone else at ASA).

**Comment by kknee** [comment]
@cheryldmorse got in to the TDS through wms.glos.us. She can provide instructions to @gcutrell  but he should call her (401.789.6224) for the PW.  Can someone at LT please look into why access was suddenly cut off?

**Comment by lukecampbell** [comment]
We can now access tds.glos.us
