### ISSUE TITLE
Login Behavior - timing out of session

### ISSUE THREAD

**Issue by kkoch** [glos/myglos#99]
I'm not sure what the time period is for being logged in to myGLOS but the issue is that it seems to time out after a certain amount of time (I know I'm not logged in anymore only because it won't let me save permalinks or other logged in abilities) however it still shows me as being logged in when I click on the icon.  

![image](https://cloud.githubusercontent.com/assets/6392982/22486175/7953120c-e7d6-11e6-9283-b7933f93104a.png)

Thus one or more of three things needs to happen:
a) don't log me out at all - or at least don't log me out if I'm actively doing things
b) go ahead and time me out but come up with a pop up asking if I would like to remain in the session (similar to what my bank does if I'm sluggly about taking an action)
c) if you do log me out, make sure the icon for myglos login no longer shows me logged in

**Comment by kknee** [comment]
This issue should be moot now that we have adopted a different user management approach.
